### ISSUE TITLE
junos-eznc required version - not correct

### ISSUE THREAD

**Issue by tomehb** [Juniper/ansible-junos-stdlib#107]
States that >= 1.2.2 is required, but 1.3.1 is installed when running playbook to update configuration.

```
PLAY [NTP Update] **************************************************************

TASK [Checking NETCONF connectivity] *******************************************
ok: [MY-SRX]

TASK [junos_install_config] ****************************************************
fatal: [MY-SRX]: FAILED! => {"changed": false, "failed": true, "msg": "junos-eznc >= 1.2.2 is required for this module"}

PLAY RECAP *********************************************************************
MY-SRX     : ok=1    changed=0    unreachable=0    failed=1

(env) MAC:~/Ansible-JunOS/junos-deploy$pip list | grep junos-eznc
junos-eznc (1.3.1)
```

**Comment by dgarros** [comment]
Hi

Are you using py env ?
There is a known issue related to py env
if this is the case, please install the module from github directly
thanks
Damien


--
Damien GARROS
dgarros@gmail.com

**Comment by tomehb** [comment]
Thanks Damien, confirmed as working

Tom


On Tuesday, 16 February 2016, Damien <notifications@github.com> wrote:

> Hi
>
> Are you using py env ?
> There is a known issue related to py env
> if this is the case, please install the module from github directly
> thanks
> Damien
>
>
> --
> Damien GARROS
> dgarros@gmail.com <javascript:_e(%7B%7D,'cvml','dgarros@gmail.com');>
>
> On Mon, Feb 15, 2016 at 4:40 PM, tomehb <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > States that >= 1.2.2 is required, but 1.3.1 is installed when running
> > playbook to update configuration.
> >
> > PLAY [NTP Update]
> **************************************************************
> >
> > TASK [Checking NETCONF connectivity]
> *******************************************
> > ok: [MY-SRX]
> >
> > TASK [junos_install_config]
> ****************************************************
> > fatal: [MY-SRX]: FAILED! => {"changed": false, "failed": true, "msg":
> "junos-eznc >= 1.2.2 is required for this module"}
> >
> > PLAY RECAP
> *********************************************************************
> > MY-SRX : ok=1 changed=0 unreachable=0 failed=1
> >
> > (env) MAC:~/Ansible-JunOS/junos-deploy$pip list | grep junos-eznc
> > junos-eznc (1.3.1)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Juniper/ansible-junos-stdlib/issues/107>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Juniper/ansible-junos-stdlib/issues/107#issuecomment-184733505>
> .
>


-- 

------
Thomas Buchanan
Support Manager
Sohonet Limited

t : +44 (0)20 7292 6900
e : tom@sohonet.com
w: www.sohonet.com

24 7 support on :-
uk : +44 (0)20 7292 6909
us : +001 310 449 8610
aus: 1800 77 5280 H

**Comment by bitstacker** [comment]
Hi,
i have the same error ("junos-eznc >= 1.2.2 is required for this module").
Tried it with junos-eznc 1.3.1 but it didn't work.
I don't use py env (not that i know of) and using the latest junos-eznc from github (1.4.0-dev) didn't help either.
I use ansible 2.0.2.0 on ubuntu 14.04.

**Comment by vnitinv** [comment]
@bitstacker Whats your playbook content? Also share output of "pip list" and "ansible-galaxy list".
Have you tried with latest modules in github (by copying library content under /etc/ansible/roles/Juniper.juns/library)

**Comment by bitstacker** [comment]
cat playbooks/juniper.yml 
```
---
- hosts: juniper
  connection: local
  roles:
  - Juniper.junos
  - juniper
```
cat roles/juniper/tasks/main.yml 
```
---
- name: Install default config
  junos_install_config:
    host={{ inventory_hostname }}
    user=root
    file=default.conf
```
pip list
```
ansible (2.0.2.0)
apt-xapian-index (0.45)
argparse (1.2.1)
chardet (2.0.1)
colorama (0.2.5)
docopt (0.6.2)
html5lib (0.999)
httplib2 (0.8)
Jinja2 (2.7.2)
junos-eznc (1.3.1)
junos-netconify (1.0.2)
lxml (3.6.0)
MarkupSafe (0.18)
ncclient (0.4.7)
netaddr (0.7.18)
paramiko (2.0.0)
pip (1.5.4)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycurl (7.19.3)
pyserial (3.0.1)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.4.1)
scp (0.10.2)
setuptools (3.3)
six (1.5.2)
ssh-import-id (3.21)
urllib3 (1.7.1)
virtualenv (1.11.4)
wheel (0.24.0)
wsgiref (0.1.2)
```
ansible-galaxy list
`- Juniper.junos, 1.3.1`

I copied the library/ content from the latest github version to /etc/ansible/roles/Juniper.junos/library (The module was installed there with "ansible-galaxy install Juniper.junos")

Output:
```
ansible-playbook playbooks/juniper.yml 

PLAY [juniper] *****************************************************************

TASK [setup] *******************************************************************
ok: [my-juniper-host]

TASK [juniper : Install default config] ****************************************
fatal: [my-juniper-host]: FAILED! => {"changed": false, "failed": true, "msg": "junos-eznc >= 1.2.2 is required for this module"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @playbooks/juniper.retry

PLAY RECAP *********************************************************************
my-juniper-host      : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by bitstacker** [comment]
Got it running.
Seems like junos-eznc needed the python module "cryptography".
Installing it made the error disappear:
```
apt-get install libopenssl-dev
pip install cryptography
```

**Comment by vnitinv** [comment]
@bitstacker Great. Thanks

**Comment by dgarros** [comment]
@vnitinv,  
it looks like whatever is the issue, if the module is not capable to load PYEZ it return the same error message referring to the version number which is misleading when the error is somewhere else.

I think we should improve the error handling to make sure the right error message is passed to the user.
What do you think ?
Damien

**Comment by vnitinv** [comment]
@dgarros Totally agree.

**Comment by calvinchristopher** [comment]
any idea what the root issue may be @vnitinv ? My problems resurfaced after 2.1's release and weren't solved by @bitstacker's solution of `pip install cryptography` (already installed)

I am not running in a virtualenv, but I am using on OS X. Here's some debugging 💨 

`ansible $ ansible-playbook juniper.yml -vvv
Using /Users/calvinchristopher/Development/Python/ansible/ansible.cfg as config file

PLAYBOOK: juniper.yml **********************************************************
1 plays in juniper.yml

PLAY [vSRX] ********************************************************************

TASK [setup] *******************************************************************
<172.16.116.134> ESTABLISH LOCAL CONNECTION FOR USER: calvinchristopher
<172.16.116.134> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464409241.04-17527252741490 `" && echo ansible-tmp-1464409241.04-17527252741490="` echo $HOME/.ansible/tmp/ansible-tmp-1464409241.04-17527252741490 `" ) && sleep 0'
<172.16.116.134> PUT /var/folders/tm/7jrljygx3yg28jmwt9mxy7840000gn/T/tmpKu459w TO /Users/calvinchristopher/.ansible/tmp/ansible-tmp-1464409241.04-17527252741490/setup
<172.16.116.134> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/calvinchristopher/.ansible/tmp/ansible-tmp-1464409241.04-17527252741490/setup; rm -rf "/Users/calvinchristopher/.ansible/tmp/ansible-tmp-1464409241.04-17527252741490/" > /dev/null 2>&1 && sleep 0'
ok: [vsrx1]

TASK [collect default set of facts] ********************************************
task path: /Users/calvinchristopher/Development/Python/ansible/juniper.yml:4
<172.16.116.134> ESTABLISH LOCAL CONNECTION FOR USER: calvinchristopher
<172.16.116.134> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464409241.62-133541826915775 `" && echo ansible-tmp-1464409241.62-133541826915775="` echo $HOME/.ansible/tmp/ansible-tmp-1464409241.62-133541826915775 `" ) && sleep 0'
<172.16.116.134> PUT /var/folders/tm/7jrljygx3yg28jmwt9mxy7840000gn/T/tmpXmrniR TO /Users/calvinchristopher/.ansible/tmp/ansible-tmp-1464409241.62-133541826915775/junos_facts
<172.16.116.134> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/calvinchristopher/.ansible/tmp/ansible-tmp-1464409241.62-133541826915775/junos_facts; rm -rf "/Users/calvinchristopher/.ansible/tmp/ansible-tmp-1464409241.62-133541826915775/" > /dev/null 2>&1 && sleep 0'
fatal: [vsrx1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"config": true, "config_format": "set", "host": "vsrx1", "password": null, "port": null, "provider": null, "ssh_keyfile": null, "timeout": 0, "transport": "netconf", "username": null}, "module_name": "junos_facts"}, "msg": "junos-eznc >= 1.2.2 is required but does not appear to be installed"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @juniper.retry

PLAY RECAP *********************************************************************
vsrx1                      : ok=1    changed=0    unreachable=0    failed=1`

**Comment by calvinchristopher** [comment]
installed packages:

```
ansible $ pip list
ansible (2.1.0.0)
cffi (1.6.0)
cryptography (1.3.2)
enum34 (1.1.6)
idna (2.1)
ipaddress (1.0.16)
Jinja2 (2.8)
junos-eznc (1.3.1)
junos-netconify (1.0.2)
lxml (3.6.0)
MarkupSafe (0.23)
ncclient (0.4.7)
netaddr (0.7.18)
paramiko (2.0.0)
pip (8.1.2)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pyserial (3.1)
PyYAML (3.11)
scp (0.10.2)
setuptools (19.4)
six (1.10.0)
vboxapi (1.0)
virtualenv (15.0.1)
wheel (0.26.0)
ansible $
```

**Comment by calvinchristopher** [comment]
What a shame, I'm having the same issue on a fresh RHEL install; while that eliminates the OS X, it doesn't bring me any closer to a resolution.

Feel like I'm missing something obvious here, any feedback would be appreciated.

inventory file:
```
[juniper]
vsrx1 ansible_connection=local ansible_ssh_host=192.168.6.9 juniper_user=ansible  juniper_passwd=ansible1
```

playbook:
```
---
- hosts: juniper
  tasks:
    - name: collect default set of facts
      junos_facts:
        host: "{{ inventory_hostname }}"
        config: yes
        config_format: set
```

output:
```
Ansible $ ansible-playbook juniper.yml -vvv
Using /home/calvinchristopher/Development/Ansible/ansible.cfg as config file

PLAYBOOK: juniper.yml **********************************************************
1 plays in juniper.yml

PLAY [juniper] *****************************************************************

TASK [setup] *******************************************************************
<192.168.6.9> ESTABLISH LOCAL CONNECTION FOR USER: calvinchristopher
<192.168.6.9> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464443802.6-121851227957007 `" && echo ansible-tmp-1464443802.6-121851227957007="` echo $HOME/.ansible/tmp/ansible-tmp-1464443802.6-121851227957007 `" ) && sleep 0'
<192.168.6.9> PUT /tmp/tmpuqv0rx TO /home/calvinchristopher/.ansible/tmp/ansible-tmp-1464443802.6-121851227957007/setup
<192.168.6.9> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/calvinchristopher/.ansible/tmp/ansible-tmp-1464443802.6-121851227957007/setup; rm -rf "/home/calvinchristopher/.ansible/tmp/ansible-tmp-1464443802.6-121851227957007/" > /dev/null 2>&1 && sleep 0'
ok: [vsrx1]

TASK [collect default set of facts] ********************************************
task path: /home/calvinchristopher/Development/Ansible/juniper.yml:4
<192.168.6.9> ESTABLISH LOCAL CONNECTION FOR USER: calvinchristopher
<192.168.6.9> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1464443805.09-147653484443254 `" && echo ansible-tmp-1464443805.09-147653484443254="` echo $HOME/.ansible/tmp/ansible-tmp-1464443805.09-147653484443254 `" ) && sleep 0'
<192.168.6.9> PUT /tmp/tmppVk1bc TO /home/calvinchristopher/.ansible/tmp/ansible-tmp-1464443805.09-147653484443254/junos_facts
<192.168.6.9> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/calvinchristopher/.ansible/tmp/ansible-tmp-1464443805.09-147653484443254/junos_facts; rm -rf "/home/calvinchristopher/.ansible/tmp/ansible-tmp-1464443805.09-147653484443254/" > /dev/null 2>&1 && sleep 0'
fatal: [vsrx1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"config": true, "config_format": "set", "host": "vsrx1", "password": null, "port": null, "provider": null, "ssh_keyfile": null, "timeout": 0, "transport": "netconf", "username": null}, "module_name": "junos_facts"}, "msg": "junos-eznc >= 1.2.2 is required but does not appear to be installed"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @juniper.retry

PLAY RECAP *********************************************************************
vsrx1                      : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ntwrkguru** [comment]
Can you successfully invoke PyEZ outside of Ansible?

**Comment by calvinchristopher** [comment]
@ntwrkguru yes I can still execute PyEZ. 

```
api_JunosPyEZ $ python pyez_example.py
{'2RE': False,
 'HOME': '/cf/var/home/ansible',
 'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'model': 'FIREFLY-PERIMETER RE',
         'status': 'Testing',
         'up_time': '17 hours, 29 minutes, 27 seconds'},
 'domain': None,
 'fqdn': 'vSRX1',
 'hostname': 'vSRX1',
 'ifd_style': 'CLASSIC',
 'model': 'FIREFLY-PERIMETER',
 'personality': 'SRX_BRANCH',
 'serialnumber': '53b548eef005',
 'srx_cluster': False,
 'switch_style': 'NONE',
 'vc_capable': False,
 'version': '12.1X47-D15.4',
 'version_info': junos.version_info(major=(12, 1), type=X, minor=(47, 'D', 15), build=4),
 'virtual': True}
Interface: ge-0/0/0 Information
[('oper', 'up'), ('rx_packets', '10637'), ('macaddr', '00:0c:29:ee:f0:05'), ('description', None), ('rx_bytes', '1481661'), ('admin', 'up'), ('mtu', 1514), ('running', True), ('link_mode', 'Full-duplex'), ('tx_bytes', '703511711'), ('tx_packets', '3309194'), ('present', True)]
Interface: ge-0/0/1 Information
[('oper', 'up'), ('rx_packets', '3454221'), ('macaddr', '00:0c:29:ee:f0:0f'), ('description', None), ('rx_bytes', '740263539'), ('admin', 'up'), ('mtu', 1514), ('running', True), ('link_mode', 'Full-duplex'), ('tx_bytes', '448717'), ('tx_packets', '2499'), ('present', True)]
Welcome to the interactive shell
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
```

cannot execute ansible

```
ansible $ ansible-playbook juniper.yml

PLAY [vSRX] ********************************************************************

TASK [setup] *******************************************************************
ok: [vsrx1]

TASK [collect default set of facts] ********************************************
fatal: [vsrx1]: FAILED! => {"changed": false, "failed": true, "msg": "junos-eznc >= 1.2.2 is required but does not appear to be installed"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @juniper.retry

PLAY RECAP *********************************************************************
vsrx1                      : ok=1    changed=0    unreachable=0    failed=1

ansible $
```

**Comment by vnitinv** [comment]
Hi @calvinchristopher Can you share the PYTHONPATH environment. "echo $PYTHONPATH"
Also, share the path where PyEZ is installed. 
You can try by adding PyEZ installed path to PYTHONPATH. That helps most of the time. If you still face the problem, we can do a hangout session to resolve this. Will that be OK with you?

**Comment by calvinchristopher** [comment]
Thanks @vnitinv, I am not receiving anything returned when I use "echo $PYTHONPATH".

In an effort to avoid messing with my system's Python, I installed an alternative version through Homebrew. Here's my path:

```
~ $ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.path
['', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.11/F# Set architecture flags
rameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages']
```

**Comment by dgarros** [comment]
Hi 
can you try to define the variable `ansible_python_interpreter` 
You can put it inside your inventory or any variable file

```
## Inside your inventory
[all:vars]
ansible_python_interpreter=/usr/local/bin/python
```
For me It solved some issues related to python environment

**Comment by calvinchristopher** [comment]
@dgarros thank you so much, that's the missing piece.

```
juniper $ which python
/usr/local/bin/python
juniper $ ansible-playbook test.yml --ask-vault-pass
Vault password:

PLAY [Get Device Facts] ********************************************************

TASK [Checking NETCONF connectivity] *******************************************
ok: [jnprvsrx0001]

TASK [Retrieve info from devices] **********************************************
ok: [jnprvsrx0001]

TASK [version] *****************************************************************
ok: [jnprvsrx0001] => {
    "msg": "12.1X47-D15.4"
}

PLAY RECAP *********************************************************************
jnprvsrx0001               : ok=3    changed=0    unreachable=0    failed=0

juniper $
```

My only concern now is controlling this stream of joyous tears. Thanks again.

**Comment by stacywsmith** [comment]
Closing this issue.

Ansible actually only uses the shebang line to determine that the module is written in Python. If the line contains `python`, it is assumed to be a module written in Python.

Ansible best practice is that the line actually be:
```
#!/usr/bin/python
```

Regardless of the Python path in the shebang line, Ansible executes the module with the Python interpreter specified by the `ansible_python_interpreter` inventory variable. (note: this is an inventory variable, not an environment variable, configuration variable, or playbook variable.)

The value of `ansible_python_interpreter` defaults to `/usr/bin/python`. If your Python is in another location, you MUST set the `ansible_python_interpreter` variable to the correct value for your installation in the inventory file.

The value of

**Comment by klbnet** [comment]
Evening. 
I read through the thread and followed all instructions but I am still having a similar issue. I hate to bump it 3 years after the fact. 
Can anyone assist? I've gone through and made sure all the requirements/dependencies were installed and everything was updated. 


~~~~~~~~~~~~~~~~~
(.venv) klobue@dev3-atl1:~/ansible$ ansible --version
ansible 2.10.4
  config file = /home/klobue/ansible/ansible.cfg
  configured module search path = ['/home/klobue/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/klobue/ansible/network_ops/.venv/lib/python3.6/site-packages/ansible
  executable location = /home/klobue/ansible/network_ops/.venv/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
(.venv) klobue@dev3-atl1:~/ansible$
~~~~~~~~~~~~~~~~~~
(.venv) klobue@dev3-atl1:~/ansible$ head hosts
[all:vars]
ansible_python_interpreter=/usr/bin/python3
~~~~~~~~~~~~~~~~~~~~~
Jinja2 (2.11.2)
lxml (4.6.2)
ncclient (0.6.9)
netaddr (0.8.0)
netmiko (3.1.1)
paramiko (2.7.2)
pyparsing (2.4.7)
pyserial (3.5)
PyYAML (5.3.1)
scp (0.13.3)
six (1.15.0)
transitions (0.8.6)
yamlordereddictloader (0.4.0)
~~~~~~~~~~~~~~~~
(.venv) klobue@dev3-atl1:~/ansible$ ansible-galaxy list
# /home/klobue/.ansible/roles
- Juniper.junos, 2.4.3
- clay584.parse_genie, 1.4.0
[WARNING]: - the configured path /usr/share/ansible/roles does not exist.
[WARNING]: - the configured path /etc/ansible/roles does not exist.
~~~~~~~~~~~~~~~~~~~~~~~
(.venv) klobue@dev3-atl1:~/ansible$ ls -ltrha network_ops/.venv/lib/python3.6/site-packages/junos_eznc-2.5.4+8.gfc5debc-py3.6*
-rw-rw-r-- 1 klobue klobue  529 Dec 29 00:16 network_ops/.venv/lib/python3.6/site-packages/junos_eznc-2.5.4+8.gfc5debc-py3.6-nspkg.pth

network_ops/.venv/lib/python3.6/site-packages/junos_eznc-2.5.4+8.gfc5debc-py3.6.egg-info:
total 56K
-rw-rw-r--   1 klobue klobue    5 Dec 29 00:16 top_level.txt
-rw-rw-r--   1 klobue klobue  147 Dec 29 00:16 requires.txt
-rw-rw-r--   1 klobue klobue 1.6K Dec 29 00:16 PKG-INFO
-rw-rw-r--   1 klobue klobue    5 Dec 29 00:16 namespace_packages.txt
-rw-rw-r--   1 klobue klobue    1 Dec 29 00:16 dependency_links.txt
-rw-rw-r--   1 klobue klobue 5.9K Dec 29 00:16 SOURCES.txt
-rw-rw-r--   1 klobue klobue  11K Dec 29 00:16 installed-files.txt
drwxrwxr-x   2 klobue klobue 4.0K Dec 29 00:16 .
drwxrwxr-x 153 klobue klobue  12K Dec 29 00:59 ..
(.venv) klobue@dev3-atl1:~/ansible$
~~~~~~~~~~~~~~~~~~~~
#playbook from: https://www.juniper.net/documentation/en_US/junos-ansible/topics/topic-map/junos-ansible-commands-rpcs-executing.html#task-rpc-command-module-format-specifying

(.venv) klobue@dev3-atl1:~/ansible$ ansible-playbook -i hosts junos_rpc_example.yml --limit=*TA1.LAB1.PTN*

PLAY [Get device information] ****************************************************************************

TASK [Get software and system uptime information] ********************************************************
fatal: [TA1.LAB1.PTN]: FAILED! => {"changed": false, "msg": "junos-eznc (aka PyEZ) >= 2.5.0 is required for this module. However, junos-eznc does not appear to be currently installed. See https://github.com/Juniper/py-junos-eznc#installation for details on installing junos-eznc."}

PLAY RECAP ***********************************************************************************************
TA1.LAB1.PTN               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by rahkumar651991** [comment]
@klbnet - In your pip list, there is no mention of junos-eznc. You need to install junos-eznc as it is missing. 
``` pip install junos-eznc ```

**Comment by klbnet** [comment]
@rahkumar651991 I was so concerned with listing all requirements I left out the PyEZ ... It's there. I included the module folders as well. See below. Thank you for replying. 

(.venv) klobue@dev3-atl1:~/ansible$ pip list | grep -i jun
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
junit-xml (1.9)
junos-eznc (2.5.4+8.gfc5debc)
junos-netconify (1.0.2)

**Comment by klbnet** [comment]
Error messages I realize I also forgot to include. 
Also output showing netconf and jnpr.junos working. Not entirely sure how to test PyEZ without ansible or why ansible claims it is not installed. 

(.venv) klobue@dev3-atl1:~/ansible$ ansible-playbook -i hosts junos_facts.yml --limit=*TA1.LAB1.PTN*

PLAY [Get device facts and configuration] ****************************************************************

TASK [Retrieve device facts and configuration and save facts to file] ************************************
fatal: [TA1.LAB1.PTN]: FAILED! => {"changed": false, "msg": "junos-eznc (aka PyEZ) >= 2.5.0 is required for this module. However, junos-eznc does not appear to be currently installed. See https://github.com/Juniper/py-junos-eznc#installation for details on installing junos-eznc."}

PLAY RECAP ***********************************************************************************************
TA1.LAB1.PTN               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

(.venv) klobue@dev3-atl1:~/ansible$
(.venv) klobue@dev3-atl1:~/ansible$
(.venv) klobue@dev3-atl1:~/ansible$ ./pyeztest.py
{'2RE': False,
 'HOME': '/var/home/ipengineering',
 'RE0': {'last_reboot_reason': '0x1:power cycle/failure',
         'mastership_state': 'master',
         'model': 'RE-ACX-5448',
         'status': 'OK',
         'up_time': '19 days, 21 hours, 25 minutes, 12 seconds'},
 'RE1': None,
 'RE_hw_mi': False,
 'current_re': ['master', 'node', 'fwdd', 'member', 'pfem', 're0', 'localre'],
 'domain': None,
 'fqdn': 'TA1.LAB1.PTN',
 'hostname': 'TA1.LAB1.PTN',
 'hostname_info': {'re0': 'TA1.LAB1.PTN'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(20, 3), type=R, minor=1, build=8),
                        'text': '20.3R1.8'}},

**Comment by klbnet** [comment]
Friend helped to get it fixed. Even tho the ansible --version info showed the correct modules paths and all the other roles/modules worked without an issue PyEZ wouldn't work until I changed the ansible_python_interpreter to the one linked in the venv

(.venv) klobue@dev3-atl1:~/ansible$ head hosts
[all:vars]
ansible_python_interpreter=/home/klobue/ansible/network_ops/.venv/bin/python3
#ansible_python_interpreter=/usr/bin/python3

**Comment by rahkumar651991** [comment]
@klbnet  - while using venv, we need to set python interpreter path correctly. Good to know that issue is resolved.
