### ISSUE TITLE
junos_cli timeout

### ISSUE THREAD

**Issue by Knockturn** [Juniper/ansible-junos-stdlib#122]
Hi,
I had a problem with timeout while doing a "request" using the junos_cli module.

Please see attached stackoverflow for how I got around it. Perhaps you can add the timeout to this as well in the future?

http://stackoverflow.com/questions/35863701/ansible-juniper-cli-commands-timeout-error/35887731#35887731

**Comment by vnitinv** [comment]
thanks @Knockturn Will try to add timeout to this module.

**Comment by dgarros** [comment]
Hi @Knockturn 
I added a timeout option for both junos_cli and junos_rpc
Please can you check and confirm if it's working good
https://github.com/Juniper/ansible-junos-stdlib/pull/133
Thanks
Damien

**Comment by jbain** [comment]
junos_cli has a typo in it, submitted PR #135

**Comment by dgarros** [comment]
Closing as #135 as been merged
