### ISSUE TITLE
junos_get_table's RouteTable doesn't return route

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#125]
Not sure if py-junos-eznc or ansible-junos-stdlib issue.

Running:

```
- name: Get structured routing table
  hosts: all
  connection: local
  gather_facts: False
  roles:
    - Juniper.junos
  tasks:
    - name: Get route table
      junos_get_table:
        table=RouteTable
        file=routes.yml
        host={{ inventory_hostname }}
        port=22
      register: result

    - debug: var=result
```

Returns:

```
"result.resource": [
        {
            "age": 2328255, 
            "nexthop": "10.243.24.1", 
            "protocol": "Static", 
            "via": "fe-0/0/0.0"
        }, 
        {
            "age": 2328255, 
            "nexthop": null, 
            "protocol": "Direct", 
            "via": "fe-0/0/0.0"
        }, 
        {
            "age": 20460877, 
            "nexthop": null, 
            "protocol": "Local", 
            "via": "fe-0/0/0.0"
        }, 
        {
            "age": 20460885, 
            "nexthop": null, 
            "protocol": "Local", 
            "via": null
        }
    ]
```

Looking at https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/op/routes.yml#L11 the key should be the route.
Let me know if I can help troubleshooting it more.

**Comment by vnitinv** [comment]
@XioNoX Arzhel, it would be great if you too contribute in troubleshooting.

**Comment by XioNoX** [comment]
@vnitinv Sure, what can I do to help?

**Comment by jedelman8** [comment]
@vnitinv  what is the difference between "key" and "args_key" in a Table definition and how is "args_key" accessed as a Device property?

**Comment by stacywsmith** [comment]
@jedelman8 

"key" is an XPath expression used to select an XML element within each table item. The value of the XML element becomes the key used to access each item within the native Python data structure.
If "key" is not specified, the XPath "name" is used as the value of "key". If multiple XML elements are required to uniquely identify a table item, the value of this key is a YAML list containing an XPath for each XML element that forms the key. It is recommended to explicitly specify "key" even if its value is set to the default of "name".

"args_key" is the name of one optional unnamed  first argument to the get() method.
For example, the prepackaged RouteTable definition includes:
```
RouteTable:
  rpc: get-route-information
  args_key: destination
```
This definition allows the user to call:
```
>>> route_table.get('10.0.0.0/8')
```
Which causes the following RPC to be sent to the Junos device:
```
<get-route-information>
    <destination>10.0.0.0/8</destination>
</get-route-information>
```

I don't currently know of a way to retrieve the "args_key" value as a Device property.

**Comment by vnitinv** [comment]
Hi @XioNoX I tried my edited table and able to get route names too. 

```yml
    - junos_get_table:
        table=RouteTable
        path=/Users/nitinkr/Desktop
        file=routes.yml
        host={{ inventory_hostname }}
        user='xxxx'
        passwd='xxxx'
      register: junos

    - name: Print table view data
      debug: msg="{{ junos }}"
```

Table being used:
```yml
RouteTable:
  rpc: get-route-information
  args_key: destination
  item: route-table/rt
  key: rt-destination
  view: RouteTableView

RouteTableView:
  groups:
    entry: rt-entry
  fields_entry:
    # fields taken from the group 'entry'
    protocol: protocol-name
    via: nh/via | nh/nh-local-interface
    age: { age/@seconds : int }
    nexthop: nh/to
    route: ../rt-destination
```
check out for **route: ../rt-destination**

output:
```json
            {
                "age": 693230, 
                "nexthop": "xx.xxx.xx.xxx", 
                "protocol": "Static", 
                "route": "xxx.xx.xxx.0/23", 
                "via": "xx0.0"
            }, 
            {
                "age": 693230, 
                "nexthop": "xx.xxx.63.254", 
                "protocol": "Static", 
                "route": "xxx.xx.xxx.0/24", 
                "via": "xx0.0"
            }
```
So we get routes name too.
Is that what you wanted or I am getting it wrong.

**Comment by stacywsmith** [comment]
I believe this has been resolved. If not, please reopen the issue.
