### ISSUE TITLE
"Uncaught exception - please report: Type 'str' cannot be serialized."

### ISSUE THREAD

**Issue by andyjsharp** [Juniper/ansible-junos-stdlib#137]
fatal: [cswj-ngcn-1085]: FAILED! => {"changed": false, "failed": true, "msg": "Uncaught exception - please report: Type 'str' cannot be serialized."}

Executing junos_cli against an EX VC produced the above message.  The actual error reported via cli/rpc was "the chassis-control subsystem is not responding to management requests".

It would be great if the actual rpc error or error message was returned rather than an uncaught exception, then such cases could be managed such as executing "restart chassis-contol immediately all-members" to resolve the issue and permit provisioning to continue instead of failing.

Thanks.

**Comment by spidercensus** [comment]
What was the actual CLI command?

**Comment by andyjsharp** [comment]
"show chassis hardware detail"

**Comment by dgarros** [comment]
@andyjsharp agreed it would be better to check for error in the response and manage that properly.

@vnitinv, is there an easy way today with Pyez to know if an RPC call returned an error or not ?
It would be a great feature to have if not already available.

**Comment by dgarros** [comment]
Second try :) 
@vnitinv, is there an easy way today with Pyez to know if an RPC call returned an error or not ?
It would be a great feature to have if not already available.

**Comment by vnitinv** [comment]
@dgarros dev.cli tries to replicate how cli works. Hence it would return string error message in place of exception. I feel in our junos_cli module we should use dev.rpc.cli to handle cli rather than dev.cli. With that we will have more control over all featuers we want to support and even exception handling. What's your view?

**Comment by dgarros** [comment]
@vnitinv I was not aware of the differences between `dev.rpc.cli` and `dev.cli`, I thought the latter was a shortcut to the `dev.rpc.cli`

If error handling is better in `dev.rpc.cli` we should definitely give it a try

What is the down side to use `dev.rpc.cli` instead of `dev.cli` ?

**Comment by vnitinv** [comment]
@dgarros Just that we need to take care of these (if needed) also in the junos_cli module 

https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/device.py#L679-L702

**Comment by stacywsmith** [comment]
The new `juniper_junos_command` module replaces `junos_cli`. It was implemented via #285.

The new module includes better error handling and reporting of this situation and others.
