### ISSUE TITLE
error with "junos_get_config" if I use the parameter "filter" with slash notation 

### ISSUE THREAD

**Issue by ksator** [Juniper/ansible-junos-stdlib#141]
I am facing the following issue with the module junos_get_config and the optional parameter filter:
-if I do not use this parameter, it is working well.
-If I use it to retrieve part of the config only with a basic filter (interfaces as example, system as example, ...), it is OK as well.
-if I use it with slash notation (system/name-server as example) as suggested in the doc, it doesnt work (Ansible error).
I tried with various hierarchies, I tried with and without quotes, I tried with text and xml formats, I tried with Various Ansible version. 
Are you facing the same issue? is it  a bug with this module? or is it the doc? or is it me?
Many thanks in advance!
Cheers
Khelil

**Comment by vnitinv** [comment]
@ksator Do let me know if the mail (sent on same line) works for you.

**Comment by ksator** [comment]
Hello,
I tested (filter=system/login into junos_get_config module) with latest code from github instead of the one available in  galaxy and it works.
I am closing this  issue on github as gitbub code is clean (galaxy only has this issue).
Many thanks!
