### ISSUE TITLE
enhance junos_install_os to add flexibility to install on backup RE first.

### ISSUE THREAD

**Issue by mcdoug62** [Juniper/ansible-junos-stdlib#149]
Common practice for upgrading dual-RE systems is to upgrade junos on the backup RE first.  Then, once it's upgraded do a mastership switch and repeat the process on the former master RE.     The current junos_install_os does not allow this sort of flexibility, and can only install on RE0, then RE1.   

The module needs to be enhanced to allow installation on an ordered list of REs (eg "re1, re0").  (The list could be a list of one.)

**Comment by stacywsmith** [comment]
The new `juniper_junos_software` module implemented in #296 allows the ability to specify the `all_re: false` option. This causes the software to only be installed on the current Routing Engine. This isn't exactly what's requested in this issue, but it does allow that functionality to be implemented if a playbook is written to first connect to and upgrade the backup Routing Engine and then connect to and upgrade the primary Routing Engine.

Implementing the requested functionality will require enhancing PyEZ first. However, I'm not sure PyEZ and/or Ansible can cover all of the user-defined MOPs for upgrading software. Most users are going to want to perform verifications on the new software of the backup RE before proceeding with an RE switchover, and then finally upgrading the software on the (former) primary RE.

Assuming both RE's have NETCONF over SSH reachability, the current modules allow the flexibility for the user to automate any MOP for upgrading a dual-RE system.

If you feel this needs to be supported directly in PyEZ, please begin by opening a PyEZ issue.
