### ISSUE TITLE
Add “aliases” in both Core and Galaxy modules to homogenize the name of the input parameters

### ISSUE THREAD

**Issue by ydnath** [Juniper/ansible-junos-stdlib#170]
@dgarros Requested that the above enhancement is made. 
It’s something natively provided by Ansible, see an example here: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/openstack.py#L80
Currently
·         Core modules take: username & password
·         Galaxy modules take: user& passwd
It would be better if both could accept: username, user, passwd & password

**Comment by dgarros** [comment]
Thanks @ydnath, 
I did a workshop with @stacywsmith  for some customers on Ansible yesterday and many faced this issue. 

I think we should also send a pull request to add the aliases on the core modules.

Thanks
Damien

**Comment by stacywsmith** [comment]
Aliases have been added to the modules in this repository via #278. All modules now support the same connection and authentication-related options as the core modules. This includes the ability to specify all connection and authentication-related options at the top level or inside a `provider` dictionary.

The full list of aliases includes:
```
Option Name            Aliases
-------------------------------------------------------------------
host                   hostname, ip   (also now defaults to {{ inventory_hostname }} so it no longer has to be explicitly specified.)
user                   username
passwd                 password
ssh_private_key_file   ssh_keyfile
```
