### ISSUE TITLE
Callback plugin jsnapy not working

### ISSUE THREAD

**Issue by eugeneee** [Juniper/ansible-junos-stdlib#173]
Not getting output as described after installing jsnapy callback plugin. Seen jsnapy compiled after execution of ansible-playbook:

root@ubuntu:/home/automation/Project/Ansible/callback_plugins# ls -lah
total 16K
drwxr-xr-x 2 root root 4.0K Nov  2 11:31 .
drwxr-xr-x 5 root root 4.0K Nov  2 11:25 ..
-rw-r--r-- 1 root root 2.3K Nov  2 11:26 jsnapy.py
-rw-r--r-- 1 root root 2.8K Nov  2 11:31 jsnapy.pyc

root@ubuntu:/home/automation/Project/Ansible# ansible-playbook -i hosts -M './custom_modules/' /home/automation/Project/Ansible/post_activity.yml

PLAY [Post Activity] ***********************************************************

TASK [post_activity : POST CHECKLIST -- Compare PRE and POST snapshot --] ******
ok: [192.168.128.10]

TASK [post_activity : Post Checklist -- debug comparison results ---] **********
ok: [192.168.128.10] => {
    "msg": {
        "action": "check", 
        "changed": false, 
        "final_result": "Failed", 
        "msg": "Test Failed: Passed 0, Failed 1", 
        "passPercentage": 0, 
        "router": "192.168.128.10", 
        "test_results": {
            "show task memory": [
                {
                    "count": {
                        "fail": 1, 
                        "pass": 0
                    }, 
                    "expected_node_value": [
                        1.0, 
                        85.0
                    ], 
                    "failed": [
                        {
                            "actual_node_value": "94", 
                            "id": {
                                "./task-memory-in-use-avail": "94"
                            }, 
                            "post": {
                                "task-memory-in-use-avail": "94"
                            }, 
                            "pre": {
                                "task-memory-in-use-avail": "4"
                            }
                        }
                    ], 
                    "node_name": "task-memory-in-use-avail", 
                    "passed": [], 
                    "result": false, 
                    "testoperation": "in-range", 
                    "xpath": "//task-memory-information"
                }
            ]
        }, 
        "total_failed": 1, 
        "total_passed": 0, 
        "total_tests": 1
    }
}

PLAY RECAP *********************************************************************
192.168.128.10             : ok=2    changed=0    unreachable=0    failed=0   

root@ubuntu:/home/automation/Project/Ansible# 

Appreciate assistance. Thanks!

**Comment by eugeneee** [comment]
Got some error:
 [WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fd5ac913b90>>: 'module' object has no attribute
'COLOR_ERROR'

root@ubuntu:/home/automation/Project/Ansible# ansible-playbook -i hosts -M './custom_modules/' /home/automation/Project/Ansible/post_activity.yml
PLAY [Post Activity] ***********************************************************

TASK [post_activity : POST CHECKLIST -- Compare PRE and POST snapshot --] ******
ok: [192.168.128.10]

TASK [post_activity : Post Checklist -- debug comparison results ---] **********
ok: [192.168.128.10] => {
    "msg": {
        "action": "check", 
        "changed": false, 
        "final_result": "Failed", 
        "msg": "Test Failed: Passed 0, Failed 1", 
        "passPercentage": 0, 
        "router": "192.168.128.10", 
        "test_results": {
            "show task memory": [
                {
                    "count": {
                        "fail": 1, 
                        "pass": 0
                    }, 
                    "expected_node_value": [
                        1.0, 
                        85.0
                    ], 
                    "failed": [
                        {
                            "actual_node_value": "94", 
                            "id": {
                                "./task-memory-in-use-avail": "94"
                            }, 
                            "post": {
                                "task-memory-in-use-avail": "94"
                            }, 
                            "pre": {
                                "task-memory-in-use-avail": "4"
                            }
                        }
                    ], 
                    "node_name": "task-memory-in-use-avail", 
                    "passed": [], 
                    "result": false, 
                    "testoperation": "in-range", 
                    "xpath": "//task-memory-information"
                }
            ]
        }, 
        "total_failed": 1, 
        "total_passed": 0, 
        "total_tests": 1
    }
}

JSNAPy Results for: 192.168.128.10 *********************************************
 [WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fd5ac913b90>>: 'module' object has no attribute
'COLOR_ERROR'

I changed Line 42 of callback_plugin jsnapy from:
    if module_name == 'junos_jsnapy':
to 
    if module_name == 'junos_jsnapynitin2':

I'm using this custom module which Nitin Kumar rectified at:
root@ubuntu:/home/automation/Project/Ansible/custom_modules# ls
junos_getcli_logs2  junos_jsnapy2  junos_jsnapynitin  junos_jsnapynitin2  junos_pingtest2
root@ubuntu:/home/automation/Project/Ansible/custom_modules# pwd
/home/automation/Project/Ansible/custom_modules

**Comment by eugeneee** [comment]
My apologies. Just checked again and this is the error seen:
[WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fd250091b90>>: 'module' object has no attribute
'COLOR_ERROR'

root@ubuntu:/home/automation/Project/Ansible# ansible-playbook -i hosts -M './custom_modules/' /home/automation/Project/Ansible/post_activity.yml

PLAY [Post Activity] ***********************************************************

TASK [post_activity : POST CHECKLIST -- Compare PRE and POST snapshot --] ******
ok: [192.168.128.10]

TASK [post_activity : Post Checklist -- debug comparison results ---] **********
ok: [192.168.128.10] => {
    "msg": {
        "action": "check", 
        "changed": false, 
        "final_result": "Failed", 
        "msg": "Test Failed: Passed 0, Failed 1", 
        "passPercentage": 0, 
        "router": "192.168.128.10", 
        "test_results": {
            "show task memory": [
                {
                    "count": {
                        "fail": 1, 
                        "pass": 0
                    }, 
                    "expected_node_value": [
                        1.0, 
                        85.0
                    ], 
                    "failed": [
                        {
                            "actual_node_value": "94", 
                            "id": {
                                "./task-memory-in-use-avail": "94"
                            }, 
                            "post": {
                                "task-memory-in-use-avail": "94"
                            }, 
                            "pre": {
                                "task-memory-in-use-avail": "4"
                            }
                        }
                    ], 
                    "node_name": "task-memory-in-use-avail", 
                    "passed": [], 
                    "result": false, 
                    "testoperation": "in-range", 
                    "xpath": "//task-memory-information"
                }
            ]
        }, 
        "total_failed": 1, 
        "total_passed": 0, 
        "total_tests": 1
    }
}

JSNAPy Results for: 192.168.128.10 *********************************************
[WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fd250091b90>>: 'module' object has no attribute
'COLOR_ERROR'


PLAY RECAP *********************************************************************
192.168.128.10             : ok=2    changed=0    unreachable=0    failed=0

**Comment by eugeneee** [comment]
My apologies. Just checked again and this is the error seen:
[WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fd250091b90>>: 'module' object has no attribute
'COLOR_ERROR'

root@ubuntu:/home/automation/Project/Ansible# ansible-playbook -i hosts -M './custom_modules/' /home/automation/Project/Ansible/post_activity.yml

PLAY [Post Activity] ***********************************************************

TASK [post_activity : POST CHECKLIST -- Compare PRE and POST snapshot --] ******
ok: [192.168.128.10]

TASK [post_activity : Post Checklist -- debug comparison results ---] **********
ok: [192.168.128.10] => {
    "msg": {
        "action": "check", 
        "changed": false, 
        "final_result": "Failed", 
        "msg": "Test Failed: Passed 0, Failed 1", 
        "passPercentage": 0, 
        "router": "192.168.128.10", 
        "test_results": {
            "show task memory": [
                {
                    "count": {
                        "fail": 1, 
                        "pass": 0
                    }, 
                    "expected_node_value": [
                        1.0, 
                        85.0
                    ], 
                    "failed": [
                        {
                            "actual_node_value": "94", 
                            "id": {
                                "./task-memory-in-use-avail": "94"
                            }, 
                            "post": {
                                "task-memory-in-use-avail": "94"
                            }, 
                            "pre": {
                                "task-memory-in-use-avail": "4"
                            }
                        }
                    ], 
                    "node_name": "task-memory-in-use-avail", 
                    "passed": [], 
                    "result": false, 
                    "testoperation": "in-range", 
                    "xpath": "//task-memory-information"
                }
            ]
        }, 
        "total_failed": 1, 
        "total_passed": 0, 
        "total_tests": 1
    }
}

JSNAPy Results for: 192.168.128.10 *********************************************
[WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fd250091b90>>: 'module' object has no attribute
'COLOR_ERROR'


PLAY RECAP *********************************************************************
192.168.128.10             : ok=2    changed=0    unreachable=0    failed=0

**Comment by dgarros** [comment]
Please can you re-check with the latest code on Github, I made some changes last week
thanks
Damien

**Comment by eugeneee** [comment]
Hi Damien,

Still not getting the results :( I managed to find something though, the play recap shows okay. I wonder if that's the issue. I'll ping Nitin Kumar too.

I'm using the latest junos_jsnapy code from github to test this too and the latest jsnapy callback_plugin.

root@ubuntu:/home/automation/Project/Ansible# ansible-playbook -i hosts -M './custom_modules/' /home/automation/Project/Ansible/post_activity.yml

PLAY [Post Activity] ***********************************************************

TASK [post_activity : POST CHECKLIST -- Compare PRE and POST snapshot --] ******
ok: [192.168.128.10]

TASK [post_activity : Post Checklist -- debug comparison results ---] **********
ok: [192.168.128.10] => {
    "msg": {
        "action": "check", 
        "changed": false, 
        "final_result": "Failed", 
        "msg": "Test Failed: Passed 0, Failed 1", 
        "passPercentage": 0, 
        "router": "192.168.128.10", 
        "test_results": {
            "show task memory": [
                {
                    "count": {
                        "fail": 1, 
                        "pass": 0
                    }, 
                    "expected_node_value": [
                        1.0, 
                        85.0
                    ], 
                    "failed": [
                        {
                            "actual_node_value": "94", 
                            "id": {
                                "./task-memory-in-use-avail": "94"
                            }, 
                            "post": {
                                "task-memory-in-use-avail": "94"
                            }, 
                            "pre": {
                                "task-memory-in-use-avail": "4"
                            }
                        }
                    ], 
                    "node_name": "task-memory-in-use-avail", 
                    "passed": [], 
                    "result": false, 
                    "testoperation": "in-range", 
                    "xpath": "//task-memory-information"
                }
            ]
        }, 
        "total_failed": 1, 
        "total_passed": 0, 
        "total_tests": 1
    }
}

JSNAPy Results for: 192.168.128.10 *********************************************
 [WARNING]: Error when using <bound method CallbackModule.v2_playbook_on_stats of
</home/automation/Project/Ansible/callback_plugins/jsnapy.CallbackModule object at 0x7fdd685aab50>>:
'module' object has no attribute 'COLOR_ERROR'


PLAY RECAP *********************************************************************
192.168.128.10             : ok=2    changed=0    unreachable=0    failed=0

**Comment by eugeneee** [comment]
This works:
root@ubuntu:/home/automation/Project/Ansible# ansible-playbook -i hosts -M './custom_modules/' /home/automation/Project/Ansible/post_activity.yml

PLAY [Post Activity] ***********************************************************

TASK [post_activity : POST CHECKLIST -- Compare PRE and POST snapshot --] ******
ok: [192.168.128.10]

TASK [post_activity : Post Checklist -- debug comparison results ---] **********
ok: [192.168.128.10] => {
    "msg": {
        "action": "check", 
        "changed": false, 
        "final_result": "Failed", 
        "msg": "Test Failed: Passed 0, Failed 1", 
        "passPercentage": 0, 
        "router": "192.168.128.10", 
        "test_results": {
            "show task memory": [
                {
                    "count": {
                        "fail": 1, 
                        "pass": 0
                    }, 
                    "expected_node_value": [
                        1.0, 
                        85.0
                    ], 
                    "failed": [
                        {
                            "actual_node_value": "87", 
                            "id": {
                                "./task-memory-in-use-avail": "87"
                            }, 
                            "post": {
                                "task-memory-in-use-avail": "87"
                            }, 
                            "pre": {
                                "task-memory-in-use-avail": "4"
                            }
                        }
                    ], 
                    "node_name": "task-memory-in-use-avail", 
                    "passed": [], 
                    "result": false, 
                    "testoperation": "in-range", 
                    "xpath": "//task-memory-information"
                }
            ]
        }, 
        "total_failed": 1, 
        "total_passed": 0, 
        "total_tests": 1
    }
}

PLAY RECAP *********************************************************************
192.168.128.10             : ok=2    changed=0    unreachable=0    failed=0   


JSNAPy Results for: 192.168.128.10 *********************************************
Value of 'task-memory-in-use-avail' not 'in-range' at '//task-memory-information' with {"task-memory-in-use-avail": "87"}
