### ISSUE TITLE
junos_install_os support for different package versions.

### ISSUE THREAD

**Issue by andyjsharp** [Juniper/ansible-junos-stdlib#174]
Scenario:
MX running with 13.3 32bit release.

junos_install_os won't install a 64bit release of the same version of code as it doesnt identify a difference.

It would be greate to have a couple of additional options available for junos_install_os.
1.  force install option, this would ignore a scenario where the version number is the same, and would just proceed to install the package on the device.   In this way it would be possible to define a test within the playbook to check if the correct 64bit or 32bit release is installed, and force the installation.  Or force a "re-installation" of the same code version

2.  bit check.  e.g. 32 | 64 , if the device isnt running the appropriate required bit version, then the installation would proceed with the specificed package version.

**Comment by stacywsmith** [comment]
@andyjsharp I understand your issue and agree we need to fix this. I also agree with your suggestions for new options.

In the mean time, I believe you could workaround this issue by passing the `version` argument to the `junos_install_os` module. Simply set a value for `version` that does not match the currently installed version. Something like `version=foo` should work.

**Comment by andyjsharp** [comment]
Cheers Stacy, I think I can work around this with a few additional plays.  Won't be pretty, but will do the job.

Regards,
Andy

On 7 Nov 2016, at 10:41, Stacy W. Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@andyjsharp<https://github.com/andyjsharp> I understand your issue and agree we need to fix this. I also agree with your suggestions for new options.

In the mean time, I believe you could workaround this issue by passing the version argument to the junos_install_os module. Simply set a value for version that does not match the currently installed version. Something like version=foo should work.

-

**Comment by renetbo** [comment]
Hi,

There is an error raised at the reboot when using it with EX92K 16.1R1.11. The workaround it to enable the no_reboot and then run a new task that runs the request system reboot.

Thanks

B

**Comment by stacywsmith** [comment]
We still need to look into adding this capability. However, this will require enhancements to the PyEZ fact gathering system to report whether 32-bit or 64-bit kernel is currently installed.

**Comment by stacywsmith** [comment]
Will track under Juniper/py-junos-eznc#797
