### ISSUE TITLE
no-validate parameter in junos_install_os

### ISSUE THREAD

**Issue by panks21** [Juniper/ansible-junos-stdlib#175]
Currently the junos_install_os module doesn't have the no-validate as the optional parameter which can be passed to the router while upgrading. 
In case the validation fails the ansible-playbook returns the below error and the upgrade does not happen ---->

"An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1478266001.29-197296805243207/junos_install_os", line 2202, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1478266001.29-197296805243207/junos_install_os", line 256, in main
    results = junos_install_os(module, dev)
  File "/root/.ansible/tmp/ansible-tmp-1478266001.29-197296805243207/junos_install_os", line 204, in junos_install_os
    do_log(results['msg'], level='error')
TypeError: do_log() got an unexpected keyword argument 'level'

fatal: [mx9]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "junos_install_os"}, "parsed": false}"

**Comment by stacywsmith** [comment]
The `validate` option has now been added to the new `juniper_junos_software` module via #296.

The `validate` option defaults to `False` which is equivalent to specifying the `no-validate` keyword via the CLI. That means `no-validate` is now the default.

Validation may be enabled by specifying the `validate: true` option to `juniper_junos_software`
