### ISSUE TITLE
coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by blc325** [Juniper/ansible-junos-stdlib#190]
Getting this fatal response when trying to execute playbook below on an EX4300 virtual-chassis:
TASK [perform a system snapshot] ***********************************************
fatal: [10.199.244.247]: FAILED! => {"changed": false, "failed": true, "msg": "Uncaught exception - please report: coercing to Unicode: need string or buffer, NoneType found"}

      - name: perform a system snapshot
        junos_cli:
          host: "{{ inventory_hostname }}"
          user: "{{username}}"
          passwd: "{{userpasswd}}"
          cli: "request system snapshot slice alternate all-members"
          timeout: 600
        register: system_snapshot

**Comment by dgarros** [comment]
Hi 
Please can you provide more information to help with the troubleshooting
- Output of `request system snapshot slice alternate all-members | display xml`
- Ansible cli logs with high verbosity `-vvv`

thanks
Damien

**Comment by blc325** [comment]
I think it could be because there are long pauses between different parts of the message before EOF.



On Dec 6, 2016, at 10:53 PM, Damien <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
Please can you provide more information to help with the troubleshooting

  *   Output of request system snapshot slice alternate all-members | display xml
  *   Ansible cli logs with high verbosity -vvv

thanks
Damien

**Comment by blc325** [comment]
Here’s an example of the XML response with long pauses between FPCs.


Last login: Mon Nov 28 14:17:36 2016 from 192.168.254.1

brianchow@ubuntu:~$ ssh root@vc

Password:

--- JUNOS 14.1X53-D35.3 built 2016-03-01 02:32:19 UTC

root@4300VC:RE:1% cli



{master:1}

root@4300VC> request system snapshot slice alternate all-members | display xml

<rpc-reply xmlns:junos="http://xml.juniper.net/junos/14.1X53/junos">

    <multi-routing-engine-results>



        <multi-routing-engine-item>



            <re-name>fpc0</re-name>



            <snapshot-information>

                <inform>

                    <message>Formatting alternate root (/dev/da0s2a)...</message>

                </inform>

                /dev/da0s2a: 329.3MB (674472 sectors) block size 16384, fragment size 2048

                        using 4 cylinder groups of 82.34MB, 5270 blks, 10624 inodes.

                super-block backups (for fsck -b #) at:

                 32, 168672, 337312, 505952<snapshot-copy>

                <source-directory>/dev/da0s1a</source-directory>

                <destination-directory>/dev/da0s2a</destination-directory>

            </snapshot-copy>

            <archived-directory-list>

                <directory-name>/</directory-name>

            </archived-directory-list>

        </snapshot-information>

    </multi-routing-engine-item>



    <multi-routing-engine-item>



        <re-name>fpc1</re-name>



        <snapshot-information>

            <inform>

                <message>Formatting alternate root (/dev/da0s2a)...</message>

            </inform>

            /dev/da0s2a: 329.3MB (674472 sectors) block size 16384, fragment size 2048

                using 4 cylinder groups of 82.34MB, 5270 blks, 10624 inodes.

            super-block backups (for fsck -b #) at:

             32, 168672, 337312, 505952<snapshot-copy>

            <source-directory>/dev/da0s1a</source-directory>

            <destination-directory>/dev/da0s2a</destination-directory>

        </snapshot-copy>

        <archived-directory-list>

            <directory-name>/</directory-name>

        </archived-directory-list>

    </snapshot-information>

</multi-routing-engine-item>


    </multi-routing-engine-results>

    <cli>

<banner>{master:1}</banner>

    </cli>

        </rpc-reply>


{master:1}

root@4300VC> exit


From: Brian Chow <brianchow@juniper.net<mailto:brianchow@juniper.net>>
Date: Wednesday, December 7, 2016 at 8:02 AM
To: Juniper/ansible-junos-stdlib <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: Juniper/ansible-junos-stdlib <ansible-junos-stdlib@noreply.github.com<mailto:ansible-junos-stdlib@noreply.github.com>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: Re: [Juniper/ansible-junos-stdlib] coercing to Unicode: need string or buffer, NoneType found (#190)

I think it could be because there are long pauses between different parts of the message before EOF.



On Dec 6, 2016, at 10:53 PM, Damien <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
Please can you provide more information to help with the troubleshooting

  *   Output of request system snapshot slice alternate all-members | display xml
  *   Ansible cli logs with high verbosity -vvv

thanks
Damien

**Comment by stacywsmith** [comment]
The issue is because you are not passing the `dest` argument to the `junos_cli` module.

Your task is:
```
  - name: perform a system snapshot
    junos_cli:
      host: "{{ inventory_hostname }}"
      user: "{{username}}"
      passwd: "{{userpasswd}}"
      cli: "request system snapshot slice alternate all-members"
      timeout: 600
    register: system_snapshot
```

The `junos_cli` module does not return the output of the cli command. Instead, it saves the output in a file specified by the `dest` argument.

The documentation for the module correctly states the `dest` argument is **[required](https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_cli#L92).**

However, the module doesn't actually list the argument as [required](https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_cli#L136).

That's the reason you're getting the ambiguous error message. I'll fix the argument to be required, which will improve the error message, but you'll need to modify your playbook to correctly use the module.

If you want the output of the command, then I see two options:

1) Combine `junos_cli` with the file lookup.
```
---
- name: Perform a snapshot
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: perform a system snapshot
      junos_cli:
        host: "{{ inventory_hostname }}"
        user: "{{username}}"
        passwd: "{{userpasswd}}"
        cli: "request system snapshot slice alternate all-members"
        dest: "{{ inventory_hostname }}.snapshot_output.txt"
       timeout: 600
    - debug:
        msg: "The snapshot output is: {{ lookup('file', '{{ inventory_hostname }}.snapshot_output.txt') }}"
```

2) Use the core `junos_command` module:
```
---
- name: Perform a snapshot
  hosts: junos-all
  connection: local
  gather_facts: no
  tasks:
    - name: perform a system snapshot
      junos_command:
        host: "{{ inventory_hostname }}"
        user: "{{username}}"
        password: "{{userpasswd}}"
        commands:
          - "request system snapshot slice alternate all-members"
        format: text
      register: response
    - debug:
        msg: "The snapshot output is: {{ response.stdout }}"
```

**Comment by blc325** [comment]
OK. Thanks Stacy. I did not know it was required. Thought it was more for logging the interaction if I wanted to.



On Dec 7, 2016, at 2:31 PM, Stacy W. Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is because you are not passing the dest argument to the junos_cli module.

Your task is:

  - name: perform a system snapshot
    junos_cli:
      host: "{{ inventory_hostname }}"
      user: "{{username}}"
      passwd: "{{userpasswd}}"
      cli: "request system snapshot slice alternate all-members"
      timeout: 600
    register: system_snapshot


The junos_cli module does not return the output of the cli command. Instead, it saves the output in a file specified by the dest argument.

The documentation for the module correctly states the dest argument is required<https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_cli#L92>.

However, the module doesn't actually list the argument as required<https://github.com/Juniper/ansible-junos-stdlib/blob/master/library/junos_cli#L136>.

That's the reason you're getting the ambiguous error message. I'll fix the argument to be required, which will improve the error message, but you'll need to modify your playbook to correctly use the module.

If you want the output of the command, then I see two options:

  1.  Combine junos_cli with the file lookup.

---
- name: Perform a snapshot
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: perform a system snapshot
      junos_cli:
        host: "{{ inventory_hostname }}"
        user: "{{username}}"
        passwd: "{{userpasswd}}"
        cli: "request system snapshot slice alternate all-members"
        dest: "{{ inventory_hostname }}.snapshot_output.txt"
       timeout: 600
    - debug:
        msg: "The snapshot output is: {{ lookup('file', '{{ inventory_hostname }}.snapshot_output.txt') }}"


  1.  Use the core junos_command module:

---
- name: Perform a snapshot
  hosts: junos-all
  connection: local
  gather_facts: no
  tasks:
    - name: perform a system snapshot
      junos_command:
        host: "{{ inventory_hostname }}"
        user: "{{username}}"
        password: "{{userpasswd}}"
        commands:
          - "request system snapshot slice alternate all-members"
        format: text
      register: response
    - debug:
        msg: "The snapshot output is: {{ response.stdout }}"

**Comment by stacywsmith** [comment]
Handled by #193.
