### ISSUE TITLE
Request to optionally disable filesystem clean-up in junos_install_os

### ISSUE THREAD

**Issue by jeffbrl** [Juniper/ansible-junos-stdlib#200]
By default, junos_install_os will clean up the filesystem prior to copying the image to the device.  This is not desired behavior for some network operators as their tools and procedures expect local logs to be maintained in the upgrade/downgrade process.

I'd like to request a flag for the module to prevent the filesystem clean-up.

**Comment by stacywsmith** [comment]
This is now implemented via the new `juniper_junos_software` module introduced in #296.

The new `cleanfs` option supports this functionality. `cleanfs` defaults to to `true` unless the `no_copy` option is `true`. If you set `cleanfs: false`, then the `request system storage cleanup` will not be executed.
