### ISSUE TITLE
Update README.md to include role installation from github

### ISSUE THREAD

**Issue by jeffbrl** [Juniper/ansible-junos-stdlib#202]
The script mentioned in the README to add the cloned repo to $ANSIBLE_LIBRARY is useful for a test/dev environment but not production. If users of these modules accept the risk of using code that hasn't been pushed to Galaxy, let's show them how.

install_roles.yml
```
# from github
- src: https://github.com/Juniper/ansible-junos-stdlib
  name: Juniper.junos
```

Then run `sudo ansible-galaxy install -r install_roles.yml`

Unfortunately, I don't see an option to install from a commit. There is a tag option.

I can write a pull request for this change if the maintainers want this added to the README.

**Comment by dgjnpr** [comment]
@jeffbrl yes please.
