### ISSUE TITLE
junos_jsnapy default lookup directory for jsnapy configuration files is not correct

### ISSUE THREAD

**Issue by ksator** [Juniper/ansible-junos-stdlib#208]
Hello,

jsnapy default lookup directory for jsnapy configuration files is /etc/jsnapy 
/etc/jsnapy/jsnapy.cfg file contains default path for configuration files, snapshots and testfiles. If required, /etc/jsnapy/jsnapy.cfg can be overwrited.

junos_jsnapy default lookup directory for jsnapy configuration files is /etc/jsnapy/testfiles. 
https://github.com/Juniper/ansible-junos-stdlib/blob/jsnapy/library/junos_jsnapy#L85
https://github.com/Juniper/ansible-junos-stdlib/blob/jsnapy/library/junos_jsnapy#L191
This is not expected:  
default lookup directory for jsnapy tests files and inventory file is supposed to be /etc/jsnapy/testfiles, but the default lookup directory for jsnapy configuration files is supposed to be /etc/jsnapy (in order to be consistent with jsnapy command line tool and jsnapy python module). 
Can we fix it (i.e changing the default lookup directory for configuration files from /etc/jsnapy/testfiles  to /etc/jsnapy )? 

Also, junos_jsnapy ignores /etc/jsnapy/jsnapy.cfg. 

meanwhile, current workarounds are: 
- move your jsnapy configuration files is supposed to be /etc/jsnapy/testfiles
- or change the optional argurment dir of the junos_jsnapy module
- or use the absolute path for the argument config_file.
 
 
Many thanks

**Comment by rahkumar651991** [comment]
The default path is due to certain use cases.
It is recommended to use absolute path or move to the corresponding directory. 

Closing the issue.
