### ISSUE TITLE
junos_install_os fails to execute on a SRX320

### ISSUE THREAD

**Issue by epydd** [Juniper/ansible-junos-stdlib#227]
When trying to upgrade a SRX320, an exception is raised:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_tZXJlA/ansible_module_junos_install_os.py", line 307, in <module>
    main()
  File "/tmp/ansible_tZXJlA/ansible_module_junos_install_os.py", line 292, in main
    results = junos_install_os(module, dev)
  File "/tmp/ansible_tZXJlA/ansible_module_junos_install_os.py", line 221, in junos_install_os
    ok = sw.install(package, **sw_args)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 684, in install
    **kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 181, in pkgadd
    return self._parse_pkgadd_response(rsp)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 219, in _parse_pkgadd_response
    rc = int(got.findtext('package-result').strip())
AttributeError: 'NoneType' object has no attribute 'strip'
```

Heres the playbook:

```
- name: Generating configuration Files
  hosts: "E0"
  gather_facts: no
  connection: local
  roles:
    - Juniper.junos
  tasks:

    - name: Checking Conectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 5
    
    - name: "UPGRADE - Install Junos OS package"
      junos_install_os:
        logfile: "{{ inventory_hostname }}.log"
        host: "{{ inventory_hostname }}"
        version: "15.1X49-D75.5"
        package: "/var/ftp/junos-srxsme-15.1X49-D75.5-domestic.tgz"
        no_copy: true
        reboot: true
        reboot_pause: 0
```

Current version on SRX320:

```
root@E0> show version
Hostname: E0
Model: srx320
Junos: 15.1X49-D80.4
JUNOS Software Release [15.1X49-D80.4]
```

Package name:
`junos-srxsme-15.1X49-D75.5-domestic.tgz`

Im using:
junos-eznc (2.1.2.dev1)
Juniper.junos, 1.4.0

A previous error junos_get_facts prevented this opretaion to conclude on SRX320, but unfortunatly it does not seem to be the only problem.

**Comment by stacywsmith** [comment]
```
        package: "/var/ftp/junos-srxsme-15.1X49-D75.5-domestic.tgz"
```

Is this the package name and location on the SRX320?

**Comment by epydd** [comment]
No, its locally on the server running the playbook.

**Comment by stacywsmith** [comment]
Then you need to remove the `no_copy: true` argument.

If `no_copy: true` is present, the module does not copy the image from the Ansible server to the target device. Instead it assumes the package file (i.e. just the filename portion of the `package` value which is `junos-srxsme-15.1X49-D75.5-domestic.tgz` in your case) is already present in the `/var/tmp/` directory of the target device. If `/var/tmp/junos-srxsme-15.1X49-D75.5-domestic.tgz` isn't already present, you will get an exception. I'm not positive, but I believe that's the problem you are seeing here.

Please let me know if removing the `no_copy` argument resolves your issue.

**Comment by epydd** [comment]
after removing the `no_copy` it worked!

```
TASK [Checking Conectivity] ****************************************************
ok: [E0]

TASK [UPGRADE - Install Junos OS package 15.1X49-D75.5] ************************
changed: [E0]

PLAY RECAP *********************************************************************
E0                         : ok=2    changed=1    unreachable=0    failed=0
```

Output from SRX320 after upgrade:

```
Hostname: E0
Model: srx320
Junos: 15.1X49-D75.5
JUNOS Software Release [15.1X49-D75.5]
```

I think i was confused by this option (not leaving a file on the device, rather then using a local file)
I would suggest to update the description of the module (junos_install_os), the steps on top description, and the option `package` should consider that the file can be local on the device too.

Thanks for the support!

**Comment by stacywsmith** [comment]
@epydd Glad your issue is resolved. Yes, I agree the documentation could be improved in this area. I'll leave this issue open to track the documentation enhancement.

**Comment by stacywsmith** [comment]
Documentation has been updated as part of the new `juniper_junos_software` module introduced via #296.
