### ISSUE TITLE
junos_config doesn't work with Ansible 2.3

### ISSUE THREAD

**Issue by jalphonso** [Juniper/ansible-junos-stdlib#237]
junos_config worked with Ansible 2.2 and 2.2.1 but not with 2.3. The error message refers you to https://docs.ansible.com/ansible/network_debug_troubleshooting.html#category-unable-to-open-shell

**Comment by nzkller** [comment]
Hi @jalphonso 

What version of the ansible-junos-stdlib are you using?

For ansible 2.3 see this https://github.com/ansible/ansible/issues/23725

Best regards,

Nzkller

**Comment by jalphonso** [comment]
I believe it is the latest. I actually deployed it using our latest docker container juniper/pyez-ansible https://hub.docker.com/r/juniper/pyez-ansible/ Since junos_config is part of Ansible Core and not Ansible Galaxy how do we fix it? See https://docs.ansible.com/ansible/junos_config_module.html

**Comment by ntwrkguru** [comment]
@nzkiller, it's Ansible 2.3, but as @jalphonso mentions, `junos_config` is a core module. 

cc: @vnitinv @stacywsmith

**Comment by stacywsmith** [comment]
@jalphonso 

Ansible enabled host key checking by default for all core networking modules in Ansible 2.3. Host key checking was previously not enabled for the core Junos modules in Ansible 2.1 and 2.2. This might be the cause of the issue you are seeing. Either ensure you have a host key for your target device(s) in ~/.ssh/known_hosts or see this http://docs.ansible.com/ansible/intro_getting_started.html#host-key-checking

Note: Host key checking is still not enabled for the modules in this repository, even when these modules are used with Ansible 2.3.

If you're still having problems with the core `junos_config` module please consider opening an issue at https://github.com/ansible/ansible/issues
