### ISSUE TITLE
can't connect, have tried many methods

### ISSUE THREAD

**Issue by JerryS3** [Juniper/ansible-junos-stdlib#240]
Hi,
I have been chasing this for a while. I can't seem to connect to any of my qfx10k switches. I can use python-eznc and get box facts. I can ssh to the box either as root or admin, and I have done a ssh-add to make it password free. I have upgraded eznc to github current thinking that may be the problem. I'm out of ideas...

Here is the current playbook task:
    - name: install the config onto the running system
      junos_install_config:
        host={{ inventory_hostname }}
        file="{{ role_dir }}/files/{{ inventory_hostname }}.cfg"
        user=root
        comment="configured by ansible"
        overwrite=true
        logfile="/tmp/junos.log"

I get one of 2 errors
fatal: [pnpcoreB]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "junos_install_config"
    }, 
    "module_stderr": "/usr/bin/python: Operation not permitted\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
on command (from -vvv)
<10.201.0.32> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r 10.201.0.32 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''

or
fatal: [sgscoreA]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "junos_install_config"
    }, 
    "module_stderr": "", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
on command
<10.201.0.41> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/tmp/ansible-ssh-%h-%p-%r 10.201.0.41 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''

If I try using the admin user, i get that it can't run /bin/sh (reasonable since that account drops you into the cli and not a shell.)

any help on this?

**Comment by stacywsmith** [comment]
Can you please provide your complete playbook?

These modules don't follow the typical Ansible connection model where Ansible establishes and SSH connection to the target device, pushes the module code over that connection, and executes the module on the target device. Instead, they run locally on the Ansible host and use the PyEZ library to make a NETCONF over SSH connection to the Junos device.

As such, your playbook must include `connection: local`. It looks as if that might be missing in your case.

Here's an example playbook for `junos_install_config`:

```
---
- name: Install configuration
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Install the config
      junos_install_config:
        host: "{{ inventory_hostname }}"
        user: "{{ user }}"
        passwd: "{{ password} "
        file: "{{ inventory_hostname }}.set"
        diffs_file: "{{ inventory_hostname }}.diff"
      register: response
    - name: Print the response for debugging
      debug:
        var: response
```

Can you also confirm that you have Python installed in `/usr/bin/python` on your Ansible host?

**Comment by JerryS3** [comment]
If you look at the command that ansible is generating (from -vvv) is is trying to run the shell on the remote machine. The ansible machine is 10.201.0.63 and the juniper in this case was 10.201.0.41. When I looked at the requirements for the ansible role, it mentioned eznc but not PyEZ. I have the latest eznc and have done a trivial test to make sure it works. Why is my system trying to connect to the remote machine with ssh?

---
# tasks file for 10krtr
- hosts: core10ks
  roles:
    - ansible-junos-stdlib
  gather_facts: no
  vars:
    incvar_dir: /etc/ansible/include_vars
    role_dir: /etc/ansible/roles/10krtr
    ALLOW_JTAC: ""
  remote_user: root

  tasks:
    - name: load global bgp information
      include_vars: "{{ incvar_dir }}/bgp_vars.yaml"
      run_once: true

    - name: make sure there is a link in /tftpboot for this config
      local_action:
        file state=link path="/tftpboot/{{ inventory_hostname }}.cfg" src="{{ ro
le_dir }}/files/{{ inventory_hostname }}.cfg"

#    - name: make sure we have the latest software image running
#      junos_install_os:
#        host={{ inventory_hostname }}
#        version={{ junos_version }}
#        package={{ junos_image }}

    - name: generate the config and store it locally
      local_action:
        template src="{{ role_dir }}/templates/10kt2.j2" dest="{{ role_dir }}/fi
les/{{ inventory_hostname }}.cfg"

    - name: install the config onto the running system
      junos_install_config:
        host={{ inventory_hostname }}
        file="{{ role_dir }}/files/{{ inventory_hostname }}.cfg"
        user=root
        comment="configured by ansible"
        overwrite=true
        logfile="/tmp/junos.log"

    - name: store the config onto the router
      copy:
        src={{ role_dir }}/files/{{ inventory_hostname }}.cfg
        dest=/config/{{ inventory_hostname }}.cfg


 /usr/bin/python -V
Python 2.7.5
(centos 7 system)

**Comment by stacywsmith** [comment]
Sorry, PyEZ is the same as the `junos-eznc` package. 

Ansible is trying to run it on the remote machine because you haven't specified `connection: local` for your play.

Also, assuming you installed from from Galaxy, the name of the Ansible role where the Juniper modules is installed is `Juniper.junos`. So, you want your play to contain:

```
  roles:
    - Juniper.junos
 ```
rather than:
```
  roles:
    - ansible-junos-stdlib
```

**Comment by JerryS3** [comment]
connection: local was what I missed. I got it working now.
Many thanks for the assistance.
jerry

**Comment by stacywsmith** [comment]
@JerryS3 Glad it's working for you now.
