### ISSUE TITLE
junos_install_config template support

### ISSUE THREAD

**Issue by vnitinv** [Juniper/ansible-junos-stdlib#241]
Please add support for template option as per PyEZ load function

http://junos-pyez.readthedocs.io/en/2.1.0/jnpr.junos.utils.html#jnpr.junos.utils.config.Config.load

currently, sometimes it becomes quite tough to generate desired config using Ansible's template option.

**Comment by stacywsmith** [comment]
This is now implemented in the new `juniper_junos_config` module introduced via #290.

The `template` and `vars` options can be used to generate and load a configuration from a Jinja2 template.

Example:
```
    - name: Load from a Jinja2 template.
      juniper_junos_config:
        load: 'merge'
        format: 'xml'
        template: "{{ inventory_hostname }}.j2"
        vars:
          host: "{{ inventory_hostname }}"
      register: response
    - name: Print the complete response.
      debug:
        var: response
```
