### ISSUE TITLE
junos_install_os Failure

### ISSUE THREAD

**Issue by zgould** [Juniper/ansible-junos-stdlib#251]
Errors that I'm receiving::

TASK [Install JunOS Software] ******************************************************************************************************
task path: /home/zgould/junos_upgrade.yml:19
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/basic.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/_text.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/local/lib/python2.7/dist-packages/ansible/module_utils/six/_six.py
Using module file /etc/ansible/roles/Juniper.junos/library/junos_install_os
<192.168.244.27> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.244.27> EXEC /bin/sh -c 'echo ~ && sleep 0'
<192.168.244.27> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427 `" && echo ansible-tmp-1500670201.08-34156210799427="` echo /home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427 `" ) && sleep 0'
<192.168.244.27> PUT /tmp/tmpqKeHtn TO /home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427/junos_install_os
<192.168.244.27> EXEC /bin/sh -c 'chmod u+x /home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427/ /home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427/junos_install_os && sleep 0'
<192.168.244.27> EXEC /bin/sh -c '/usr/bin/python /home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427/junos_install_os; rm -rf "/home/zgould/.ansible/tmp/ansible-tmp-1500670201.08-34156210799427/" > /dev/null 2>&1 && sleep 0'
fatal: [192.168.244.27]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "host": "192.168.244.27",
            "issu": false,
            "logfile": "/var/log/ansible/software.log",
            "no_copy": false,
            "nssu": false,
            "package": "/tftpboot/juniper//jinstall-ex-2200-12.3R12.4-domestic-signed.tgz",
            "port": "830",
            "reboot": true,
            "reboot_pause": 10,
            "user": "databank",
            "version": "12.3R12.4"
        }
    },
    "msg": "internal error: choices for argument reboot are not iterable: frozenset([0, 'on', 'f', 'false', 1, 'no', 'n', '1', '0', 't', 'y', 'off', 'yes', 'true'])"
}
        to retry, use: --limit @/home/zgould/junos_upgrade.retry

##
YML File
##

- name: Install JunOS
  hosts: junos-sales-switch
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  vars:
   wait_time: 3600
   pkg_dir: /tftpboot/juniper/
   OS_version: 12.3R12.4
   OS_package: jinstall-ex-2200-12.3R12.4-domestic-signed.tgz
   log_dir: /var/log/ansible

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Install JunOS Software
    junos_install_os:
     user=databank
     host={{ inventory_hostname }}
     version={{ OS_version }}
     reboot=yes
     package={{ pkg_dir }}/{{ OS_package }}
     logfile={{ log_dir }}/software.log
    register: sw
    notify:
    - wait_reboot

  handlers:
  - name: wait_reboot
    wait_for: host={{ inventory_hostname }} port=830 timeout={{ wait_time }}
    when: not sw.check_mode

Any clue as to what's causing it? This is on an EX2200 chassis.

**Comment by stacywsmith** [comment]
@zgould Can you please include the content of your YAML file as a code snippet? That will avoid the formatting that seems to have occurred and allow us to see the exact content of your YAML file.

**Comment by stacywsmith** [comment]
@zgould In addition, please provide the output of `ansible-playbook --version`.

**Comment by stacywsmith** [comment]
@zgould No need to provide your YAML file as a code snippet. I have been able to reproduce your issue. I believe your issue is specific to the Ansible version. Can you please confirm the version of Ansible you are using?

**Comment by zgould** [comment]
Stacywsmith,

I'm using:

`Ansible - 2.4.0`
`Python - 2.7.12`

Thanks.

**Comment by stacywsmith** [comment]
@zgould Thanks for the version information. This issue appears to be specific to Ansible 2.4. I understand the issue, and I'm working on a fix.

**Comment by zgould** [comment]
@stacywsmith 

Sounds good. I rolled back to Ansible 2.3.x, and it's working like a charm now.

Thanks,

**Comment by stacywsmith** [comment]
@zgould I had previously been able to replicate your issue using the Ansible devel branch prior to the 2.4 releases. Now, I am no longer able to replicate the problem using the released version of Ansible 2.4.0. I'm going to close this issue. If you see the problem on a released version of Ansible, please re-open the issue.
