### ISSUE TITLE
Need file_name, pre_file, and post_file jsnapy parameters exposed to the junos_jsnapy module interface

### ISSUE THREAD

**Issue by jnpr-bowen** [Juniper/ansible-junos-stdlib#255]
Not having access to the file parameters on the jsnapy snap and check functions precludes having a test comparison against a "golden" test result, or creating a baseline test result. Adding the parameters as optional with defaults that match the current hard coded values should add functionality and maintain backward compatibility.

**Comment by chidanandpujar** [comment]
Hi @jnpr-bowen 
    Thanks,
     Old issue, closing the issue for now , please re-open if this issue needs to be fixed .

Thanks
