### ISSUE TITLE
Can't Specify SSH Key

### ISSUE THREAD

**Issue by supertylerc** [Juniper/ansible-junos-stdlib#26]
Specifying an SSH key with Ansible is not honored by the Juniper module.  With the key loaded to the device, the following error occurs:

```
TASK: [Deploying Configuration] ***********************************************
failed: [cs01.hq.adap.tv] => {"failed": true}
msg: unable to connect to cs01.hq.adap.tv: ConnectAuthError(cs01.hq.adap.tv)
failed: [as01.hq.adap.tv] => {"failed": true}
msg: unable to connect to as01.hq.adap.tv: ConnectAuthError(as01.hq.adap.tv)
failed: [fw01.hq.adap.tv] => {"failed": true}
msg: unable to connect to fw01.hq.adap.tv: ConnectTimeoutError(fw01.hq.adap.tv)

FATAL: all hosts have already failed -- aborting
```

This is with the following hosts configuration:

```
[network_hq]
cs01.hq.adap.tv ansible_ssh_private_key_file=/home/ops/.ssh/rtr_rsa
as01.hq.adap.tv ansible_ssh_private_key_file=/home/ops/.ssh/rtr_rsa
fw01.hq.adap.tv ansible_ssh_private_key_file=/home/ops/.ssh/rtr_rsa
```

I have verified that I can ssh when using that key.  The relevant configuration for the playbook:

```
  tasks:
    - name: Deploying Configuration
      junos_install_config:
        host={{ inventory_hostname }}
        user=ansible
        file=/tmp/{{ inventory_hostname }}.set
        logfile=/etc/ansible/logs/{{ inventory_hostname }}.log
        timeout="300"
```

And the log (which isn't helpful):

```
$ cat logs/cs01.hq.adap.tv.log
2014-06-13 09:24:57,657:CONFIG:cs01.hq.adap.tv:connecting to host: ansible@cs01.hq.adap.tv
2014-06-13 09:39:48,110:CONFIG:cs01.hq.adap.tv:connecting to host: ansible@cs01.hq.adap.tv
2014-06-13 10:05:38,849:CONFIG:cs01.hq.adap.tv:connecting to host: ansible@cs01.hq.adap.tv
2014-06-13 10:09:00,972:CONFIG:cs01.hq.adap.tv:connecting to host: ansible@cs01.hq.adap.tv
```

**Comment by jmorgan415** [comment]
Hi, I loaded the key via ssh-add and can ssh into the junos device (aliased to "mx_junos") manually just fine, but the junos module is generating this: msg: unable to connect to mx_junos: ConnectAuthError(mx_junos).  Any idea what I'm doing wrong?  Thanks in advance.

**Comment by vnitinv** [comment]
@jmorgan415 Share the content of your playbook and host file.

**Comment by jmorgan415** [comment]
Playbook:
---
- name: load_config
  hosts: mx_junos
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no


  tasks:
   - name: Checking NETCONF connectivity
     wait_for: host={{ inventory_hostname }} port=830 timeout=5

   - name: Create Manual Diversion
     junos_install_config:
       host={{ inventory_hostname }}
       user={{ ansible_ssh_user }}
       port=830
       file=files/conf_file.conf
       overwrite=false
       replace=false
       timeout=0
       diffs_file=logs/commit_check_log
       logfile=logs/commit_log

Hosts File (did not include real user):

# Define Junos hosts
mx_junos ansible_connection=local ansible_ssh_host=172.16.100.131 ansible_ssh_port=830 ansible_ssh_user=testuser


Note:  I am using Ubuntu 14.04.

**Comment by jmorgan415** [comment]
Playbook:

---
- name: load_config
  hosts: mx_junos
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
   - name: Checking NETCONF connectivity
     wait_for: host={{ inventory_hostname }} port=830 timeout=5

   - name: Create Manual Diversion
     junos_install_config:
       host={{ inventory_hostname }}
       user={{ ansible_ssh_user }}
       port=830
       file=files/conf_file.conf
       overwrite=false
       replace=false
       timeout=0
       diffs_file=logs/commit_check_log
       logfile=logs/commit_log

Hosts File (did not include real user):

mx_junos ansible_connection=local ansible_ssh_host=172.16.100.131 ansible_ssh_port=830 ansible_ssh_user=testuser

Note:  using Ubuntu 14.04, Ansible 1.9.2, junos-eznc 1.2.2.dev, and junos netconify 1.0.0.

**Comment by sdndude** [comment]
If you run the following from the command line, what do you get?

ssh -p 830 \<your device here\>

**Comment by jmorgan415** [comment]
It's prompting for a password.  The only way I can ssh is if I "ssh -i sshkey device".  If I add the -p 830, I get this:  

PTY allocation request failed on channel 0
shell request failed on channel 0

If I use -p 22, it works.  I have netconf setup properly as I have run plenty of other playbooks (using password instead of ssh) on the device, which used port 830.

**Comment by sdndude** [comment]
The problem is most likely that when you pushed the public key over to the device, you did so with ssh port 22.  You need to do it by scp -P 830 \<key file\> and I think it will work. I am doing this from memory and don;t have a system in front of me, so bear with me.  
Since in the playbook you are specifying port 830 and you loaded the public key via port 22 it will never work, it's always wanting the password.

**Comment by mamoudousy** [comment]
Hey i have a same problem. My error fatal: [QFX_17]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to XX.XX.XX.XX: ConnectAuthError(XX.XX.XX.XX)"}

**My inventory**   
QFX_17  ansible_connection=local ansible_ssh_host=XX.XX.XX.XX ansible_ssh_port=830    juniper_user=equiptest   juniper_passwd=****

**my playbook** 

- name: test
    hosts: QFX_17
    connection: local
  
  roles:
  - Juniper.junos
    
  tasks:
  - name: retrieve facts
     junos_facts: 
      host={{ ansible_ssh_host }}  
      user={{ ansible_ssh_user }} 
      passwd={{ juniper_passwd }}
     register: info
  
  - name: affichage
     debug: msg={{ info.facts }}


And i verified my Netconf connection with   ssh equiptest@QFX_17 -p 830 and i get this : 
PTY allocation request failed on channel 0
shell request failed on channel 0

Please can you help me to resolv my error . Thank you

**Comment by stacywsmith** [comment]
@mamoudousy Your issue is different. I responded in #220.
