### ISSUE TITLE
Junos_install_os tries to install OS on RE1 when the host has single RE

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#270]
Host = VM = mam1r (IP 10.221.133.177)
while running junos_install_os for this router which has single RE, installation fails with the below error.
Module tries to install image on the other RE where as the router has only one RE.

PLAY [Junos Core Modules] ********************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [mam1r]

TASK [Install Junos OS package] **************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: Could not connect to re1 : No route to host)
fatal: [mam1r]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_1DuT3B/ansible_module_junos_install_os.py\", line 307, in <module>\n    main()\n  File \"/tmp/ansible_1DuT3B/ansible_module_junos_install_os.py\", line 292, in main\n    results = junos_install_os(module, dev)\n  File \"/tmp/ansible_1DuT3B/ansible_module_junos_install_os.py\", line 221, in junos_install_os\n    ok = sw.install(package, **sw_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 718, in install\n    **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 176, in pkgadd\n    rsp = self.rpc.request_package_add(**args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py\", line 336, in _exec_rpc\n    return self._junos.execute(rpc, **dec_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 76, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 23, in wrapper\n    result = function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py\", line 722, in execute\n    errs=ex)\njnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: Could not connect to re1 : No route to host)\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/regress/mamathac/ANSIBLE/pb/all.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************
mam1r                      : ok=1    changed=0    unreachable=0    failed=1

Playbook:

(ANS_virtualenv) root@nms5-grpc-server1:/home/regress/mamathac/ANSIBLE/pb# cat all.pb
---
- name: Junos Core Modules
  hosts: [SINGLE]
  connection: local
  gather_facts: yes
  roles:
    - Juniper.junos

  tasks:
   - name: Install Junos OS package
     junos_install_os:
        host={{ inventory_hostname }}
        user=user
        passwd=password
        reboot=yes
        no_copy=no
        port=830
        version={{ OS_version }}
        package={{ pkg_dir }}/{{ OS_package }}
        logfile={{ log_dir }}/software.log
     register: sw
     notify:
     - wait_reboot

  vars:
   wait_time: 3600
   pkg_dir: /tmp
   OS_version: 17.3R1.10
   OS_package: junos-x86-64-17.3R1.10.vmdk
   log_dir: /var/log/ansible

**Comment by stacywsmith** [comment]
Hi @mamathac 

Any time your opening an issue against the modules in this project, it's helpful to include the output of NETCONF traceoptions from the target Junos device. Please configure:
```
set system services netconf traceoptions flag all
set system services netconf traceoptions file netconf.log
```
Then include the output from the resulting `/var/log/netconf.log` in the issue. This allows us to see the exact RPCs sent to the device, and the exact RPC responses produced by the device.

It's also helpful to know some version information. In the future, please include the version of:
Junos
PyEZ
The Juniper.junos Ansible role. 
(If you're using the latest development branch of PyEZ or the Juniper.junos role, then please include the date when you cloned/updated from GitHub.)

Please also include the model of Junos device. In this case, I was able to deduce you're using a VMX, but it's helpful if that's stated explicitly.

Often, it's also helpful if you can include the output of PyEZ facts gathering. Much of the PyEZ and Juniper.junos is dependent upon PyEZ facts gathering. In this particular case, it appears that PyEZ incorrectly identified this as a dual-RE device when it is actually a single-RE device.

You can execute this simple PyEZ script to print the PyEZ facts:
```
import sys
import getpass

from jnpr.junos.device import Device
from jnpr.junos.version import VERSION, DATE
from pprint import pprint

# Python3 is input(), Python2 is raw_input()
try:
    input = raw_input
except:
    pass

username = input('Device Username: ')
passwd = getpass.getpass('Device Password: ')

print("Version: %s, Date: %s" % (VERSION, DATE))

for hostname in sys.argv[1:]:
    print ("Connecting to %s..." % (hostname))
    dev = Device(host=hostname, user=username, passwd=passwd)
    dev.open()
    print("Facts for %s:" % hostname)
    pprint(dev.facts)
    if dev.master is None:
        mastership_state = "Unknown"
    elif dev.master:
        mastership_state = "Master"
    else:
        mastership_state = "Not Master"
    print("Mastership state: %s" % (mastership_state))
    print("RE Name: %s" % (dev.re_name))
    dev.close()
```

In your playbook, I see:
```
gather_facts: yes
```
While this isn't the cause of the problem, I recommend setting `gather_facts: no` in your playbook. This setting controls whether or not the default `setup` Ansible module is used to gather facts. In the case of `connection: local` it would end up executing the `setup` module against `localhost` (the Ansible control machine). This doesn't control fact gathering against the Junos device itself. That's done by calling the `junos_get_facts` module and is completely independent of the `gather_facts` setting. Setting `gather_facts: yes` doesn't break anything, but it is slower because it's executing an unnecessary step.

In your playbook, I also see:
```
OS_package: junos-x86-64-17.3R1.10.vmdk
```
This is not the correct image to upgrade an already running VMX instance. To upgrade an already running VMX instance, you should use:
```
junos-install-x86-64-17.3R1.10.tgz
```

Please retry your playbook with the suggested changes and provide the requested information. If you're not already using the latest released version of PyEZ (2.1.7), then please upgrade PyEZ and try to reproduce.

**Comment by mamathac** [comment]
Hi Stacey,

I have attached netconf log along. Pleas find in :

[ans_netconf.log](https://github.com/Juniper/ansible-junos-stdlib/files/1370792/ans_netconf.log)


>>> from jnpr.junos.version import VERSION
>>> print VERSION
2.1.7

The Juniper.junos Ansible role. Updated from galaxy:
- Juniper.junos (1.4.2) was installed successfully


Set gather_facts to 'no' and corrected image version:
   OS_version: 17.4-20170817_dev_common
   OS_package: junos-install-x86-64-17.4-20170817_dev_common.1.tgz
   log_dir: /var/log/ansible

show regress@mam1r> show version
Hostname: mam1r
Model: mx480
Junos: 17.4-20170913_dev_common.1
Pending: 17.4-20170817_dev_common.1 >> Although reboot was 'yes', may be since install failed due to 'no route to host' , reboot failed.

Playbook Output:
(ANS_virtualenv) root@nms5-grpc-server1:/home/regress/mamathac/ANSIBLE/pb# ansible-playbook all.pb

PLAY [Junos Core Modules] ********************************************************************************************************************************************************************************

TASK [Install Junos OS package] **************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: Could not connect to re1 : No route to host)
fatal: [mam1r]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_6AVkGB/ansible_module_junos_install_os.py\", line 307, in <module>\n    main()\n  File \"/tmp/ansible_6AVkGB/ansible_module_junos_install_os.py\", line 292, in main\n    results = junos_install_os(module, dev)\n  File \"/tmp/ansible_6AVkGB/ansible_module_junos_install_os.py\", line 221, in junos_install_os\n    ok = sw.install(package, **sw_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 718, in install\n    **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 176, in pkgadd\n    rsp = self.rpc.request_package_add(**args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py\", line 336, in _exec_rpc\n    return self._junos.execute(rpc, **dec_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 76, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 23, in wrapper\n    result = function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py\", line 722, in execute\n    errs=ex)\njnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: Could not connect to re1 : No route to host)\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/regress/mamathac/ANSIBLE/pb/all.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************
mam1r                      : ok=0    changed=0    unreachable=0    failed=1

DEVICE Info(2RE is false):

(ANS_virtualenv) root@nms5-grpc-server1:/home/regress/mamathac/ANSIBLE/pb# python device_info.py mam1r
Device Username: regress
Device Password:
Version: 2.1.7, Date: 2017-Sep-30
Connecting to mam1r...
Facts for mam1r:
{'2RE': False,
 'HOME': '/var/home/regress',
 'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'master',
         'model': 'RE-VMX',
         'status': 'OK',
         'up_time': '23 hours, 6 minutes, 58 seconds'},
 'RE1': None,
 'RE_hw_mi': False,
 'current_re': ['re0', 'master', 'node', 'fwdd', 'member', 'pfem'],
 'domain': 'englab.juniper.net',
 'fqdn': 'mam1r.englab.juniper.net',
 'hostname': 'mam1r',
 'hostname_info': {'re0': 'mam1r'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(17, 4), type=I, minor=20170913_dev_common, build=1),
                        'text': '17.4-20170913_dev_common.1'}},
 'master': 'RE0',
 'model': 'MX480',
 'model_info': {'re0': 'MX480'},
 'personality': 'MX',
 're_info': {'default': {'0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                               'mastership_state': 'master',
                               'model': 'RE-VMX',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                                     'mastership_state': 'master',
                                     'model': 'RE-VMX',
                                     'status': 'OK'}}},
 're_master': {'default': '0'},
 'serialnumber': 'VMXa68b',
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'BRIDGE_DOMAIN',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '17.4-20170913_dev_common.1',
 'version_RE0': '17.4-20170913_dev_common.1',
 'version_RE1': None,
 'version_info': junos.version_info(major=(17, 4), type=I, minor=20170913_dev_common, build=1),
 'virtual': True}
Mastership state: Master
RE Name: re0

**Comment by stacywsmith** [comment]
@mamathac Can you please retest this with the latest development version of the Juniper.junos modules?

**Comment by mamathac** [comment]
@stacywsmith I have uninstalled and reinstalled latest Juniper.junos module on Ansible 2.4.0.0. I still see the same issue:

root@server:/home/regress/mamathac/ANSIBLE/pb# ansible-playbook all.pb --tags ans_install_os_module

PLAY [Junos Core Modules] ************************************************************************************************************************************************************************

TASK [Install Junos OS package] ******************************************************************************************************************************************************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: Could not connect to re1 : No route to host)
fatal: [vr2r]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__KxIyO/ansible_module_junos_install_os.py\", line 317, in <module>\n    main()\n  File \"/tmp/ansible__KxIyO/ansible_module_junos_install_os.py\", line 302, in main\n    results = junos_install_os(module, dev)\n  File \"/tmp/ansible__KxIyO/ansible_module_junos_install_os.py\", line 230, in junos_install_os\n    ok = sw.install(package, **sw_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 718, in install\n    **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py\", line 176, in pkgadd\n    rsp = self.rpc.request_package_add(**args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py\", line 336, in _exec_rpc\n    return self._junos.execute(rpc, **dec_args)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 76, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py\", line 23, in wrapper\n    result = function(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py\", line 722, in execute\n    errs=ex)\njnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: Could not connect to re1 : No route to host)\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/regress/mamathac/ANSIBLE/pb/all.retry

PLAY RECAP ***************************************************************************************************************************************************************************************
vr2r                       : ok=0    changed=0    unreachable=0    failed=1

regress@router> show version
Hostname: vr2r
Model: mx480
Junos: 17.4-20170913_dev_common.1
Pending: 17.4-20170817_dev_common.1

Pending on re0.. Still looking for re1 and fails.

root@server:/home/regress/mamathac/ANSIBLE/pb# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
  
  
  Remove old Juniper.Junos and install latest:
  
  root@server:/home/regress/mamathac/ANSIBLE/pb# sudo ansible-galaxy remove Juniper.junos
- successfully removed Juniper.junos
root@server:/home/regress/mamathac/ANSIBLE/pb# sudo ansible-galaxy install git+https://github.com/Juniper/ansible-junos-stdlib.git,,Juniper.junos

**Comment by stacywsmith** [comment]
@mamathac Can you reproduce this issue and provide the setup?

**Comment by mamathac** [comment]
Seems like resolved in latest Juniper Junos role with Legacy Module name.(junos_install_os)

ansible-playbook Juniper_Legacy_Modules.pb.yaml -t ans_install_os_module
[WARNING]: log file at /root/.ansible/log/ansible.log is not writeable and we cannot create it, aborting

 [WARNING]: While constructing a mapping from /etc/ansible/ANS_virtualenv/pb/Juniper_Legacy_Modules.pb.yaml, line 2, column
3, found a duplicate dict key (vars). Using last defined value only.


PLAY [Testing Juniper Junos Core Modules] ***********************************************************************************

TASK [Install Junos OS package] *********************************************************************************************
changed: [mam2r]

RUNNING HANDLER [wait_reboot] ***********************************************************************************************
ok: [mam2r]

PLAY RECAP ******************************************************************************************************************
mam2r                      : ok=2    changed=1    unreachable=0    failed=0

Okay to close the Issue.

**Comment by stacywsmith** [comment]
Not reproducible with latest module code.
