### ISSUE TITLE
Junos_Install_OS : Installation skips version check on the backup RE

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#273]
Scanario:
Incase backup RE OS version is not same as the one on Master, Junos_install_os skips version check on back up RE , if version matches on Master RE, installation is skipped.
This may happen if image upgrade fails on backup RE.

regress@vr3r> show version invoke-on all-routing-engines | match Junos:
Junos: 17.4-20170913_dev_common.1
Junos: 17.4-20170817_dev_common.1

Since there is no knob explicit to install_os on RE0 or RE1 explicitly, loading image again on both REs.

regress@vr3r> show version
Hostname: vr3r
Model: mx480 >>> This is a Virtual Machine ..
Junos: 17.4-20170913_dev_common.1
JUNOS OS Kernel 64-bit  [20170908.220559_fbsd-builder_stable_11]
JUNOS OS libs [20170908.220559_fbsd-builder_stable_11]

SERVER INFO:

(ANS_virtualenv) root@nms5-grpc-server1:/tmp# ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
(ANS_virtualenv) root@nms5-grpc-server1:/tmp#

PYEZ Version : Version: 2.1.7

The Juniper.junos Ansible role. Updated from galaxy:

Juniper.junos (1.4.2) was installed successfully

HOST(Router) INFO:

**(ANS_virtualenv) root@nms5-grpc-server1:/home/regress/mamathac/ANSIBLE# python pb/device_info.py vr3r
Device Username: root
Device Password:
Version: 2.1.7, Date: 2017-Sep-30
Connecting to vr3r...
Facts for vr3r:
{'2RE': True,
 'HOME': '/root',
 'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'master',
         'model': 'RE-VMX',
         'status': 'OK',
         'up_time': '44 minutes, 13 seconds'},
 'RE1': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'backup',
         'model': 'RE-VMX',
         'status': 'OK',
         'up_time': '15 minutes, 35 seconds'},
 'RE_hw_mi': False,
 'current_re': ['re0', 'master', 'node', 'fwdd', 'member', 'pfem'],
 'domain': 'englab.juniper.net',
 'fqdn': 'vr3r.englab.juniper.net',
 'hostname': 'vr3r',
 'hostname_info': {'re0': 'vr3r', 're1': 'vr3r1'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(17, 4), type=I, minor=20170913_dev_common, build=1),
                        'text': '17.4-20170913_dev_common.1'},
                're1': {'object': junos.version_info(major=(17, 4), type=I, minor=20170817_dev_common, build=1),
                        'text': '17.4-20170817_dev_common.1'}},
 'master': 'RE0',
 'model': 'MX480',
 'model_info': {'re0': 'MX480', 're1': 'MX480'},
 'personality': 'MX',
 're_info': {'default': {'0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                               'mastership_state': 'master',
                               'model': 'RE-VMX',
                               'status': 'OK'},
                         '1': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                               'mastership_state': 'backup',
                               'model': 'RE-VMX',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                                     'mastership_state': 'master',
                                     'model': 'RE-VMX',
                                     'status': 'OK'}}},
 're_master': {'default': '0'},
 'serialnumber': 'VMXdd97',
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'BRIDGE_DOMAIN',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '17.4-20170913_dev_common.1',
 'version_RE0': '17.4-20170913_dev_common.1',
 'version_RE1': '17.4-20170817_dev_common.1',
 'version_info': junos.version_info(major=(17, 4), type=I, minor=20170913_dev_common, build=1),
 'virtual': True}
Mastership state: Master
RE Name: re0**

Playbook :

---
- name: Junos Core Modules
  hosts: [SINGLE]
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
   - name: Install Junos OS package
     junos_install_os:
        host={{ inventory_hostname }}
        user=root
        reboot=yes
        no_copy=no
        port=830
        version={{ OS_version }}
        package={{ pkg_dir }}/{{ OS_package }}
        logfile={{ log_dir }}/software.log
     register: sw
     notify:
     - wait_reboot
     tags:
        - ans_install_os_module
        
  vars:
   wait_time: 3600
   pkg_dir: /tmp
   OS_version: 17.4-20170913_dev_common.1 >>> This info matches that of RE0 but RE1 has a different OS<<<<
   OS_package: junos-install-x86-64-17.4-20170913_dev_common.1.tgz
   log_dir: /var/log/ansible

  handlers:
    - name: wait_reboot
      wait_for: host={{ inventory_hostname }} port=830 timeout={{ wait_time }}
      when: not sw.check_mode

Result:

(ANS_virtualenv) root@nms5-grpc-server1:/home/regress/mamathac/ANSIBLE/pb# ansible-playbook all.pb --tags ans_install_os_module

PLAY [Junos Core Modules] ********************************************************************************************************************************************************************************

TASK [Install Junos OS package] **************************************************************************************************************************************************************************
ok: [vr3r]

PLAY RECAP ***********************************************************************************************************************************************************************************************
vr3r                       : ok=1    changed=0    unreachable=0    failed=0

(ANS_virtualenv) root@nms5-grpc-server1:/home/regress/mamathac/ANSIBLE/pb#

Install OS skipped. 
Did not check on backup RE.

**Comment by stacywsmith** [comment]
@mamathac Thanks for the bug report. Until a proper fix is applied, you can work around this issue by running the playbook directly against the IP address of RE1 rather than only having the IP address of RE0 in your inventory file.

**Comment by stacywsmith** [comment]
@mamathac This should not be fixed using the new `juniper_junos_software` module. Please verify.

**Comment by mamathac** [comment]
regress@homer> show version invoke-on all-routing-engines | match Junos:
Junos: 17.4-20171123.0
Junos: 17.4-20171120.0

On Backup, its an older version.

Playbook checks for:
   pkg_dir: .
   OS_version: 17.4-20171123.0
   OS_package: junos-install-mx-x86-64-17.4-20171123.0.tgz

PLAY [Testing Juniper Junos Core Modules] *******************************************************************************

TASK [Install Junos OS package] *****************************************************************************************

changed: [hostname]

RUNNING HANDLER [wait_reboot] *******************************************************************************************
ok: [hostname]

PLAY RECAP **************************************************************************************************************
hostname                      : ok=2    changed=1    unreachable=0    failed=0


regress@homer1> show version invoke-on all-routing-engines | match Junos:
Junos: 17.4-20171123.0
Junos: 17.4-20171123.0

**Comment by mamathac** [comment]
Works fine with new Juniper_junos_software module.
