### ISSUE TITLE
Junos_shutdown : Graceful exit for Playbook needed when the device reboots.

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#274]
Scenario:
1. After a successful Junos_shutdown module execution, (Reboot=Yes), playbook exits abruptly with RPC Error "\nerror: System shutdown time has arrived"
Incase the tasks are multiple, the latter ones do not run since the playbook has already exited.
2. After an image upgrade using junos_install_os, reboot set to 'yes', although installation is successful, playbook exits with same RPC Error.

(ANS_virtualenv) root@server:/home/regress/mamathac/ANSIBLE/pb# ansible-playbook all.pb --tags ans_reboot_rtr,ans_netconf_test1

PLAY [Junos Core Modules] ************************************************************************************************************************************************************************

TASK [Checking NETCONF connectivity] *************************************************************************************************************************************************************
ok: [vr2r]

TASK [Junos Shutdown] ****************************************************************************************************************************************************************************
fatal: [vr2r]: FAILED! => {"changed": false, "failed": true, "msg": "error during device reboot or shutdown vr2r: RpcError(severity: error, bad_element: None, message: warning: Other routing-engine not present\nerror: \nerror: System shutdown time has arrived)"}
	to retry, use: --limit @/home/regress/mamathac/ANSIBLE/pb/all.retry

PLAY RECAP ***************************************************************************************************************************************************************************************
vr2r                       : ok=1    changed=0    unreachable=0    failed=1

In above example, --tags ans_reboot_rtr,ans_netconf_test1 (two tags are executed), since the first one exits, second tag is not executed.

Device details:
JNPR JUNOS version:
Version: 2.1.7
ansible 2.4.0.0

Playbook:
---
- name: Junos Core Modules
  hosts: [SINGLE]
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
   - name: Checking NETCONF connectivity
     wait_for: host={{ inventory_hostname }} port=830 timeout=5
     tags:
        - ans_netconf_test1

   - name: Junos Shutdown
     junos_shutdown:
        host={{ inventory_hostname }}
        shutdown="shutdown"
        reboot=yes
        user=user
        passwd=Password

     tags:
        - ans_reboot_rtr

**Comment by stacywsmith** [comment]
@mamathac This is a Junos bug with an unreleased version of Junos. Closing this issue.
