### ISSUE TITLE
junos_install_os -- RPC Timeout on Reboot

### ISSUE THREAD

**Issue by zgould** [Juniper/ansible-junos-stdlib#275]
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_9c4pCT/ansible_module_junos_install_os.py", line 307, in <module>
    main()
  File "/tmp/ansible_9c4pCT/ansible_module_junos_install_os.py", line 292, in main
    results = junos_install_os(module, dev)
  File "/tmp/ansible_9c4pCT/ansible_module_junos_install_os.py", line 235, in junos_install_os
    rsp = sw.reboot()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 933, in reboot
    raise err
jnpr.junos.exception.RpcTimeoutError: RpcTimeoutError(host: slc1-int-sw-02, cmd: request-reboot, timeout: 30)
```

How do I change the RPC timeout to greater than 30 seconds? Aside from this error, the device still reboots & upgrades appropriately.

But when we get the timeout error, it stops all further tasks in the playbook from executing.

**Comment by stacywsmith** [comment]
@zgould Unfortunately, I think you are hitting a Junos bug. In some releases of Junos the reply to the `<request-reboot>` RPC is incomplete. The router begins rebooting before it emits the closing `</rpc-reply>` tag. This is interpreted as an incomplete RPC reply, and we continue to wait until the rest of the RPC reply is received or the RPC timeout value.

In this case, the router is already rebooting. The closing `</rpc-reply>` tag is never sent. Increasing the RPC timeout would only mean that it would take longer to produce the same error.

Note: Juniper is actively pursuing a fix to this Junos bug, but that doesn't address the significant installed base of devices effected by this issue.

To address those devices, I suggest the following workaround:
1) Set `reboot: no` in your `junos_install_os` task.
2) Add a separate `junos_shutdown` task with `reboot: yes` to perform the reboot.
3) Use Ansible's `ignore_errors` or `failed_when` directives to ignore any `RPCTimeoutError` produced by the `junos_shutdown` task.

Any time you perform a reboot in your playbook, you also probably want follow-on tasks which wait for some period of time to verify the device is again reachable and truly did reboot (probably check `show system uptime` output.)

**Comment by stacywsmith** [comment]
The new `juniper_junos_software` module (#296) and the new `juniper_junos_system` module (#283) attempt to workaround this Junos bug. If you still see this issue, please reopen the issue here and also work with JTAC to address the underlying Junos issue.
