### ISSUE TITLE
ignore_warning not working for "statement has no contents"

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#276]
My workflow includes to load empty blocks of configuration as explained on https://github.com/Juniper/ansible-junos-stdlib/pull/168#issuecomment-275953915
This works fine while loading and committing the configuration manually (only outputs a warning) but fails while using ansible-junos-stdlib, even with the statement: `ignore_warning: true` in 1.4.3.
My previous workaround is detailed on https://github.com/XioNoX/ansible-junos-stdlib/commit/7a07c765d552226ccbc3e26d897f39141c977c3a

The exact logs are the following:
```
2017-10-13 09:45:51,904:CONFIG:cr1-esams:Unable to load config: ConfigLoadError(severity: error, bad_element: forwarding-options, message: warning: mgd: statement has no contents; ignored
error: syntax error
error: error recovery ignores input until this point
error: error recovery ignores input until this point
warning: mgd: statement has no contents; ignored
error: error recovery ignores input until this point
error: error recovery ignores input until this point
warning: mgd: statement has no contents; ignored)
```

**Comment by stacywsmith** [comment]
@XioNoX The device is not producing a warning, it's producing an error
```
ConfigLoadError(severity: error, bad_element: forwarding-options, message: warning: mgd: statement has no contents; ignored
error: syntax error
```

Can you provide exact details on your configuration snippet and playbook that are producing this error from the device? If you can also provide the output of "loading and committing the configuration manually (only outputs a warning) " that would also help.

There's really nothing that can be done in PyEZ/Ansible modules if the device is producing an error. We need to figure out why the device is producing an error and determine an appropriate workaround.

**Comment by XioNoX** [comment]
I got confused by the error message, there was two "issues" in one.

for the record, loading for example the following on an MX:
```
security {
    replace: zones {
    }
}
```
Will throw the error as "zones" is not an acceptable statement on a MX. And will then throw a warning as well for empty "security" statement.
