### ISSUE TITLE
Junos_rollback : Confirm flag is not functional. Shows commit was not confirmed

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#277]
Case:
Here I am running a playbook with rollback to previous config with commit set to 1. 
Diff shows that there is change in config, but it doesnt confirm.
On router I see "# commit confirmed will be rolled back in less than 1 minute" and soon the commit gets removed.

Playbook:
**#With a Valid rollback number.**
   - name: "junos_rollback - confirm"
     junos_rollback:
       host: "{{ inventory_hostname }}"
       user: user
       passwd: Password 
       rollback: "1"
       confirm: "1"
       diffs_file: "./rollback-{{ inventory_hostname }}.diff"
       comment: "testing junos_rollback confirm 1 with Valid Inputs"
     register: response
     tags: ans_rollback1

Diff file:
user@server:~path# cat rollback-vr3r.diff

[edit system]
+  host-name temporary-hostname;

**On the router:**

commit confirmed will be rolled back in less than 1 minute
[edit]
root@temporary-hostname#

 commit confirmed will be rolled back in less than 1 minute
[edit]
root@temporary-hostname#

commit confirmed will be rolled back in less than 1 minute
[edit]
root@temporary-hostname#

commit confirmed will be rolled back in less than 1 minute
[edit]

Broadcast Message from root@temporary-hostname
        (no tty) at 17:00 IST...

Commit was not confirmed; automatic rollback complete.

[edit]

Broadcast Message from root@temporary-hostname
        (no tty) at 17:04 IST...

Commit was not confirmed; automatic rollback complete.

Broadcast Message from root@temporary-hostname
        (no tty) at 17:06 IST...

Commit was not confirmed; automatic rollback complete.

Broadcast Message from root@vr3r
        (no tty) at 17:19 IST...

Commit was not confirmed; automatic rollback complete.

**<<<< Rollback was not confirmed.>>>>>**

Details:
Server : 
root@server:~path# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

PYEZ Version:
Version: 2.1.7
Juniper.Junos role version:

root@server:~path# cat /root/.ansible/roles/Juniper.junos/version.py
VERSION = "2.0.0dev1"
DATE = "2017-Oct-9"

Host:
root@vr3r> show version invoke-on all-routing-engines | match Junos:
Junos: 17.4-20171016.0
Junos: 17.4-20171016.0
Version: 2.1.7, Date: 2017-Sep-30
Connecting to vr3r...
Facts for vr3r:
{'2RE': True,
 'HOME': '/var/home/regress',
 'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'master',
         'model': 'RE-VMX',
         'status': 'OK',
         'up_time': '7 hours, 45 seconds'},
 'RE1': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'backup',
         'model': 'RE-VMX',
         'status': 'OK',
         'up_time': '7 hours, 37 seconds'},
 'RE_hw_mi': False,
 'current_re': ['re0', 'master', 'node', 'fwdd', 'member', 'pfem'],
 'domain': 'englab.juniper.net',
 'fqdn': 'vr3r.englab.juniper.net',
 'hostname': 'vr3r',
 'hostname_info': {'re0': 'vr3r', 're1': 'vr3r1'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(17, 4), type=I, minor=20171016, build=0),
                        'text': '17.4-20171016.0'},
                're1': {'object': junos.version_info(major=(17, 4), type=I, minor=20171016, build=0),
                        'text': '17.4-20171016.0'}},
 'master': 'RE0',
 'model': 'MX480',
 'model_info': {'re0': 'MX480', 're1': 'MX480'},
 'personality': 'MX',
 're_info': {'default': {'0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                               'mastership_state': 'master',
                               'model': 'RE-VMX',
                               'status': 'OK'},
                         '1': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                               'mastership_state': 'backup',
                               'model': 'RE-VMX',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
                                     'mastership_state': 'master',
                                     'model': 'RE-VMX',
                                     'status': 'OK'}}},
 're_master': {'default': '0'},
 'serialnumber': 'VMXdd97',
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'BRIDGE_DOMAIN',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '17.4-20171016.0',
 'version_RE0': '17.4-20171016.0',
 'version_RE1': '17.4-20171016.0',
 'version_info': junos.version_info(major=(17, 4), type=I, minor=20171016, build=0),
 'virtual': True}
Mastership state: Master
RE Name: re0

**Comment by stacywsmith** [comment]
@mamathac This is working as designed. I do agree the documentation could be improved.

The `confirm: "1"` is telling the module to perform the equivalent of the `commit confirmed 1` configuration-mode CLI command. In other words, you're playbook is specifically requesting that your configuration (the rollback) be rolled back if it isn't confirmed within 1 minute.

You would normally use the `confirm` option with this module (or with the `junos_install_config` module) if you are concerned that you are installing a configuration that might be "incorrect".

You would then follow the `junos_rollback` or `junos_install_config` task with one or more tasks which check to see if the network is operating as expected.

If so, you would then add a third task which calls the `junos_commit` module. This task would perform the equivalent of the `commit` configuration-mode CLI command. This would confirm the previous `commit confirmed 1` command and prevent the configuration from automatically rolling back.

I will leave this issue open to track an improvement to the documentation.

**Comment by stacywsmith** [comment]
The documentation has been improved to clarify this functionality.
