### ISSUE TITLE
Rollback rescue

### ISSUE THREAD

**Issue by ric79** [Juniper/ansible-junos-stdlib#284]
Hello,
is it possible to use this lib to run "rollback rescue"? I tried with junos_config and junos_cli without luck

Thanks!
RR

**Comment by stacywsmith** [comment]
@ric79 I don't believe it's currently possible, but we will look into adding it.

**Comment by stacywsmith** [comment]
This is now implemented via the new `juniper_junos_config` module introduced via #290.

Example playbook:
```
    - name: Rollback to the rescue config.
      juniper_junos_config:
        rollback: 'rescue'
      register: response
    - name: Print the complete response.
      debug:
        var: response
```

**Comment by ric79** [comment]
Thanks!
