### ISSUE TITLE
Module junos_rpc throwing "Unsupported parameters for (junos_rpc) module" error

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#288]
Host info:

ansible --version :  ansible 2.4.0.0
Juniper Junos role version:
VERSION = "2.0.0.dev4"
DATE = "2017-Oct-21"

**Device information**
Version: 2.1.7, Date: 2017-Sep-30
Connecting to bm-b...
Facts for bm-b:
{'2RE': True,
 'HOME': '/var/home/regress',
 'RE0': {'last_reboot_reason': '0x4000:VJUNOS reboot',
         'mastership_state': 'master',
         'model': 'RE-S-2X00x6',
         'status': 'OK',
         'up_time': '3 hours, 39 minutes, 41 seconds'},
 'RE1': {'last_reboot_reason': '0x1:power cycle/failure',
         'mastership_state': 'backup',
         'model': 'RE-S-2X00x6',
         'status': 'OK',
         'up_time': '13 hours, 6 minutes, 17 seconds'},
 'RE_hw_mi': False,
 'current_re': ['re0', 'master', 'node', 'fwdd', 'member', 'pfem'],
 'domain': 'englab.juniper.net',
 'fqdn': 'bm-b.englab.juniper.net',
 'hostname': 'bm-b',
 'hostname_info': {'re0': 'bm-b'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(18, 1), type=I, minor=20171026_dev_common, build=0),
                        'text': '18.1-20171026_dev_common.0'}},
 'master': 'RE0',
 'model': 'MX480',
 'model_info': {'re0': 'MX480'},
 'personality': 'MX',
 're_info': {'default': {'0': {'last_reboot_reason': '0x4000:VJUNOS reboot',
                               'mastership_state': 'master',
                               'model': 'RE-S-2X00x6',
                               'status': 'OK'},
                         '1': {'last_reboot_reason': '0x1:power cycle/failure',
                               'mastership_state': 'backup',
                               'model': 'RE-S-2X00x6',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': '0x4000:VJUNOS reboot',
                                     'mastership_state': 'master',
                                     'model': 'RE-S-2X00x6',
                                     'status': 'OK'}}},
 're_master': {'default': '0'},
 'serialnumber': 'JN12302A0AFB',
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'BRIDGE_DOMAIN',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '18.1-20171026_dev_common.0',
 'version_RE0': '18.1-20171026_dev_common.0',
 'version_RE1': None,
 'version_info': junos.version_info(major=(18, 1), type=I, minor=20171026_dev_common, build=0),
 'virtual': False}
Mastership state: Master
RE Name: re0

**Playbook**:
   - name: "Simple RPC"
     junos_rpc:
       host: "{{ inventory_hostname }}"
       user: username
       passwd: Password
       rpc: "get-software-information"
       dest: "./{{ inventory_hostname }}-get-software-information.implicit"
     register: response
     tags: ans_rpc_simple

**Result**:
PLAY [Testing Juniper Junos Core Modules] ***********************************************************************************************************

TASK [TEST 2 - junos_rpc - basic] *******************************************************************************************************************
fatal: [bm-b]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (junos_rpc) module: _module_name,_module_utils_path,dest,passwd,user Supported parameters include: args,host,output,password,port,provider,rpc,ssh_keyfile,timeout,transport,username"}
	to retry, use: --limit @/etc/ansible/ANS_virtualenv/pb/all.retry

PLAY RECAP ******************************************************************************************************************************************
bm-b                       : ok=0    changed=0    unreachable=0    failed=1

**Comment by stacywsmith** [comment]
This is a conflict with the core module which is also named junos_rpc. On Ansible 2.3 and 2.4, there's no way to invoke the Galaxy module because of this naming conflict.

That's part of why we're renaming the modules to avoid this conflict. Please test using the new name for this module: `juniper_junos_rpc`.
