### ISSUE TITLE
Shutdown Module  : VMs Shutdown and do not come up despite having "reboot : yes" 

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#293]
Tried on Several VMs and found the same issue.
Probably VMs do not reboot and remain Shut down.  Even serial connection fails.
Happens with only VM. Did not see this on Physical device.

Playbook returned "changed =1 " and device reboot message was seen.

root@vr2r>

root@vr2r>
*** FINAL System shutdown message from regress@vr2r ***

System going down IMMEDIATELY

Stopping cron.
.
Nov  2 14:55:23 jlaunchd: disk-monitoring (PID 6939) terminate signal 15 sent
Nov  2 14:55:23 jlaunchd: pki-service (PID 7027) terminate signal 15 sent
Nov  2 14:55:23 jlaunchd: dynamic-flow-capture (PID 7089) terminate signal 15 sent
Nov  2 14:55:23 jlaunchd: stats-agent (PID 7114) terminate signal 15 sent
Waiting (max 60 seconds) for system process `vnlru' to stop... done
Waiting (max 60 seconds) for system process `bufdaemon' to stop... done
Waiting (max 60 seconds) for system process `syncer' to stop...
Syncing disks, vnodes remaining... 0 0 0 0 done
All buffers synced.
Uptime: 1h0m46s
Khelp module "jsocket" can't unload until its refcount drops from 15 to 0.
acpi0: Powering system off
Connection closed by foreign host.

.......
[user@server ~]$ vmm serial -t vr2r
No local connections found to <squid server > <port>
Starting telnet connection to Serial console of (vr2r) using  <squid server > <port>
Trying <address>...
telnet: connect to address <address>: Connection refused
------
Playbook:

   - name: Junos Shutdown
     junos_shutdown:
        host={{ inventory_hostname }}

        shutdown='shutdown'
        reboot=yes
        user=user
        passwd=pwd

changed: [<IP>]
	to retry, use: --limit @/root/.ansible/retry/all.retry

PLAY RECAP ********************************************************************************************************************************************************************
<IP>            : ok=1    changed=1    unreachable=0    failed=0

##############
server and device info;
Juniper.junos :

VERSION = "2.0.0.dev6"
DATE = "2017-Nov-01"

ansible 2.4.0.0

**Comment by stacywsmith** [comment]
@mamathac Good catch! I'm working on a fix.
