### ISSUE TITLE
Netconf to set

### ISSUE THREAD

**Issue by ric79** [Juniper/ansible-junos-stdlib#306]
Hello,
my automation is producing the QFX configuration in netconf format. Is there an easy way to translate in set commands (without pushing the conf to node)?

**Comment by stacywsmith** [comment]
Can you clarify what you mean by "netconf format"? Junos only supports configuration in text (curly brace), set, xml, and json formats.

**Comment by ric79** [comment]
In ansible I'm using a jinja template. I have a string with the junos config. There are +1000rows and the format is with curly brace. Now people is asking me to show the config packet with 'set' commands. I do not want to change my jinja template... So I'm asking you if there is a way to translate from 'curly brace' to 'set' (without pushing the config  into the node)
Rr

**Comment by stacywsmith** [comment]
The Ansible modules provided in this role do not provide this ability. I'm also not currently aware of any other tool that would provide this capability.

My suggestion would be to try and demonstrate the benefits of configuration hierarchy to the people requesting the configuration in 'set' format.

The alternative is to retrieve the candidate configuration in 'set' format, load the 'text' format configuration changes into the candidate configuration (but do not commit), retrieve the now modified candidate configuration in 'set' format, and perform a "diff" between the pre and post change candidate configurations. Again, the Ansible modules provided in this role do not currently provide this capability.

**Comment by ric79** [comment]
thanks
