### ISSUE TITLE
Sample Playbook for Junos Lengthy Operational Commands (ie. RSI)

### ISSUE THREAD

**Issue by jhosee** [Juniper/ansible-junos-stdlib#307]
Hello, 

I would like to know if there exists a sample playbook or a workaround to be able to execute lengthy operational commands such as "request support information" that contains a combination of other operational commands.

The problem I am having is that the playbook executes and runs the command, but terminates before all the "sub-commands" can finish running.  I have tried this with junos_command and junos_cli modules and have received the same results for each.  

Thank you for any assistance or guidance!

Jon

**Comment by stacywsmith** [comment]
Neither the core `junos_command` module nor the released version of the `junos_cli` module from this role have the ability to set the command/RPC timeout value. 

However, the newly updated modules in this role (which are not yet released) do support setting a command/RPC timeout value with the `timeout` option. (The modules in this role have also been renamed, so the `junos_cli` module is now `juniper_junos_command`.

Here is an example playbook which will both print the RSI output and save it to a file named `./rsi_output/r0_request_support_information.text`:
```
---
- name: 'Run request support information CLI command.'
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: 'Run request support information CLI command.'
      juniper_junos_command:
        timeout: 300
        command: 'request support information'
        dest_dir: './rsi_output/'
      register: response
    - name: 'Print result'
      debug:
        var: response.stdout_lines
```

If you are willing to try these unreleased modules, you can install them with:
```
sudo ansible-galaxy remove Juniper.junos
sudo ansible-galaxy install git+https://github.com/Juniper/ansible-junos-stdlib.git,,Juniper.junos
```

**Comment by stacywsmith** [comment]
Please reopen this issue if you have further questions or problems.

**Comment by jhosee** [comment]
Thank you, Stacy!  I will definitely try out the new modules.  Appreciate the info once again and I love reading your books btw!
