### ISSUE TITLE
juniper_junos_config - Unicode error: Character 15997-15998

### ISSUE THREAD

**Issue by eregimbald** [Juniper/ansible-junos-stdlib#316]
Python: 2.7.12
Ansible: 2.4.2.0
junos-eznc: 2.1.7
junos-netconify: 1.0.2
juniper_junos_config: The one from Jan 10 2018

I'm attempting to pull a configuration from a device and I'm receiving this error:

The error was: UnicodeEncodeError: 'ascii' codec can't encode characters in position 15997-15998: ordinal not in range(128).

Playbook:

  
    ---
    - name: Search-config
      gather_facts: no
      connection: local
      vars:
        display_skipped_hosts: False

      vars_prompt:
        - name: "target"
          prompt: "Enter host or inventory group"
          private: no
        - name: "get"
          prompt: "Would you like to get the device configs? (y/n)"
          default: "y"
          private: no
        - name: "string"
          prompt: "What are you looking for? (config line)"
          private: no

      hosts: "{{target}}"

      tasks:
          - include_role:
              name: Juniper.junos
          - include_role:
              name: junos/junos-getconfig
          
          - name: Finding the line
            command: grep {{ string }} {{ playbook_dir }}/vars/search-config/{{ inventory_hostname }}/{{ 
            inventory_hostname }}.config
            register: results
          
          - name: Printing results
            debug: msg={{results.stdout_lines}}

Role:

    - name: Junos Get config
      juniper_junos_config:
        host: '{{ inventory_hostname }}'
        user: '{{ user }}'
        logfile: logs/{{ inventory_hostname }}/audit-config.log
        #return_output:
        retrieve: committed
        dest_dir: vars/search-config/{{ inventory_hostname }}/
        format: text
     when: get == "y"

**Comment by stacywsmith** [comment]
What version of Python is being used?

Can you please run the playbook with `-vvv` and provide the full output?

**Comment by stacywsmith** [comment]
>The error was: UnicodeEncodeError: 'ascii' codec can't encode characters in position 15997-15998: ordinal not in range(128).

On the device, the configuration uses UTF-8 encoding. It appears your configuration may contain a non-ASCII character. That's perfectly valid in your configuration, but there appears to be some code somewhere within Ansible and/or the juniper_junos_config module which is incorrectly assuming the configuration is ASCII encoded.

The full `-vvv` output of the playbook execution should help determine exactly where the UnicodeEncodeError is occurring.

**Comment by eregimbald** [comment]
@stacywsmith 

I think you're right, I did a regex for [\x80-\xFF] in the device's configuration and it caught some of the whitespace between words in object descriptions.

Here is the -vvv

https://hastebin.com/ruhuxajuba.md

**Comment by stacywsmith** [comment]
Thanks for the info. That was exactly what I needed to reproduce and fix the issue.
