### ISSUE TITLE
2.0 release doesn't work in Ansible AWX/Tower

### ISSUE THREAD

**Issue by jalphonso** [Juniper/ansible-junos-stdlib#321]
[DEPRECATION WARNING]: junos_install_config is kept for backwards compatibility
 but usage is discouraged. The module documentation details page may explain 
more about this rationale.. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
TASK [snmp : Deploy Junos config to device] ************************************
12:05:51
fatal: [192.168.254.232]: FAILED! => {"changed": false, "msg": "jxmlease >= 1.0.1 is required for this module. However, jxmlease does not appear to be currently installed. See http://jxmlease.readthedocs.io/en/stable/install.html for details on installing jxmlease."}

**Comment by stacywsmith** [comment]
Based on email conversation, I believe your issue has been addressed. If not, please re-open this issue.

**Comment by jalphonso** [comment]
Thank you Stacy. Here are the steps I performed to remedy the particular issue as well as install other required dependencies for this role in my env. Also per 7.1 https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html I activated the Ansible venv before installing the Python dependencies
docker exec -it awx_task /bin/bash 
. /var/lib/awx/venv/ansible/bin/activate
pip install junos-eznc jsnapy jxmlease lxml pyyaml

**Comment by stacywsmith** [comment]
@jalphonso Thanks for documenting your fix.
