### ISSUE TITLE
No module named plugins.action.normal using 2.0.0

### ISSUE THREAD

**Issue by hl1234** [Juniper/ansible-junos-stdlib#322]
I have found myself in a confusing situation since I just started trying to use Juniiper.junos this week with most of my progress yesterday.  I was also going through rebuilding my python environment with pyenv.  So I got back to a working set of playbooks and decided to try the 2.0.0 version.  That is when I encountered the error "No module named plugins.action.normal". The only change I made between work and not working was to remove 1.4.3 and install 2.0.0.

This may be an obvious newbie problem or something real so I will defer to you wrt prioritization. In the meantime I will go back to 1.4.3 and check back later.

I use -p with galaxy to install Juniper.junos in the local roles/ directory where I am working.

More follows

---------
$ ansible --version
ansible 2.4.2.0
  config file = /home/harry/Projects/network-configuration/ansible/ansible.cfg
  configured module search path = [u'/home/harry/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/harry/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansible
  executable location = /home/harry/.pyenv/versions/2.7.14/bin/ansible
  python version = 2.7.14 (default, Jan 12 2018, 10:31:32) [GCC 4.8.4]
$ python --version
Python 2.7.14

------

$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
bcrypt (3.1.4)
cffi (1.11.2)
cryptography (2.1.4)
enum34 (1.1.6)
idna (2.6)
ipaddress (1.0.19)
Jinja2 (2.10)
junos-eznc (2.1.7)
jxmlease (1.0.1)
lxml (4.1.1)
MarkupSafe (1.0)
ncclient (0.5.3)
netaddr (0.7.19)
paramiko (2.4.0)
pip (9.0.1)
pyasn1 (0.4.2)
pycparser (2.18)
PyNaCl (1.2.1)
pyserial (3.4)
PyYAML (3.12)
scp (0.10.2)
setuptools (38.4.0)
six (1.11.0)
wheel (0.30.0)

-------

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_NvO_Cq/ansible_module_junos_get_config.py", line 1164, in <module>
    main()
  File "/tmp/ansible_NvO_Cq/ansible_module_junos_get_config.py", line 784, in main
    juniper_junos_common = import_juniper_junos_common()
  File "/tmp/ansible_NvO_Cq/ansible_module_junos_get_config.py", line 777, in import_juniper_junos_common
    import juniper_junos_common
  File "/home/harry/Projects/network-configuration/ansible/roles/Juniper.junos/module_utils/juniper_junos_common.py", line 39, in <module>
    from ansible.plugins.action.normal import ActionModule as ActionNormal
ImportError: No module named plugins.action.normal

fatal: [ecp-pbb]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NvO_Cq/ansible_module_junos_get_config.py\", line 1164, in <module>\n    main()\n  File \"/tmp/ansible_NvO_Cq/ansible_module_junos_get_config.py\", line 784, in main\n    juniper_junos_common = import_juniper_junos_common()\n  File \"/tmp/ansible_NvO_Cq/ansible_module_junos_get_config.py\", line 777, in import_juniper_junos_common\n    import juniper_junos_common\n  File \"/home/harry/Projects/network-configuration/ansible/roles/Juniper.junos/module_utils/juniper_junos_common.py\", line 39, in <module>\n    from ansible.plugins.action.normal import ActionModule as ActionNormal\nImportError: No module named plugins.action.normal\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_OsmKk7/ansible_module_junos_get_config.py", line 1164, in <module>
    main()
  File "/tmp/ansible_OsmKk7/ansible_module_junos_get_config.py", line 784, in main
    juniper_junos_common = import_juniper_junos_common()
  File "/tmp/ansible_OsmKk7/ansible_module_junos_get_config.py", line 777, in import_juniper_junos_common
    import juniper_junos_common
  File "/home/harry/Projects/network-configuration/ansible/roles/Juniper.junos/module_utils/juniper_junos_common.py", line 39, in <module>
    from ansible.plugins.action.normal import ActionModule as ActionNormal
ImportError: No module named plugins.action.normal

fatal: [ecp-pba]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_OsmKk7/ansible_module_junos_get_config.py\", line 1164, in <module>\n    main()\n  File \"/tmp/ansible_OsmKk7/ansible_module_junos_get_config.py\", line 784, in main\n    juniper_junos_common = import_juniper_junos_common()\n  File \"/tmp/ansible_OsmKk7/ansible_module_junos_get_config.py\", line 777, in import_juniper_junos_common\n    import juniper_junos_common\n  File \"/home/harry/Projects/network-configuration/ansible/roles/Juniper.junos/module_utils/juniper_junos_common.py\", line 39, in <module>\n    from ansible.plugins.action.normal import ActionModule as ActionNormal\nImportError: No module named plugins.action.normal\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

**Comment by stacywsmith** [comment]
I'm pretty sure this problem is because you have Ansible installed in a virtualenv, but then when the module runs on the localhost it's not running inside the virtualenv.

There were some changes between version 1.4.3 and 2.0.0 that would explain why this works in 1.4.3, but not in 2.0.0.

I won't go into the details on why this is needed, but I believe you can get 2.0.0 working by setting the `ansible_python_interpreter` inventory variable to the path of your Python interpreter inside your virtualenv.

You might do this at the start of your playbook with something like this:
```
---
- name: Example Juniper.junos playbook
  hosts: all
  connection: local 
  gather_facts: no 
  roles:
    - Juniper.junos
  vars:
    ansible_python_interpreter: "<path to the python in your vitualenv>"
```

Please let me know if this resolves your issue.

**Comment by stacywsmith** [comment]
Please reopen this issue if my suggestion doesn't fix your problem.

**Comment by dfex** [comment]
FWIW I see this issue too without a virtualenv - hard-coding the ansible_python_interpreter var fixes this as you suggest, but I'm just setting it to the path that I'm extracting from ansible --version and/or ansible localhost -m setup:

Python 3.6.3
ansible 2.4.2.0
  config file = None
  configured module search path = ['/Users/bendale/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.6/bin/ansible
  python version = 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

ansible localhost -m setup
...
        "ansible_python": {
            "executable": "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6",
            "has_sslcontext": true,
...

**Comment by stacywsmith** [comment]
Yes, it's still required in this case. Any time the Python you are using is not in `/usr/bin/python`, you *must* explicitly set it with the `ansible_python_interpreter` setting. This has to do with Ansible's behavior.

The modules execute in a separate process on the control machine. Regardless of which Python interpreter kicked off the `ansible` or `ansible-playbook` command, the process executing the module is executed with the Python interpreter specified by the `ansible_python_interpreter` setting, or if that's not set with `/usr/bin/python`.

In the absence of a `ansible_python_interpreter` setting, older versions of Ansible would execute with the interpreter specified in the module's shebang line, but newer versions of Ansible completely ignore the shebang line.

**Comment by dfex** [comment]
That would explain it - thank you very much @stacywsmith
