### ISSUE TITLE
Improve docs around dest and dest_dir arguments

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/ansible-junos-stdlib#329]
Explain the differences between `dest` and `dest_dir` arguments. Especially when multiple commands/RPCs are specified. List pros and cons of both.

The documentation currently states that `dest` is deprecated. It should not be deprecated. There are valid use cases for both `dest` and `dest_dir`.

**Comment by chidanandpujar** [comment]
documentation takes care of both options dest and dest_dir
https://www.juniper.net/documentation/us/en/software/junos-ansible/ansible/topics/topic-map/junos-ansible-commands-rpcs-executing.html
