### ISSUE TITLE
juniper_junos_software assumes that software image on Ansible host is 'uncorrupted' when checksums mismatch

### ISSUE THREAD

**Issue by jnpr-bowen** [Juniper/ansible-junos-stdlib#344]
While it may be true that file corruption occurs more often on the Juniper device, that alone is not reason enough to assume that the Ansible host file is not the one corrupted, which is the assumption with the way the task is implemented now. Without a comparison to a 'master checksum value', if both images exist during the playbook run, a mismatch in the checksums should result in the task failing. If a master checksum is added as an attribute of the task, several outcomes are available: file present on Ansible with mismatch to checksum but file not on device, fail; file present on Ansible and device with checksum mismatch on Ansible, proceed with warning; file present on Ansible and device with checksum mismatch on device, proceed as currently implemented, copy from Ansible to device.

**Comment by stacywsmith** [comment]
The assumption is that the operator has verified the file on the Ansible host against a known good checksum value. You have to trust something as the authoritative source, and I see no difference in trusting the actual checksum of the file vs. trusting a value specified as a task attribute. Either could theoretically have been corrupted.

Because the copy is happening FROM the Ansible control machine TO the Juniper device, the checksum is being used to make sure that the file wasn't corrupted during copy. It should be the user's responsibility to ensure the source file on the Ansible control machine is trusted.

**Comment by jnpr-bowen** [comment]
That assumption that the operator has verified the file on the Ansible host may be 'acceptable', but it needs to be clearly stated as such in the documentation.
In one sense, adding an MD5 signature to the playbook does not make it 'authoritative', it just allows for a 'majority' to be formed. 
The difference, as implemented, is that the code assumes Ansible is authoritative and yet there is nothing within the code that determines that the Ansible file is not the problem. Without an additional data point, a 50/50 split does not allow for determining where the error is.
I will be coding an upgrade playbook that does the MD5 signature check of the Ansible file before proceeding with the upgrade. This is not 'efficient', but it will be reliable for me, because when there is a disagreement  the automation stop.

Look at this from the standpoint of downloading a 'very' new version of Junos from Juniper. Juniper posts the file and the MD5 checksum, then you download it and compare your MD5 sum against the posted value. When they disagree, you do not know if the download corrupted the file, the source file is corrupt, or if the MD5 sig was posted wrong. If you download again, you get a third data point. If it agrees with the posted MD5, you assume the first download was corrupted (the sig and the second download form a 'majority'). If the first and second sums match, you contact Juniper because your 'majority' says there is an error either in the source file or the posted signature.

**Comment by rahkumar651991** [comment]
Closing the issue due to inactivity.
