### ISSUE TITLE
Enumeration for dest_dir files

### ISSUE THREAD

**Issue by jhosee** [Juniper/ansible-junos-stdlib#347]
Apologies for the rudimentary question, but is there a way to enumerate output files when the dest_dir option is set?  I'm looking to trying to do this either with a numbering scheme or date/timestamps.  Thanks,

**Comment by stacywsmith** [comment]
No. You should use the `dest` option instead.

See the discussion[here](https://github.com/Juniper/ansible-junos-stdlib/issues/326#issuecomment-358448036)

Also see #329.

**Comment by jhosee** [comment]
Thank you, Stacy!
