### ISSUE TITLE
Recent commit for Python 3 broke juniper_junos_table

### ISSUE THREAD

**Issue by dgarros** [Juniper/ansible-junos-stdlib#348]
Hi there :) 

Looks like a [recent commit](https://github.com/Juniper/ansible-junos-stdlib/commit/d8392c95202a576a696d4d963f1f06d8fe7e03b2#diff-44b3e9d060adc75666a0902bbba43cd3R38) from @rsmekala regarding adding support for python 3 broke (at least) the module `juniper_junos_table` for python 2.7

Lines 341 & 362
```python
for table_key, table_fields in data.items():
```
got replaced with 
```python
for table_key, table_fields in iteritems(data):
```
I reverted this change in my local branch and it fixed it.   

Not even sure why this change was required, as far as I know, python 3 automatically return an iterator with `.items()`

**Comment by vnitinv** [comment]
fixed via https://github.com/Juniper/ansible-junos-stdlib/pull/345
