### ISSUE TITLE
junos_get_facts doesn't support check_mode

### ISSUE THREAD

**Issue by mhite** [Juniper/ansible-junos-stdlib#38]
When you have a playbook you run in check-only mode, modules that don't support check_mode are skipped. I noticed junos_get_facts doesn't support check_mode. Since this module does not change state on the remote device, I can't think of any reason why NOT to support check_mode. Or is there some detail I am missing?

It should be a simple fix to make this module check mode compatible and I'm happy to send a pull request.

**Comment by shermdog** [comment]
Fixed by 2b0f0628b0230cd9a7cc9364ef8a1c2e6a3c375c
