### ISSUE TITLE
juniper_junos_facts Support on QFX( WR Linux based hardware)

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#380]
Issue Type
------
 - Bug Report

Module Name

juniper_junos_facts

Juniper.Junos role and Python libraries version
(ANS_virtualenv) root@nms5-grpc-server1:/etc/ansible/ANS_virtualenv/pb# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

(ANS_virtualenv) root@nms5-grpc-server1:/etc/ansible/ANS_virtualenv/pb# pip freeze
asn1crypto==0.23.0
bcrypt==3.1.4
cffi==1.11.2
cryptography==2.1.3
enum34==1.1.6
idna==2.6
ipaddress==1.0.18
Jinja2==2.10
junos-eznc==2.1.9.dev0
lxml==4.1.1
MarkupSafe==1.0
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.4.0
pyasn1==0.3.7
pycparser==2.18
PyNaCl==1.2.0
pyserial==3.4
PyYAML==3.12
scp==0.10.2
six==1.11.0

OS / Environment

Model: qfx5200-32c-32q
Junos: 16.2I20180618103614_evo-builder
Junos Package: junos-linux-install-qfx-x86-64-16.2I20180618103614_evo-builder.iso
Yocto: 2.2.1
Linux Kernel: 4.8.24-WR2.2.1_standard

Summary
------
juniper_junos_facts calls the "show version invoke-on all-routing-engines" on a QFX device. 
QFX does not support this command.
juniper_junos_facts to check version and call appropriate show version command.

Steps to reproduce
------

   - name: Get Junos Facts
     juniper_junos_facts:
        host: "{{ inventory_hostname }}"
        user: user_name
        passwd: Password
        port: 830
        savedir: "."
     register: nc_response
     tags:
        - ans_get_facts1

Expected results
------
Should return the device facts

Actual results
------

Jun 21 03:50:04 [NETCONF] - [26471] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:4666366b-ea82-4c8a-91b1-552ac3608af9"><command>show version invoke-on all-routing-engines</command></nc:rpc>]]>]]>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:4666366b-ea82-4c8a-91b1-552ac3608af9">
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <rpc-error>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <error-type>protocol</error-type>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <error-tag>operation-failed</error-tag>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <error-severity>error</error-severity>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <error-message>syntax error, expecting &lt;command&gt;</error-message>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <error-info>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: <bad-element>invoke-on</bad-element>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: </error-info>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: </rpc-error>
Jun 21 03:50:04 [NETCONF] - [26471] Debug: The last token parsed by mgd [26471] was [invoke-on] and gram data current token [invoke-on]
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: </rpc-reply>
Jun 21 03:50:04 [NETCONF] - [26471] Outgoing: ]]>]]>
Jun 21 03:50:04 [NETCONF] - [26471] Incoming: <?xml ve

=================

While I am looking for a hostname field, I get all null :

    "msg": {
        "HOME": null,
        "RE0": {
            "last_reboot_reason": "ITCO Watchdog",
            "mastership_state": "Master",
            "model": "RE-QFX5200-32C",
            "status": "OK",
            "up_time": "1 day, 4 hours, 22 minutes, 31 seconds"
        },
        "RE1": null,
        "RE_hw_mi": false,
        "current_re": null,
        "domain": "englab.juniper.net",
        "fqdn": null,
        "has_2RE": false,
        "hostname": null,
        "hostname_info": null,
        "ifd_style": "SWITCH",
        "junos_info": {
            "re0": {
                "object": {
                    "build": null,
                    "major": [
                        16,
                        2
                    ],
                    "minor": "20180618103614_evo-builder",
                    "type": "I"
                },
                "text": "16.2I20180618103614_evo-builder"
            }
        },
        "master": "RE0",
        "master_state": null,
        "model": "QFX5200-32C-32Q",
        "model_info": {
            "re0": "QFX5200-32C-32Q"
        },
        "personality": "SWITCH",
        "re_info": {
            "default": {
                "0": {
                    "last_reboot_reason": "ITCO Watchdog",
                    "mastership_state": "Master",
                    "model": "RE-QFX5200-32C",
                    "status": "OK"
                },
                "default": {
                    "last_reboot_reason": "ITCO Watchdog",
                    "mastership_state": "Master",
                    "model": "RE-QFX5200-32C",
                    "status": "OK"
                }
            }

▽
        },
        "re_master": {

▽
            "default": "0"
        },
        "re_name": null,
        "serialnumber": "WH0218110306",
        "srx_cluster": null,
        "srx_cluster_id": null,
        "srx_cluster_redundancy_group": null,
        "switch_style": "NONE",
        "vc_capable": false,
        "vc_fabric": null,
        "vc_master": null,
        "vc_mode": null,
        "version": "16.2I20180618103614_evo-builder",
        "version_RE0": "16.2I20180618103614_evo-builder",
        "version_RE1": null,
        "version_info": {
            "build": null,
            "major": [
                16,
                2
            ],
            "minor": "20180618103614_evo-builder",
            "type": "I"
        },
        "virtual": false
    }
}

**Comment by vnitinv** [comment]
Fixed via https://github.com/Juniper/py-junos-eznc/pull/862

to install code form github
pip install git+https://github.com/Juniper/py-junos-eznc.git
Please verify and close.

**Comment by mamathac** [comment]
Verified and found fixed.

PLAY [Testing Juniper Junos Core Modules] ********************************************************************************************************************************

TASK [Juniper Junos_get_config Module] ***********************************************************************************************************************************
ok: [evoeventtestj]

TASK [Juniper Junos_get_config - basic - read config into a file in CONF format.] ****************************************************************************************
ok: [evoeventtestj]

TASK [Juniper Junos_get_config - basic - verify line1 content] ***********************************************************************************************************
ok: [evoeventtestj] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Juniper Junos_get_config - basic - verify Configured Login Host] ***************************************************************************************************
ok: [evoeventtestj] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [juniper_junos_config - XML format write file] **********************************************************************************************************************
ok: [evoeventtestj]

TASK [juniper_junos_config - XML format - read config into line1 variable] ***********************************************************************************************
ok: [evoeventtestj]

TASK [juniper_junos_config Check for file] *******************************************************************************************************************************
ok: [evoeventtestj] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Juniper Junos_get_config - basic - Login Host in XML] **************************************************************************************************************
ok: [evoeventtestj] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP ***************************************************************************************************************************************************************
evoeventtestj              : ok=8    changed=0    unreachable=0    failed=0
