### ISSUE TITLE
Juniper Junos Ping fails on WR Linux Based Hardware QFX5200

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#382]
Issue Type

Bug Report
Module Name

juniper_junos_ping

Juniper.Junos role and Python libraries version
(ANS_virtualenv) root@nms5-grpc-server1:/etc/ansible/ANS_virtualenv/pb# ansible --version
ansible 2.4.0.0
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

(ANS_virtualenv) root@nms5-grpc-server1:/etc/ansible/ANS_virtualenv/pb# pip freeze
asn1crypto==0.23.0
bcrypt==3.1.4
cffi==1.11.2
cryptography==2.1.3
enum34==1.1.6
idna==2.6
ipaddress==1.0.18
Jinja2==2.10
junos-eznc==2.1.9.dev0
lxml==4.1.1
MarkupSafe==1.0
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.4.0
pyasn1==0.3.7
pycparser==2.18
PyNaCl==1.2.0
pyserial==3.4
PyYAML==3.12
scp==0.10.2
six==1.11.0

OS / Environment

Model: qfx5200-32c-32q
Junos: 16.2I20180618103614_evo-builder
Junos Package: junos-linux-install-qfx-x86-64-16.2I20180618103614_evo-builder.iso
Yocto: 2.2.1
Linux Kernel: 4.8.24-WR2.2.1_standard

Summary

Juniper Junos Ping results in below error although the netconf reply returns ping results.
Note: For Linux Based QFX5200, ping command is always provided with "routing-instance mgmtri" knob.

Actual result on router:

regress@<hostname>> ping <x.x.x.x> routing-instance mgmtri
...
...
...
Result : >> 3 packets transmitted, 3 received, 0% packet loss, time 1999ms

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Steps to reproduce

   - name: "Execute ping"
     juniper_junos_ping:
        host={{ inventory_hostname }}
        user=user
        passwd=Password
        dest=10.221.129.27
        routing_instance=mgmtri
     tags:
        - ans_ping

Expected results

When the ping reply is success, Playbook should return OK.

Actual results

On box Actual reply:

Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: </hello>
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: ]]>]]>
Jun 22 02:23:03 [NETCONF] - [23137] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:capabilities><nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability><nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability><nc:capa
Jun 22 02:23:03 [NETCONF] - [23137] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:e34f1d8d-2837-48f8-a30c-005d64dc7cd4"><ping><count>5</count><routing-instance>mgmtri</routing-instance><host>10.221.129.27</host><rapid/></ping></nc:rpc>]]>]]>
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/16.2I0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:e34f1d8d-2837-48f8-a30c-005d64dc7cd4">
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: <output>
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: .&#xe008; &#xe008;.&#xe008; &#xe008;.&#xe008; &#xe008;.&#xe008; &#xe008;.&#xe008; &#xe008;PING 10.221.129.27 (10.221.129.27) 56(84) bytes of data.
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing:
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: --- 10.221.129.27 ping statistics ---
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: 5 packets transmitted, 5 received, 0% packet loss, time 5ms
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: rtt min/avg/max/mdev = 1.311/1.362/1.529/0.089 ms, ipg/ewma 1.472/1.442 ms
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: </output>
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: </rpc-reply>
Jun 22 02:23:03 [NETCONF] - [23137] Outgoing: ]]>]]>

=================

PLAY [Testing Juniper Junos Core Modules] **************************************************************************************************************************************

TASK [Execute ping] ************************************************************************************************************************************************************
fatal: [imax]: FAILED! => {"acceptable_percent_loss": "0", "changed": false, "count": "5", "dest": "10.221.129.27", "dest_ip": "10.221.129.27", "do_not_fragment": false, "failed": true, "host": "10.221.129.27", "interface": null, "msg": "Probe-results-summary not found in response: <output>.&#57352; &#57352;.&#57352; &#57352;.&#57352; &#57352;.&#57352; &#57352;.&#57352; &#57352;PING 10.221.129.27 (10.221.129.27) 56(84) bytes of data. --- 10.221.129.27 ping statistics --- 5 packets transmitted, 5 received, 0% packet loss, time 5ms rtt min/avg/max/mdev = 1.311/1.362/1.529/0.089 ms, ipg/ewma 1.472/1.442 ms</output>\n", "rapid": true, "routing_instance": "mgmtri", "size": null, "source": null, "source_ip": null, "state": "absent", "timeout": "30", "ttl": null}
	to retry, use: --limit @/PATH/Renamed_Juniper_Junos_Ansible.pb.retry

PLAY RECAP *********************************************************************************************************************************************************************
imax                       : ok=0    changed=0    unreachable=0    failed=1

**Comment by vnitinv** [comment]
Dependent on internal PR #1368770. Please flag the internal PR

**Comment by mamathac** [comment]
As per Internal PR 1276657, Not modifying standard Linux output for ping reply. Changes to be made with respect to actual result for WR Linux.
