### ISSUE TITLE
Need Package support for WR Linux Based Hardware QFX 5200

### ISSUE THREAD

**Issue by mamathac** [Juniper/ansible-junos-stdlib#384]
Issue Type
------

 - Bug Report

Module Name
------

juniper_junos_software

Juniper.Junos role and Python libraries version

```
(ANS_virtualenv) root@jsnapy-server:/etc/ansible/ANS_virtualenv/pb# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

OS / Environment
------

asn1crypto==0.23.0
bcrypt==3.1.4
cffi==1.11.2
cryptography==2.1.3
enum34==1.1.6
idna==2.6
ipaddress==1.0.18
Jinja2==2.10
junos-eznc==2.1.8.dev1
lxml==4.1.1
MarkupSafe==1.0
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.4.0
pyasn1==0.3.7
pycparser==2.18
PyNaCl==1.2.0
pyserial==3.4
PyYAML==3.12
scp==0.10.2
six==1.11.0

Summary
------

Ansible Module juniper_junos_software looks for a .tgz image in the "local_package" field. However, WR Linux based QFX 5200 loads a .iso image.
Hence the module returns failure.

Steps to reproduce
------

Use  juniper_junos_software Playbook to install OS.

```yaml

  tasks:
    - name: Execute a basic Junos software upgrade.
      juniper_junos_software:
        local_package: ./"junos-linux-install-qfx-x86-64-16.2I20180622211051_evo-builder.iso"
      register: response
    - name: Print the complete response.
      debug:
        var: response
```

Expected results

```
Successful Image Installation.

```
Actual results
------

PLAY [Examples of juniper_junos_system] ****************************************************************************************************************************************

TASK [Execute a basic Junos software upgrade.] *********************************************************************************************************************************
fatal: [nautilus-a]: FAILED! => {"changed": false, "failed": true, "msg": "The local_package (/etc/ansible/ANS_virtualenv/pb/\"junos-linux-install-qfx-x86-64-16.2I20180622211051_evo-builder.iso\") is not a valid file on the local Ansible control machine."}
	to retry, use: --limit @/etc/ansible/ANS_virtualenv/pb/Install_OS.retry

```
<nautilus-a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509 `" && echo ansible-tmp-1529960091.51-201478115137509="` echo $HOME/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509 `" ) && sleep 0'
<nautilus-a> PUT /tmp/tmpM_8RMb TO /root/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509/juniper_junos_software.py
<nautilus-a> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509/ /root/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509/juniper_junos_software.py && sleep 0'
<nautilus-a> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509/juniper_junos_software.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1529960091.51-201478115137509/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_WSyyeQ/ansible_module_juniper_junos_software.py", line 384, in <module>
    from urllib.parse import urlparse

fatal: [nautilus-a]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "attempts": null,
            "baud": null,
            "checksum": null,
            "checksum_algorithm": "md5",
            "checksum_timeout": 300,
            "cleanfs_timeout": 300,
            "console": null,
            "force_host": false,
            "host": "nautilus-a",
            "issu": false,
            "logdir": null,
            "logfile": null,
            "mode": null,
            "nssu": false,
            "passwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 830,
            "provider": null,
            "ssh_private_key_file": null,
            "timeout": 30,
            "user": "root",
            "validate": false,
            "vmhost": false
        }
    },
    "msg": "The local_package (/etc/ansible/ANS_virtualenv/pb/\"junos-linux-install-qfx-x86-64-16.2I20180622211051_evo-builder.iso\") is not a valid file on the local Ansible control machine."
}
	to retry, use: --limit @/etc/ansible/ANS_virtualenv/pb/Install_OS.retry

PLAY RECAP *********************************************************************************************************************************************************************
nautilus-a                 : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by vnitinv** [comment]
Fixed via https://github.com/Juniper/py-junos-eznc/pull/862

to install code form github
pip install git+https://github.com/Juniper/py-junos-eznc.git
Please verify and close.

**Comment by rahkumar651991** [comment]
This is a very old issue, closing it due to inactivity. This should be fixed already. In case the issue still is relevant, kindly share the netconf logs captured on device for the execution.
Refer - https://www.juniper.net/documentation/us/en/software/junos/junos-xml-protocol/topics/example/netconf-traceoptions-configuring.html
