### ISSUE TITLE
juniper_junos_config TimeoutExpiredError after chaning IP

### ISSUE THREAD

**Issue by doellal** [Juniper/ansible-junos-stdlib#390]
Issue Type
 - Bug Report

Module Name
juniper_junos_config 

Juniper.Junos role and Python libraries version
Juniper.junos 2.1.0
ansible 2.4.2.0

OS / Environment
JUNOS 15.1X49-D50.3

Summary
Hello,

I use the juniper_junos_config module to send a new configuration to a srx300. However, I get a TimeoutExpiredError after the configuration on the srx300 has been commited. I have serial access to the srx300, so i can track the procedure of the playbook on ansible and srx300. In the configuration, the IP address of the srx300 is changed, may it be because the TimeoutExpiredError error occurs in the playbook? 

I have set the timeout up to 3000 seconds, but the TimeoutExpiredError still appears. The Error does not appear in the old version with junos_install_config. Is there another solution to transfer a new config as a set file and not get TimeoutExpiredError if the IP address is changed?
 
In the old Version junos_config this playbook worked and send a changed state back.

Steps to reproduce
------

```yaml
Playbook
Task:
      - name: install new config
        juniper_junos_config:
          host: "{{ inventory_hostname }}"
          port: "{{ sshport }}"
          user: "{{ username }}"
          passwd: "{{ password }}"
          load: 'set'
          file: "{{ config_path }}{{ config_file }}"
          logfile: "junos.log"
          comment: "commited by proboter"
          timeout: 120
        ignore_errors: yes
```

Expected results

```
1. connect to srx300
2. set config on srx300
3. check and commit
4. disconnect
5. callback config changed (rpc)
```
Actual results
------

                    "hosts": {
                        "37.138.94.205": {
                            "_ansible_no_log": false,
                            "_ansible_parsed": false,
                            "changed": false,
                            "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_IDdGPo/ansible_module_juniper_junos_config.py\", line 1123, in <module>\n    main()\n  File \"/tmp/ansible_IDdGPo/ansible_module_juniper_junos_config.py\", line 1105, in main\n    confirmed=confirmed)\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1680, in commit_configuration\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 805, in fail_json\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1400, in close_configuration\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 807, in fail_json\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1327, in close\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/device.py\", line 1317, in close\n    self._conn.close_session()\n  File \"/usr/lib/python2.7/site-packages/ncclient/manager.py\", line 162, in wrapper\n    return self.execute(op_cls, *args, **kwds)\n  File \"/usr/lib/python2.7/site-packages/ncclient/manager.py\", line 232, in execute\n    raise_mode=self._raise_mode).request(*args, **kwds)\n  File \"/usr/lib/python2.7/site-packages/ncclient/operations/session.py\", line 28, in request\n    return self._request(new_ele(\"close-session\"))\n  File \"/usr/lib/python2.7/site-packages/ncclient/operations/rpc.py\", line 343, in _request\n    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')\nncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.\n",
                            "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_IDdGPo/ansible_module_juniper_junos_config.py\", line 1123, in <module>\n    main()\n  File \"/tmp/ansible_IDdGPo/ansible_module_juniper_junos_config.py\", line 1105, in main\n    confirmed=confirmed)\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1680, in commit_configuration\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 805, in fail_json\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1400, in close_configuration\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 807, in fail_json\n  File \"/tmp/ansible_IDdGPo/ansible_modlib.zip/ansible/module_utils/juniper_junos_common.py\", line 1327, in close\n  File \"/usr/lib/python2.7/site-packages/jnpr/junos/device.py\", line 1317, in close\n    self._conn.close_session()\n  File \"/usr/lib/python2.7/site-packages/ncclient/manager.py\", line 162, in wrapper\n    return self.execute(op_cls, *args, **kwds)\n  File \"/usr/lib/python2.7/site-packages/ncclient/manager.py\", line 232, in execute\n    raise_mode=self._raise_mode).request(*args, **kwds)\n  File \"/usr/lib/python2.7/site-packages/ncclient/operations/session.py\", line 28, in request\n    return self._request(new_ele(\"close-session\"))\n  File \"/usr/lib/python2.7/site-packages/ncclient/operations/rpc.py\", line 343, in _request\n    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')\nncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.\n",
                            "module_stdout": "",
                            "msg": "MODULE FAILURE",
                            "rc": 0
                        }
                    },
                    "task": {
                        "id": "005056a9-5637-8a56-309d-00000000000b",
                        "name": "install new config"
                    }

**Comment by vnitinv** [comment]
@doellal As you mentioned `In the configuration, the IP address of the srx300 is changed`, once the IP is changed, plyabook working on existing hosts will try to reach the old IP itself. Hence the issue is seen. You might need to check if we can replace the IP in inventory on go with the New IP.

**Comment by doellal** [comment]
I know the new IP, but its managed by RADIUS and i would have to wait for the login. After Login the new IP would be accesable, but iam surprised that the deprecated module junos_install_config did not got a timeout and send a changed state to the playbook. After that the playbook complete and don't got a error. 

We replace the IP in the inventory after the configuration is changed. We have now a second Playbook that checks the new ip and gives me informationen, if the juniper is properly configured.

**Comment by mfatty** [comment]
@vnitinv @doellal 
I'm running into the same issue here. I haven't tested this yet but I'm supposed to change the ip_address of a juniper host, this is the same ip address that ansible uses to connect to the host. That means once the ip is changed, the remaining tasks will not be executed because ansible cannot reach the host anymore. 

Is there a workaround for this?

**Comment by mfatty** [comment]
@vnitinv 
What if in the host file, I specify two ip_addresses: old and new ip? Is this even possible? That way once old is removed, ansible can continue it's work with the new ip.

**Comment by rahkumar651991** [comment]
@mfatty - you may give the hostname of the device instead of IP. I hope the device-name doesn't change. 

juniper_junos_config:
          host: "37.138.94.205"

juniper_junos_config:
          host: "srx300"

both will work.

**Comment by rahkumar651991** [comment]
Based on the discussion, closing the issue due to inactivity.
