### ISSUE TITLE
juniper_junos_software playbook stop while performing upgrade

### ISSUE THREAD

**Issue by davbeny** [Juniper/ansible-junos-stdlib#406]
Issue Type
------

 - Bug Report
Module Name
------
juniper_junos_software

Juniper.Junos role and Python libraries version

```Ansible version 2.7.0

```

OS / Environment
------

12R12S11
EX3300
Summary
------- The playbooks stop when the engine start it's upgrade.
PLAY [Install Junos OS] ***********************************************************************************************
TASK [Checking NETCONF connectivity] **********************************************************************************
ok: [switch1.production.com]
TASK [Install Junos OS package] ***************************************************************************************
fatal: [switch1.production.com]: FAILED! => {"changed": true, "check_mode": false, "msg": "Package jinstall-ex-3300-12.3R12-S11-domestic-signed.tgz successfully installed. Did not find expected response from reboot RPC."}
to retry, use: --limit 

Install is sucessfull but we're not able to track the progress when using the playbook.

I use the generic playbook available here :

https://www.juniper.net/documentation/en_US/junos-ansible/topics/example/junos-ansible-playbooks-device-os-installing.html

Steps to reproduce
------

```yaml

```

Expected results

```

```
Actual results
------

```

```

**Comment by davbeny** [comment]
Hello, any ideas on how to correct this issue? Thanks. Regards

**Comment by rsmekala** [comment]
@davbeny Ok, This looks similar to the #408

**Comment by chidanandpujar** [comment]
Hi @davbeny 
Please verify the fix - https://github.com/Juniper/ansible-junos-stdlib/pull/475
Please re-open the issue ,if it is reproducible.

Thanks
