### ISSUE TITLE
Feature: Improve juniper_junos_system module behaviour for VC setup

### ISSUE THREAD

**Issue by ydnath** [Juniper/ansible-junos-stdlib#410]
Issue Type
------

 - Feature Idea

Module Name
------

juniper_junos_system
Juniper.Junos role and Python libraries version

```

```

OS / Environment
------

Summary
------

Handle the below cases:
VC where each member has a single RE; Ansible is connected to the master:
  action: reboot with all_re: true
  action: reboot with all_re: false
  action: reboot with other_re: false
  action: reboot with other_re: true
 
VC where each member has dual REs; Ansible is connected to the master:
  action: reboot with all_re: true
  action: reboot with all_re: false
  action: reboot with other_re: true
  action: reboot with other_re: false

Steps to reproduce
------

```yaml

```

Expected results

```

```
Actual results
------

```

```

**Comment by rahkumar651991** [comment]
The feature has been implemented and integrated with PyEZ. 
Closing this.
