### ISSUE TITLE
get-support-information no output in text format- xml working

### ISSUE THREAD

**Issue by CodeTechies** [Juniper/ansible-junos-stdlib#419]
Issue Type
------
get-support-information/RSI  no output in text format- xml working

Module Name
Junos_junos_rpc
juniper_junos_command

Juniper.Junos role and Python libraries version

ansible --version
ansible 2.5.3
  config file = /var/lib/awx/projects/Francis/junosupgrade/ansible.cfg
  configured module search path = [u'/home/nera/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

pip freeze
ansible==2.5.3
Babel==0.9.6
backports.ssl-match-hostname==3.5.0.1
certifi==2018.4.16
cffi==1.6.0
chardet==3.0.4
click==6.7
configobj==4.7.2
cryptography==1.7.2
decorator==3.4.0
docopt==0.6.2
enum34==1.0.4
Flask==1.0.2
grip==4.5.2
httplib2==0.9.2
idna==2.7
iniparse==0.4
ipaddress==1.0.16
IPy==0.75
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.0
junos-eznc==2.1.7
jxmlease==1.0.1
kitchen==1.1.1
lxml==4.2.1
Markdown==2.6.11
MarkupSafe==1.0
meld3==0.6.10
mercurial==2.6.2
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.1.1
passlib==1.6.5
path-and-address==2.0.1
perf==0.1
ply==3.4
policycoreutils-default-encoding==0.1
psycopg2==2.7.4
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.0
Pygments==2.2.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyserial==3.4
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
requests==2.19.0
schedutils==0.4
scp==0.11.0
seobject==0.1
sepolicy==1.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
supervisor==3.1.4
urlgrabber==3.10
urllib3==1.23
virtualenv==15.1.0
Werkzeug==0.14.1
yum-metadata-parser==1.1.4

OS / Environment
------

Model: ex4300-24p
Junos: 14.1X53-D47.6
JUNOS EX  Software Suite [14.1X53-D47.6]
JUNOS FIPS mode utilities [14.1X53-D47.6]
JUNOS Online Documentation [14.1X53-D47.6]
JUNOS EX 4300 Software Suite [14.1X53-D47.6]
JUNOS Web Management Platform Package [14.1X53-D47.6]
JUNOS py-base-powerpc [14.1X53-D47.6]
Summary
------

Steps to reproduce
------

```yaml

```

Expected results

```

```
Actual results
------

```

```

**Comment by rsmekala** [comment]
@CodeTechies Can you please attach the playbook output and Ansible logs for debugging purposes ??
