### ISSUE TITLE
Minor modifications in comment.

### ISSUE THREAD

**Issue by wnelis** [Juniper/ansible-junos-stdlib#423]
Issue Type
------
 - Documentation Report

Module Name
------

juniper_junos_common.py

Summary
------
Some (possible) typo's found in comment.

[juniper_junos_common.diff.txt](https://github.com/Juniper/ansible-junos-stdlib/files/3025358/juniper_junos_common.diff.txt)

**Comment by rsmekala** [comment]
@wnelis Thanks for pointing this out. Can we expect a pull request from your side ??

**Comment by wnelis** [comment]
I'm still at the very beginning of the learning curve w.r.t git(hub). What is the benefit of a pull request? I just wanted to read the module, as it was hard to find some documentation on writing python user modules for configuring a Juniper switch.

**Comment by ntwrkguru** [comment]
@wnelis The benefit is that you can contribute those fixes into the project directly. I have included these in #424.

**Comment by rsmekala** [comment]
Merged via #424
