### ISSUE TITLE
juniper_junos_software RPC <bad-element>request-package-validate</bad-element>

### ISSUE THREAD

**Issue by omegafoo** [Juniper/ansible-junos-stdlib#439]
Issue Type
------

 - Bug Report

Module Name
------

juniper_junos_software

```
Juniper.Junos role version 2.2.0
ansible 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Mar 26 2019, 22:13:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

pip freeze
asn1crypto==0.24.0
bcrypt==3.1.6
cffi==1.12.1
cryptography==2.5
Jinja2==2.8
junos-eznc==2.2.0
jxmlease==1.0.1
lxml==4.3.1
MarkupSafe==0.23
ncclient==0.6.3
netaddr==0.7.19
paramiko==2.4.2
pexpect==4.2.1
ptyprocess==0.5.1
pyasn1==0.4.5
pycparser==2.19
PyNaCl==1.3.0
pyserial==3.4
PyYAML==3.13
scp==0.13.0
selectors2==2.0.1
six==1.12.0
virtualenv==13.1.2
```

OS / Environment
------

Juniper EX3400-24T version 18.1R3.3

Summary
------

We are running some EX3400-24T switches with 18.1R3 code and I had an Ansible playbook that was working for upgrading software successfully on 15.1 code. With the 18.1 code I'm running into an error with software validation. The last switch that I ran this against is running JUNOS 18.1R3.3

When I run that playbook with -vvvv I get the following output

```TASK [Installing Junos OS package] **********************************************************************************************************************
task path: /etc/ansible/bes-software-install.yml:34
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_juniper_junos_software_payload_hPcmGD/__main__.py", line 660, in main
    ok = junos_module.sw.install(**install_params)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 865, in install
    dev_timeout=timeout)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 330, in validate
    package_name=remote_package, **kwargs).getparent()
  File "/usr/lib/python2.7/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/decorators.py", line 23, in wrapper
    result = function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jnpr/junos/device.py", line 794, in execute
    errs=ex)

fatal: [host.fqdn]: FAILED! => changed=true
  check_mode: false
  invocation:
    module_args:
      attempts: null
      baud: null
      checksum: null
      checksum_algorithm: md5
      checksum_timeout: 300
      cleanfs_timeout: 300
      console: null
      force_host: false
      host: host.fqdn
      issu: false
      level: null
      logdir: null
      logfile: null
      mode: null
      nssu: false
      passwd: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      port: 22
      ssh_config: null
      ssh_private_key_file: null
      timeout: 30
      user: user_id
      validate: true
      vmhost: false
  msg: 'Installation failed. Error: RpcError(severity: error, bad_element: request-package-validate, message: syntax error)'
        to retry, use: --limit @/etc/ansible/bes-software-install.retry
```
After a lot of searching I ran across the netconf debuggin, turned it on and here is what I have in the netconf logs

```
Jun 21 13:22:34 [NETCONF] - [62875] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:14cc698d-1133-4a43-8365-b09b5cccf2e0"><request-package-validate><package-name>/var/tmp/junos-arm-32-18.1R3-S4.2.tgz</package-name></request-package-validate></nc:rpc>]]>]]>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/18.1R3/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:14cc698d-1133-4a43-8365-b09b5cccf2e0">
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <rpc-error>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <error-type>protocol</error-type>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <error-tag>operation-failed</error-tag>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <error-severity>error</error-severity>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <error-message>syntax error</error-message>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <error-info>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: <bad-element>request-package-validate</bad-element>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: </error-info>
Jun 21 13:22:34 [NETCONF] - [62875] Outgoing: </rpc-error>
```

Steps to reproduce
------

You can run the playbook below on 18.1R3.3 and it should reproduce the error every time. If I remove the 'validate: true' it will skip validation and the playbook completes successfully.

My playbook is as follows:
```
---
- name: 'BES Software Upgrade ### WITH NO REBOOT ###'
  hosts:
    - bes
  roles:
    - Juniper.junos
    - bes
  connection: local
  gather_facts: no

  vars_prompt:
    - name: os_package
      prompt: "Enter the JUNOS package filename to install"
      private: no

  vars_files:
    - "{{ lookup('env', 'HOME') }}/.ansible/myvault.yml"

  vars:
    connection_settings:
      user: "{{ lookup('env', 'USER') }}"
      host: "{{ inventory_hostname }}"
      port: 22
      passwd: "{{ vault_tacacs_pwd }}"

  tasks:
    - name: Checking NETCONF connectivity
      wait_for:
        host: "{{ host }}"
        port: "{{ connection_settings['port'] }}"
        timeout: 5

    - name: Installing Junos OS package
      juniper_junos_software:
        provider: "{{ connection_settings }}"
        local_package: "/tftpboot/juniper/ex3400/{{ os_package }}"
        logdir: "{{ playbook_dir }}"
        reboot: false
        validate: true
        kwargs:
          unlink: true
        version: "18.1R3-S4.2"
      register: response

    - name: Print Response
      debug:
        var: response

**Comment by indirakas** [comment]
I am getting exactly the same error with the only difference of having EX2300-C-12T switch.

**Comment by cserranobr** [comment]
Hello All,
I work in JTAC and we have a customer with this issue. They would like to know when will this be fixed.
Regards,
Carlos.

**Comment by rsmekala** [comment]
@omegafoo @indirakas "validate" isn't supported for EX devices AFAIK, so please try running the playbook without setting "validate" option.

**Comment by PhobicShades** [comment]
> @omegafoo @indirakas "validate" isn't supported for EX devices AFAIK, so please try running the playbook without setting "validate" option.

Seems to be true for QFX5120-48Y too. After setting 'validate: false' in my playbook, the upgrade succeeded (from version 18.4R1-S2.4 to 18.4R2.7).

**Comment by KobesM** [comment]
I can also confirm that validation does not work using the ansible module for QFX5100-48s and QFX5120-48y. For the QFX5100 this is only the issue when using 5e-series firmware but not when using the 5-series firmware.

We are updating to 18.4R2-S5.4.

So to summarize:
- QFX5100-48s with **5-series** firmware (jinstall-host-qfx-5-18.4R2-S5.4-signed.tgz) with validate set to **true** using juniper_junos_software - **Success**
- QFX5100-48s with **5e-series** firmware (jinstall-host-qfx-5e-x86-64-18.4R2-S5.4-secure-signed.tgz) with validate set to **true** using juniper_junos_software - **Fail**
- QFX5100-48s with **5e-series** firmware (jinstall-host-qfx-5e-x86-64-18.4R2-S5.4-secure-signed.tgz) with validate set to **false** using juniper_junos_software - **Success**

- QFX5120-48y with **5e-series** firmware (jinstall-host-qfx-5e-x86-64-18.4R2-S5.4-secure-signed.tgz) with validate set to **true** using juniper_junos_software - **Fail**
- QFX5120-48y with **5e-series** firmware (jinstall-host-qfx-5e-x86-64-18.4R2-S5.4-secure-signed.tgz) with validate set to **false** using juniper_junos_software - **Success**

Manual installiation of the firmware from the CLI with validation does succeed: request system software add /var/tmp/jinstall-host-qfx-5e-x86-64-18.4R2-S5.4-secure-signed.tgz reboot

We are using the juniper/pyez-ansible:2.4.3 container.

**Comment by rahkumar651991** [comment]
based on the discussion, setting validate flag as false resolves it as it is not supported for some device.
closing the issue.
