### ISSUE TITLE
security nat source acting all weird

### ISSUE THREAD

**Issue by djatlantic** [Juniper/ansible-junos-stdlib#44]
Hi all, 

I am new to Juniper OS ( 12.1X44.3 ) and I have tried to setup security nat source with the following:

set security address-book global address dmz70 wildcard-address 192.168.7.0/255.255.255.0
set security address-book global address lan50 wildcard-address 192.168.5.0/255.255.255.0
set security address-book global address lan60 wildcard-address 192.168.6.0/255.255.255.0
set security address-book global address lan80 wildcard-address 192.168.8.0/255.255.255.0
set security address-book global address la2vpn wildcard-address 172.16.8.0/255.255.255.0
set security address-book global address sj2vpn wildcard-address 172.16.11.0/255.255.255.0
set security address-book global address sj wildcard-address 172.16.1.0/255.255.255.0
set security address-book global address va2-4 wildcard-address 10.0.4.0/255.255.255.0
set security address-book global address va2-8 wildcard-address 10.0.8.0/255.255.255.0

set security nat source rule-set snat-out from zone dmz
set security nat source rule-set snat-out from zone trust
set security nat source rule-set snat-out to zone untrust

set security nat source rule-set snat-out rule VPNNATOFF match source-address  lan50
set security nat source rule-set snat-out rule VPNNATOFF match source-address  lan60
set security nat source rule-set snat-out rule VPNNATOFF match source-address  lan80
set security nat source rule-set snat-out rule VPNNATOFF match source-address  la2vpn
set security nat source rule-set snat-out rule VPNNATOFF match source-address  sj2vpn      
set security nat source rule-set snat-out rule VPNNATOFF match source-address  sj
set security nat source rule-set snat-out rule VPNNATOFF match source-address  dmz70
set security nat source rule-set snat-out rule VPNNATOFF match destination-address va2-4 
set security nat source rule-set snat-out rule VPNNATOFF match destination-address va2-8 
set security nat source rule-set snat-out rule VPNNATOFF then source-nat off

set security nat source rule-set snat-out rule snat-out match source-address  lan50
set security nat source rule-set snat-out rule snat-out match source-address  lan60
set security nat source rule-set snat-out rule snat-out match source-address  lan80
set security nat source rule-set snat-out rule snat-out match source-address  dmz70
set security nat source rule-set snat-out rule snat-out then source-nat interface

------
Ansible playbook ran until completion without any errors but then I got this from the above.  This is really unexpected and I just do not know where x.x.114.94/32 is from.  I do not have anything in my config with this x.x.114.94/32 (x.x were replaced for security).

steven@sc2-jnpr-fw# show security nat source
rule-set snat-out {
    from zone [ dmz trust ];
    to zone untrust;csteven@sc2-jnpr-fw# show security nat source
rule-set snat-out {
    from zone [ dmz trust ];
    to zone untrust;
    rule VPNNATOFF {
        match {
            source-address x.x.114.94/32;
            destination-address x.x.114.94/32;
        }
        then {
            source-nat {
                off;
            }
        }
    }
    rule snat-out {
        match {
            source-address x.x.114.94/32;
        }
        then {
            source-nat {
                interface;
            }
        }
    }
}

I grepped my config and nothing of x.x114.94/32 is in there except for the nat source entries.

steven@sc2-jnpr-fw# show |grep 114.94
                        source-address x.x.114.94/32;
                        destination-address x.x.114.94/32;
                        source-address x.x.114.94/32;

Thanks.

**Comment by shermdog** [comment]
Closed due to lack of response.
