### ISSUE TITLE
vmhost reboot for dual RE

### ISSUE THREAD

**Issue by vnitinv** [Juniper/ansible-junos-stdlib#442]
- Bug Report

Module Name
------
juniper_junos_software

Summary
------
For dual RE system, software install fails with error

Reboot failed. Error: RpcError(severity: error, bad_element: both-routing-engines, message: syntax error, expecting <invoke-on>)"}

**Comment by rahkumar651991** [comment]
this is fixed with code changes done in newer releases of PyEZ. 
Closing this.
