### ISSUE TITLE
Check if requirements.txt needs entry for ansible

### ISSUE THREAD

**Issue by ydnath** [Juniper/ansible-junos-stdlib#448]
Issue Type
------

 - Bug Report
 - Feature Idea
 - Documentation Report

Module Name
------

Juniper.Junos role and Python libraries version

```

```

OS / Environment
------

Summary
------

Steps to reproduce
------

```yaml

```

Expected results

```

```
Actual results
------

```

```

**Comment by rsmekala** [comment]
Fixed via #451
