### ISSUE TITLE
Not able install PyEz on mac 

### ISSUE THREAD

**Issue by Nirosh-123** [Juniper/ansible-junos-stdlib#449]
Not able install PyEz getting below error,

nkumarreddy-mbp:~ nkumarreddy$ sudo pip install junos-eznc
Password:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/Users/nkumarreddy/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/nkumarreddy/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting junos-eznc
  Downloading https://files.pythonhosted.org/packages/da/6c/6a9c839f2d7bef53381c84a7e49620b44a87633306832bc5e3bf7b68fe00/junos_eznc-2.2.1-py2.py3-none-any.whl (159kB)
     |████████████████████████████████| 163kB 687kB/s 
Collecting paramiko>=1.15.2 (from junos-eznc)
  Downloading https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl (199kB)
     |████████████████████████████████| 204kB 2.2MB/s 
Collecting ncclient>=0.5.4 (from junos-eznc)
  Downloading https://files.pythonhosted.org/packages/36/b1/1f909193588dfd35726e8ae35e01463386bbcf670b90ed61c4930ce447db/ncclient-0.6.6.tar.gz (89kB)
     |████████████████████████████████| 92kB 962kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-aQNEOC/ncclient/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-aQNEOC/ncclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/tmp/pip-install-aQNEOC/ncclient/
    Complete output (3 lines):
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in ncclient setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected ',' or end-of-list in selectors2>=2.0.1; python_version <= '3.4' at ; python_version <= '3.4'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

PLease help me to install PyEz

**Comment by rsmekala** [comment]
@Nirosh-123 Can you please share the output of the following commands as well ??

```
python --version
pip --version
pip list
```

According to me, you are unable to install `ncclient` rather than PyEZ itself. Can you try running the following command and share the output ??

```
pip install ncclient
```

**Comment by Nirosh-123** [comment]
after trying with pip3 it worked.

Thank You
