### ISSUE TITLE
Question: Commit only once when using juniper_junos_config

### ISSUE THREAD

**Issue by routenull0** [Juniper/ansible-junos-stdlib#464]
Issue Type
------
 - Question

Module Name
------
- juniper_junos_config

Juniper.Junos role and Python libraries version

ansible 2.8.5
  config file = /netops/netops_ansible/ansible.cfg
  configured module search path = [u'/netops/netops_ansible_modules']
  ansible python module location = /netops/netops_python_env/lib/python2.7/site-packages/ansible
  executable location = /netops/netops_python_env/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

ansible==2.8.5
asn1crypto==0.24.0
bcrypt==3.1.7
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
cryptography==2.7
enum34==1.1.6
idna==2.8
ipaddress==1.0.22
Jinja2==2.10.1
junos-eznc==2.2.1
jxmlease==1.0.1
lxml==4.3.4
MarkupSafe==1.1.1
ncclient==0.6.6
netaddr==0.7.19
paramiko==2.6.0
psutil==5.6.3
pycparser==2.19
PyNaCl==1.3.0
pyserial==3.4
pyvmomi==6.7.3
PyYAML==5.1.2
requests==2.22.0
scp==0.13.2
selectors2==2.0.1
six==1.12.0
urllib3==1.25.6
```
- Juniper.junos, 2.2.1

```

OS / Environment
------
Red Hat Enterprise Linux Server release 7.4 (Maipo)

Summary
------

Is it possible when using the juniper_junos_config module to only do a single commit over the course of several tasks?

I break our configurations down into specific sections and I have a role built with tasks that modify just a specific configuration section through a `load: merge`. Each task is tagged so that if I only want to execute that specific task in the role I can.

The issue is that when I apply the role to a host, the juniper_junos_config module wants to commit each task as it goes, which drives the time to complete through the roof when there are lots of tasks.

Example:
I break the configuration down into sections, I have a section for all our settings for `system->services->ssh` and `system->services->ntp`
The role has two tasks defined, one for SSH configuration and the other for NTP configuration. Each of those tasks takes the respective .conf file from within the role/files/ and performs a `load:merge` with the juniper_junos_config module.

I've tried setting `commit: false` and attempted to use a handler to do the commit but I cannot get it working properly. My intent is to be able to target a specific task with our tags and then doing a final commit when I only need to update a specific config section, say an NTP key.

Maybe I am going about it wrong, but on existing devices I don't want to be 1) replacing sections that I don't need to and 2) committing after each task.

**Comment by ssawtell** [comment]
Please consider the following approach:

* The roles use the template module to process the templates, or the copy module to copy a static config file, writing to a temporary target directory created to hold these temporary files. (The roles do not call juniper_junos_config.)

* Use the assemble module to combine the temporary files into a single Junos configuration file.

* Use juniper_junos_config once to upload the assembled configuration.

See https://github.com/Juniper/junosautomation/tree/master/ansible/Automating_Junos_with_Ansible/chapter_12 for an example (minus the tags) from “Automating Junos with Ansible.”

**Comment by routenull0** [comment]
That's a much better way, thanks for the point in the right direction.
