### ISSUE TITLE
junos_install_os not supported with EX4300 Virtual Chassis.

### ISSUE THREAD

**Issue by Hamelpa** [Juniper/ansible-junos-stdlib#47]
When I use the junos_install_os with a stack of EX4300 in a VC, only the Master RE reboots at the end and the playbook fails. I have to manually reboot the other members in the virtual chassis to finalize the installation.

Thanks,
Patrick

**Comment by vnitinv** [comment]
This should now be working with latest PyEZ 1.2.3
