### ISSUE TITLE
junos-eznc (aka PyEZ) >= 2.2.0 is required

### ISSUE THREAD

**Issue by anaaman** [Juniper/ansible-junos-stdlib#478]
Issue Type
------
 - Bug Report

Module Name
------
ansible --version
ansible 2.9.2
config file = /Users/asafn/Documents/junos-ansible/ansible.cfg
configured module search path = ['/Users/asafn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]

pip3 freeze
ansible==2.9.2
asn1crypto==0.24.0
bcrypt==3.1.7
cffi==1.13.2
colorama==0.4.3
configparser==4.0.2
cryptography==2.8
future==0.18.2
icdiff==1.9.1
Jinja2==2.10.3
jsnapy==1.3.2
junos-eznc==2.2.0
jxmlease==1.0.1
lxml==4.4.2
MarkupSafe==1.1.1
ncclient==0.6.7
netaddr==0.7.19
paramiko==2.7.1
pycparser==2.19
PyNaCl==1.3.0
pyparsing==2.4.6
pyserial==3.4
PyYAML==5.3
scp==0.13.2
six==1.14.0
transitions==0.7.2
yamlordereddictloader==0.4.0

OS / Environment
------

Summary
------
Trying to run any Juniper.junos playbook display the message:
FAILED! => {"changed": false, "msg": "junos-eznc (aka PyEZ) >= 2.2.0 is required for this module. However, junos-eznc does not appear to be currently installed. See https://github.com/Juniper/py-junos-eznc#installation for details on installing junos-eznc."}

I have simple python file:
from pprint import pprint
from jnpr.junos import Device

with Device(host='x.x.x.x', user='root', password='YYYYY' ) as dev:
    pprint( dev.facts )

which runs with python3 test.py

Steps to reproduce
------
Installed Python3, Ansible, PyEZ and Juniper.junos on macOS Catalina

**Comment by kr3ator** [comment]
Please run your playbook with -v parameter and check in the output what is the discovered Python interpreter.

Most probably the discovered interpreter is different from Python3 for which You've installed the PyEZ package.

You can set the interpreter in ansible.cfg or via magic variable called `ansible_python_interpreter`.

**Comment by vnitinv** [comment]
@anaaman I hope `ansible_python_interpreter` should help you here. Closing this issue for now. If still facing this please re-open.
