### ISSUE TITLE
Text Input file - juniper_junos_command

### ISSUE THREAD

**Issue by nandhuvi** [Juniper/ansible-junos-stdlib#545]
Issue Type
------
 - Feature Idea

Module Name
------
juniper_junos_command
-->

juniper.device collection and Python libraries version

```
ansible --version
ansible 2.10.6
  config file = /Users/nandhuv/Documents/ansible/ansible.cfg
  configured module search path = ['/Users/nandhuv/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/3.0.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:26:09) [Clang 12.0.0 (clang-1200.0.32.29)]
```

OS / Environment
------
Model: ex4300-48p
Junos: 17.3R3-S4.2

Summary
------
I would like to know if there's anyway we can use a set of commands from a text file under the juniper_junos_command module. I only see an option to use the command and then issue the list of commands we want to run. I would like to run a set of operational commands from a text file input if it's possible. The same way we use the 'src' option under juniper_junos_config module.

**Comment by rahkumar651991** [comment]
Hi @nandhuvi  - we don't have such a provision in juniper_junos_command as of now.

**Comment by dineshbaburam91** [comment]
This can be achieved using ansible built-in modules, no changes are needed from juniper ansible collection.

File:
```
% cat command.txt 
show version
show route
```

Sample Playbook:
```
---
- name: Test juniper.device.command module
  hosts: all
  gather_facts: no

  tasks:
    - name: Register a file content as a variable
      ansible.builtin.command: cat command.txt
      register: result

    - name:  Execute juniper commands.
      juniper.device.command:
        commands: "{{ item }}"
      loop: "{{ result.stdout_lines }}" 
      register: test1

    - name: "Print the response"
      debug:
        var: test1 
```
