### ISSUE TITLE
Return more verbose error message

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#56]
Hi,

Right now if the network device returns an error, it's properly logged in the logfile, while only "Unable to make changes" is returned to Ansible. To me, the most verbose/useful error should be returned to Ansible.
If so, I think nothing gets caught in the "except CommitError" and defaults to "except Exception".
I'll wait before trying to send a pull request :P

Thx!

**Comment by shermdog** [comment]
Internal note: Remember our Lync meeting....
