### ISSUE TITLE
logfile not being found in juniper.device.software

### ISSUE THREAD

**Issue by holynakamoto** [Juniper/ansible-junos-stdlib#568]
Issue Type
------

 - Bug Report

Module Name
------

juniper.device collection and Python libraries version

```
ansible [core 2.11.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/nmoore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/nmoore/.ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) [Clang 6.0 (clang-600.0.57)]
  jinja version = 3.0.1
  libyaml = True

aiohttp==3.7.4.post0
ansible-lint==5.1.2
anyio==3.3.0
appnope==0.1.2
argcomplete==1.12.3
argon2-cffi==20.1.0
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
bcrypt==3.2.0
bleach==4.0.0
boto3==1.18.11
botocore==1.21.11
bracex==2.1.1
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
charset-normalizer==2.0.4
colorama==0.4.4
commonmark==0.9.1
configparser==5.0.2
cryptography==3.4.7
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
docker==4.4.4
docker-py==1.10.6
docker-pycreds==0.4.0
enrich==1.2.6
entrypoints==0.3
future==0.18.2
icdiff==2.0.4
idna==3.2
ipykernel==6.0.3
ipython==7.26.0
ipython-genutils==0.2.0
jedi==0.18.0
Jinja2==3.0.1
jmespath==0.10.0
jsnapy==1.3.6
json5==0.9.6
jsonschema==3.2.0
junos-eznc==2.6.2
jupyter-client==6.2.0
jupyter-core==4.7.1
jupyter-server==1.10.2
jupyterlab==3.1.4
jupyterlab-pygments==0.1.2
jupyterlab-server==2.6.2
jxmlease==1.0.3
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib-inline==0.1.2
meraki==1.10.0
mistune==0.8.4
multidict==5.1.0
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
ncclient==0.6.9
nest-asyncio==1.5.1
netaddr==0.8.0
notebook==6.4.2
packaging==21.0
pan-os-python==1.4.0
pan-python==0.16.0
pandocfilters==1.4.3
paramiko==2.7.2
parso==0.8.2
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.11.0
prompt-toolkit==3.0.19
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.9.0
PyNaCl==1.4.0
pyparsing==2.4.7
pyrsistent==0.18.0
pyserial==3.5
python-dateutil==2.8.2
pytz==2021.1
pywatchman==1.4.1
PyYAML==5.4.1
pyzmq==22.2.1
requests==2.26.0
requests-unixsocket==0.2.0
resolvelib==0.5.5
rich==10.7.0
ruamel.yaml==0.17.10
ruamel.yaml.clib==0.2.6
s3transfer==0.5.0
scp==0.13.6
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
tenacity==8.0.1
terminado==0.10.1
testpath==0.5.0
tornado==6.1
traitlets==5.0.5
transitions==0.8.8
typing-extensions==3.10.0.0
urllib3==1.26.6
wcmatch==8.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.1.1
xmltodict==0.12.0
yamllint==1.26.2
yamlordereddictloader==0.4.0
yarl==1.6.3

# /Users/nmoore/.ansible/roles
- Juniper.junos, 2.4.3
```

OS / Environment
------
 18.4R2-S5.4

Summary
------
<img width="915" alt="Screen Shot 2021-09-15 at 4 51 31 PM" src="https://user-images.githubusercontent.com/407440/133527810-0079d7cd-6191-4b85-b4dd-2b5dfaf972f7.png">

Steps to reproduce
------
Not seeing log ouput, it appears as though vscode thinks logfile is not under the software module

When I hover over path under software I get the following:

<img width="1182" alt="Screen Shot 2021-09-15 at 4 44 04 PM" src="https://user-images.githubusercontent.com/407440/133527268-b561d48a-5851-4c4c-a5f0-f47cfe339412.png">

I am using roles my file structure is as such:

<img width="598" alt="Screen Shot 2021-09-15 at 4 46 22 PM" src="https://user-images.githubusercontent.com/407440/133527454-e79d681e-e5b0-459b-9b7f-25716d82987a.png">

<img width="413" alt="Screen Shot 2021-09-15 at 4 49 43 PM" src="https://user-images.githubusercontent.com/407440/133527663-7daea473-2a77-44c6-ad3d-b92a02ad797c.png">

```yaml

```

Expected results

```

```
Actual results
------

```

```

**Comment by holynakamoto** [comment]
I started getting log data back when I used verbose output, however I'm still curious why the extension isn't picking up logfile.

**Comment by rahkumar651991** [comment]
Hi, 

I just tried in my local setup and it works fine. Are you providing the complete path of the file? 
I am not sure what could be the reason for the issue.

**Comment by holynakamoto** [comment]
Yes I'm providing an absolute path, which makes it even stranger.  The behavior is intermittent 
<img width="1472" alt="Screen Shot 2021-09-17 at 6 02 19 AM" src="https://user-images.githubusercontent.com/407440/133787206-17af47a0-674a-4e25-ac98-683c36ea309f.png">
<img width="1510" alt="Screen Shot 2021-09-17 at 6 02 41 AM" src="https://user-images.githubusercontent.com/407440/133787211-9e078d7b-81ad-4838-a9f0-21c191bff7fb.png">
