### ISSUE TITLE
SSH fails with "shell request failed on channel 0" on Juniper vMX device

### ISSUE THREAD

**Issue by nishantag** [Juniper/ansible-junos-stdlib#574]
When trying to SSH into a Juniper vMX device with a configured username/pwd, it fails with an error "shell request failed on channel 0". The only way to come out of the issue is to login using a root used and force logout all the other sessions via "request system logout user " command. Is there a way to avoid performing this logout CLI and prevent seeing "shell request failed on channel 0" for SSH connection?

**Comment by apurvaraghu** [comment]
Hello, Can you please provide a reproduction script

**Comment by dineshbaburam91** [comment]
@nishantag Could you please clarify whether you are using `PyEZ` or `Juniper Ansible Collection` to log in? Kindly provide more details about the issue.

**Comment by dineshbaburam91** [comment]
No update from the submitter. So, closing the ticket.

If you have any issues with the latest Juniper Ansible collection, please don't hesitate to open a ticket.
