### ISSUE TITLE
Banner text shows up in diffs randomly

### ISSUE THREAD

**Issue by cvicente** [Juniper/ansible-junos-stdlib#59]
This may not be a bug in this module, but I'd like to ask here in case someone has any clues. The issue is that, when deploying changes, we randomly see these lines in the diffs:

```
[edit system login]
-   message "\n\n          UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED.\n   Explicit permission is required to access or configure this device.\n\n        Unauthorized attempts and actions to access or use this\n         system may result in civil and/or criminal penalties.\n\n  All action taken on or against this device is logged and monitored.\n\n\n    ";
+   message "\n\n          UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED.\n   Explicit permission is required to access or configure this device.\n\n        Unauthorized attempts and actions to access or use this\n         system may result in civil and/or criminal penalties.\n\n  All action taken on or against this device is logged and monitored.\n\n\n    ";
```

The template that covers this section looks like this (we use XML format):

```
  <login>
    <message>


          UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED.
   Explicit permission is required to access or configure this device.

        Unauthorized attempts and actions to access or use this
         system may result in civil and/or criminal penalties.

  All action taken on or against this device is logged and monitored.


    </message>
```

I say "randomly" because we see the diffs coming from some devices, sometimes. 

It is particularly problematic when we do periodic "dry-runs" to detect variations from the canonical configurations.

Thanks in advance for any pointers.

**Comment by shermdog** [comment]
Hi @cvicente ,

Is this also on:
```
Model: qfx3500s
JUNOS Base OS boot [13.2X51-D30.4]
```

Or a different device / version?

Thanks,
-Rick

**Comment by cvicente** [comment]
This happens in pretty much any model we have (MX, SRX, QFX, EX)

**Comment by shermdog** [comment]
You find all the fun stuff Carlos :)

I suspect this is on the Junos side of things.  I searched our bug system found issues around deleted messages persisting, but nothing quite like this.

Could you try to do `load (replace|merge) terminal` on an affected system (several times) to see if you can re-produce this manually?

I can also try this if you give me the software version of the systems.

-Rick

**Comment by cvicente** [comment]
I've tried to reproduce it on the CLI, using `load merge terminal` and also `set system login message` , trying a dozen times on several devices, but I don't see it happen that way.  

Examples where I've seen the problem recently:

* mx240 - 12.3R6.6
* mx480 - 12.3R9.4
* ex2200 - 12.3R6.6
* ex2200 - 12.3R9.4

**Comment by shermdog** [comment]
I *may* have this reproduced on my side.

When I pass the message enclosed in quotes it seems to trigger the diff.

If I pass it in unenclosed it seems to work without issue (at least after a couple hundred automated passes).

```xml
<message>\n\n          UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED.\n   Explicit permission is required to access or configure this device.\n\n        Unauthorized attempts and actions to access or use this\n         system may result in civil and/or criminal penalties.\n\n  All action taken on or against this device is logged and monitored.\n\n\n    </message>
```

So my thinking (hope) is that string is being quoted prior to being passed in.

**Comment by cvicente** [comment]
I tried a combination of quoted, unquoted, with and without encoded carriage returns (\n) to no avail. The only solution was to reduce the banner to a one-liner. I am not seeing diffs any more. Notice that this only when using XML format. I have not tried the other formats.

**Comment by stacywsmith** [comment]
@cvicente I'm closing this old issue. It appears to be a Junos issue rather than a bug with this module. If you are still having the problem, do reach out to me directly and I will help you work with JTAC to resolve the issue.
