### ISSUE TITLE
Has POE in get_facts

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#60]
Same as the has_2RE, it would be useful if get_facts could returns the POE capability of the device as well. (None, POE, POE+)

Thanks

**Comment by shermdog** [comment]
Gathering facts requires a series of RPC calls to be executed which adds some additional delay.  We're looking at some enhancements to the facts mechanism that would optionally provide more extensive facts.  I'll add that to the list.

Thanks,
-Rick

**Comment by spidercensus** [comment]
This would be pretty easy to implement.  However this is actually a request that needs to be put into the [py-junos-eznc facts checker](https://github.com/Juniper/py-junos-eznc/tree/master/lib/jnpr/junos/facts)

**Comment by dgarros** [comment]
Closing  this one as it apply to pyez not ansible
