### ISSUE TITLE
Incorrect value of has_2RE

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#61]
Switches with a single RE return "'has_2RE': True".

For example:
ok: [switch2] => {
    "msg": "{u'domain': u'example.net', u'serialnumber': u'XXX', u'ifd_style': u'SWITCH', u'version_info': {u'major': [12, 3], u'type': u'R', u'build': 6, u'minor': u'6'}, u'version_RE0': u'12.3R6.6', u'RE0': {u'status': u'OK', u'last_reboot_reason': u'0x1:power cycle/failure ', u'model': u'EX2200-48T-4G', u'up_time': u'89 days, 2 hours, 2 minutes, 9 seconds', u'mastership_state': u'master'}, u'hostname': u'switch2', u'fqdn': u'switch2', u'has_2RE': True, u'switch_style': u'VLAN', u'version': u'12.3R6.6', u'master': u'RE0', u'HOME': u'/var/home/xionox', u'model': u'EX2200-48T-4G', u'vc_capable': True, u'personality': u'SWITCH'}"
}

Same thing with a EX4200-48PX

**Comment by shermdog** [comment]
Hi @XioNoX 

Can you please provide the output of (with sanitized serial numbers) from the affected switch:

```
show chassis routing-engine | display xml
```

Thanks,
-Rick

**Comment by XioNoX** [comment]
Here it is:
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.3R6/junos">
    <route-engine-information xmlns="http://xml.juniper.net/junos/12.3R6/junos-chassis">
        <route-engine>
            <slot>0</slot>
            <mastership-state>master</mastership-state>
            <status>OK</status>
            <temperature junos:celsius="26">26 degrees C / 78 degrees F</temperature>
            <cpu-temperature junos:celsius="26">26 degrees C / 78 degrees F</cpu-temperature>
            <memory-dram-size>512</memory-dram-size>
            <memory-buffer-utilization>49</memory-buffer-utilization>
            <cpu-user>6</cpu-user>
            <cpu-background>0</cpu-background>
            <cpu-system>6</cpu-system>
            <cpu-interrupt>0</cpu-interrupt>
            <cpu-idle>89</cpu-idle>
            <model>EX2200-48T-4G</model>
            <serial-number>XXX</serial-number>
            <start-time junos:seconds="1420906005">2015-01-10 16:06:45 UTC</start-time>
            <up-time junos:seconds="7702748">89 days, 3 hours, 39 minutes, 8 seconds</up-time>
            <last-reboot-reason>0x1:power cycle/failure </last-reboot-reason>
            <load-average-one>0.11</load-average-one>
            <load-average-five>0.35</load-average-five>
            <load-average-fifteen>0.39</load-average-fifteen>
        </route-engine>
    </route-engine-information>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>

**Comment by shermdog** [comment]
Please repost with content in a code block.
https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by XioNoX** [comment]
My bad, updated above.

**Comment by shermdog** [comment]
I found the bug and have opened up the issue inside of the PyEZ project (reference above).

Thanks!
