### ISSUE TITLE
This output is shown when the juniper is backed up in Open source platform CBackup.

### ISSUE THREAD

**Issue by Saumil-30** [Juniper/ansible-junos-stdlib#610]
This output is shown when the juniper is backed up in Open source platform CBackup.

How to resolve this issue ?

--------------------------------------------------

##CONFIG##

show configuration | display set | n

##ENDOF_CONFIG##

--------------------------------------------------

**Comment by chidanandpujar** [comment]
Hi @Saumil-30 
     Thanks ,
     Could you please share steps and Ansible playbook details to replicate this issue.

Thanks .

**Comment by dineshbaburam91** [comment]
No update from the submitter. Hence, closing the issue.
