### ISSUE TITLE
Fix the broken link of DayOne JSNAPy book!

### ISSUE THREAD

**Issue by astritm** [Juniper/ansible-junos-stdlib#612]
Issue Type
------
 - Documentation Report

Module Affected
------
juniper.device/docs/jsnapy.rst
juniper.device/plugins/modules/jsnapy.py

Description
------

The current documentation link for JSNAPy in the jsnapy.rst and jsnapy.py files points to an outdated link. The new link is https://www.juniper.net/documentation/en_US/day-one-books/DO_JSNAPy.zip and should be updated in the documentation.

Expected Behavior
------
The documentation link in jsnapy.rst and jsnapy.py should be updated to the new link: https://www.juniper.net/documentation/en_US/day-one-books/DO_JSNAPy.zip.

Actual Behavior
------
The documentation link in jsnapy.rst and snapy.py points to an outdated link: https://www.juniper.net/uk/en/training/jnbooks/day-one/automation-series/jsnapy/.

**Comment by chidanandpujar** [comment]
merged the fix 
https://github.com/Juniper/ansible-junos-stdlib/pull/628
