### ISSUE TITLE
RPC  "get-system-core-dumps" with formats "text" only prints the first line  of rpc-reply

### ISSUE THREAD

**Issue by chidanandpujar** [Juniper/ansible-junos-stdlib#616]
Issue Type
------

 - Bug Report

Module Name
------------------
juniper.device.rpc

juniper.device collection and Python libraries version

              
junos-eznc            2.6.6
            
ansible-junos-stdlib  v1.0.2-collections

OS / Environment
------
All-junos

Summary
------
RPC  "get-system-core-dumps" prints with formats "text" only prints the first line  of rpc-reply with formats "text"
<<get-system-core-dumps format="text"/>

Steps to reproduce
------

yml file
---------

---
- name: Router Upgrade
  hosts: all
  ignore_unreachable: true
  gather_facts: false
  vars:
    ansible_host_key_checking: false
    ansible_connection: local

  tasks:
    - name: Show system core dumps
      juniper.device.rpc:
        rpcs:
          - "get-system-core-dumps"
        formats:
          - "text"
      register: core_dumps

    - name: Print system alarm information
      debug:
        msg: "{{ core_dumps }}"

Run the playbook
ansible-playbook test_core.yml

Expected results
-------------------
show system core-dumps 
/var/crash/*core*: No such file or directory
/var/tmp/*core*: No such file or directory
/var/tmp/pics/*core*: No such file or directory
/var/crash/kernel.*: No such file or directory
/var/jails/rest-api/tmp/*core*: No such file or directory
/tftpboot/corefiles/*core*: No such file or directory

Actual results
------

ok: [test] => {
    "msg": {
        "attrs": null,
        "changed": false,
        "failed": false,
        "format": "text",
        "kwargs": null,
        "msg": "The RPC executed successfully.",
        "rpc": "get-system-core-dumps",
        "stdout": "\n/var/crash/*core*: No such file or directory\n",
        "stdout_lines": [
            "",
            "/var/crash/*core*: No such file or directory"
        ]
    }
}

**Comment by dineshbaburam91** [comment]
Junos Software bug. Internal PR raised for this issue.

**Comment by jnicholson56** [comment]
> Junos Software bug. Internal PR raised for this issue.

Do you have a PR number that I can use to track this issue?

**Comment by dineshbaburam91** [comment]
@jnicholson56  PR 1789911

**Comment by dineshbaburam91** [comment]
Juniper ticket was opened for this issue. Could you track the Juniper PR?
Hence, I am closing this ticket.
