### ISSUE TITLE
Return unreachable instead of failed when unreachable

### ISSUE THREAD

**Issue by XioNoX** [Juniper/ansible-junos-stdlib#62]
Currently, when ansible-junos-stdlib tails to connect to a target host, ansible sees it as "failed" while it should reports it as "unreachable". especially as ansible-playbook has different return code for failed vs unreachable.

For example:
msg: unable to connect to xxx: ConnectTimeoutError(xxx)
[...]
xxx : ok=1    changed=0    unreachable=0    failed=1

Thanks

**Comment by shermdog** [comment]
Hi @XioNoX ,

I dug into the source of Ansible, and unfortunately there is no mechanism available for modules to exit out as unreachable.  Unreachable is in the context of hosts, and with our connection mechanism we use localhost.  If this is something you would like to see available in future versions of Ansible, please open up an issue with them.

https://github.com/ansible/ansible/issues

For background:
https://github.com/ansible/ansible/blob/4ca4d36ae6cb3386703c7be3c3b87bd7da2a106e/lib/ansible/module_utils/basic.py#L1256-L1272

Thanks,
-Rick
