### ISSUE TITLE
Address readthedocs upcoming changes

### ISSUE THREAD

**Issue by ydnath** [Juniper/ansible-junos-stdlib#621]
The Read the Docs build system will start requiring a configuration file v2 (.readthedocs.yaml) starting on September 25, 2023. We are sending weekly notifications about this issue to all impacted users, as well as temporary build failures (brownouts) as the date approaches for those who haven't migrated their projects. The timeline for this deprecation is as follows:
Monday, July 24, 2023: Do the first brownout (temporarily enforce this deprecation) for 12 hours: 00:01 PST to 11:59 PST (noon)
Monday, August 14, 2023: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)
Monday, September 4, 2023: Do a third and final brownout (temporarily enforce this deprecation) for 48 hours: 00:01 PST to September 5, 2023 23:59 PST (midnight)
Monday, September 25, 2023: Fully remove support for building documentation without configuration file v2.

**Comment by chidanandpujar** [comment]
Need to add following .readthedocs.yaml file under docs 
https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by chidanandpujar** [comment]
Fix is merged 
https://github.com/Juniper/ansible-junos-stdlib/pull/627
