### ISSUE TITLE
Commit check var

### ISSUE THREAD

**Issue by Aaronprat** [Juniper/ansible-junos-stdlib#63]
Guys,

I'm trying to use commit check in library/junos_install_config. 
Added commit_check:1 in the play-book but it didnt work.

I changed the script (junos_install_config) to make it work.
I'm not sure if its an issue or if I'm using it wrong. 

Let me know. if its an issue, I'll send you the fix I did.

Thank you,
Aaron Prat

**Comment by shermdog** [comment]
Hi @Aaronprat ,

The module already supports check mode using Ansible's builtin checkmode.

http://docs.ansible.com/playbooks_checkmode.html

If your use case is different please provide more detailed information.

-Rick
