### ISSUE TITLE
Update README to clarify the status of collections vs roles

### ISSUE THREAD

**Issue by ydnath** [Juniper/ansible-junos-stdlib#642]
Issue Type
------

 - Bug Report
 - Feature Idea
 - Documentation Report

Module Name
------

juniper.device collection and Python libraries version

```

```

OS / Environment
------

Summary
------

Steps to reproduce
------

```yaml

```

Expected results

```

```
Actual results
------

```

```

**Comment by dineshbaburam91** [comment]
Updated ReadMe and functional test cases ReadME
