### ISSUE TITLE
Update tests to cover all modules, when using pyez connection plugin

### ISSUE THREAD

**Issue by MicLennartz** [Juniper/ansible-junos-stdlib#643]
Issue Type
------
 - Feature Idea

Module Name
------
all

juniper.device collection and Python libraries version:
most recent stable releases of Python and Ansible

OS / Environment
------
any platform, which is supported as controller by Ansible

Summary
------
Right now the tests in folder `./tests/` are not covering the modules, when running with the pyez connection plugin. We've only one test for the 'rpc' module. And the current structure is not following the Ansible standards to test collections. This is especially critical, since module code is not the same between the two connection plugins.

I like to ask you to update all tests, so that all modules are tested with both supported connection plugins (local / pyez).
Also please update the tests in line with Ansible standards as described here:  
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_testing.html

At the end we like to run CI/CD pipelines for sanity and unit tests on the collections, once the version of Ansible or the core Python modules are bumped to a new release. This is to ensure, that all used collections don't introduce breaking changes in the projects. 

Expected results
------
We can use `ansible-test` as documented to run sanity and unit tests on all modules, together with both connection plugins.

**Comment by dineshbaburam91** [comment]
Fixed. Kindly use ansible v1.0.4 collection release.
