### ISSUE TITLE
Juniper's galaxy module download fails.

### ISSUE THREAD

**Issue by github-20240422** [Juniper/ansible-junos-stdlib#648]
Issue Type
------
 - Documentation Report

Module Name
juniper.device collection and Python libraries version
https://galaxy.ansible.com/ui/repo/published/juniper/device/

ansible --version
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:41: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Dec  1 2023, 12:55:46) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21)]

OS / Environment
EX2300(Junos 23.4R1.9)

Summary
"ansible-galaxy collection install juniper.device" command fails.
-----
ansible-galaxy collection install juniper.device
/usr/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:41: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
 [WARNING]: - collection was NOT installed successfully: missing required
'current_version' from server response (https://galaxy.ansible.com/api/)

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
-----

Expected results
I will probably see results such as successful download on my device.

Actual results
It actually shows the error I attached.

**Comment by dineshbaburam91** [comment]
Could you please install the ansible collection in python3?

Python 2 is no longer supported. Could you upgrade to the latest python3 version?
