### ISSUE TITLE
Playbook fails on existing configuration

### ISSUE THREAD

**Issue by gtrxcbdev** [Juniper/ansible-junos-stdlib#65]
I believe I am running into a bug with either the Ansible module and/or the junos-eznc module.  I have a simple playbook to install a configuration on a device (have tried this on multiple devices, all fail, this is on a EX2200-C, 12.3R6.6, with Ansible vs 1.9.1, Ansible Module v1.1.0, junos-eznc 1.2.0).  

The test scenario is to update the VLAN configuration on one or more ports, the existing configuration has ge-0/0/7 with VL0001 configured and I want to change it to VL0002, this fails as there appears to be no way to update the configuration (the only option I have seen is the overwrite option which blasts the entire configuration).

##### Existing Configuration (snippet)
```
show interfaces ge-0/0/7    
description TEST;
unit 0 {
    family ethernet-switching {
        port-mode access;
        vlan {
            members VL0001-192.168.1.0_24;
        }
    }
}
```

##### YAML File:
```
---
- name: Load Junos Config
  hosts: juniper
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
    - name: Verifying NETCONF
      wait_for: host={{ ansible_ssh_host }} port=830

    - name: Set System Login Message
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=load_config.conf
        overwrite=false
        user={{ juniper_user }}
        logfile="/tmp/junos_ansible.log
```
##### Configuration File:
```
interfaces {
    ge-0/0/7 {
        description TEST;
        unit 0 {
            family ethernet-switching {
                port-mode access;
                vlan {
                    members VL0002;
                }
            }
        }
    }
}
```
##### Ansible Run and Error:
```
ansible-playbook -i /etc/ansible/hosts /etc/ansible/playbooks/load_config.yml 

PLAY [Load Junos Config] ****************************************************** 

TASK: [Verifying NETCONF] ***************************************************** 
ok: [sw01.lab]

TASK: [Update VLAN] ********************************************** 
failed: [sw01.lab] => {"changed": false, "failed": true, "file": "/etc/ansible/playbooks/load_config.conf"}
msg: Unable to commit configuration:error,None,Access interface <ge-0/0/7.0> has more than one vlan member: <VL0002> and <VL0001>

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/load_config.retry

sw01.lab         : ok=1    changed=0    unreachable=0    failed=1
```
Is there a way to update the configuration (or delete the specific stanza prior to the update) for stanza's that can take only a single value or is this just a limitation of the module?  Full disclosure, I have run into this same problem with the junos-eznc module while testing out Python scripts and have found no resolution to this issue either (for that module it was recommended to use the "delete: vlan" command just before the stanza, but that did not work), given that the Junos Ansible module uses junos-eznc I am guessing I am running into the same issue.

**Comment by sdndude** [comment]
Access ports can only have 1 VLAN assigned to them (as you know), so you will need to delete the vlan assignment before you push the config.  It acts the same as if you were on the cmd line.  
I would just add that to the Configuration File in your example, so it deletes the vlan stanza and then adds in the stanza that you want.  I haven't tested this but it should be something similar to the following:

```
interfaces {
    ge-0/0/7 {
        description TEST;
        unit 0 {
            family ethernet-switching {
                port-mode access;
                delete: vlan; 
                vlan {
                    members VL0002;
                }
            }
        }
    }
}

```

This would be easier with the set command if you want to go that route.

**Comment by cvicente** [comment]
Or use XML instead for your config format. It allows you to clearly specify which sections need to be merged, replaced or deleted. E.g.

```
<configuration>
  <interfaces>
      <name>ge-0/0/7</name>
          <description>TEST</description>
            <unit>
                <name>0</name>
                <family>
                    <ethernet-switching>
                        <port-mode>access</port-mode>
                        <vlan operation="replace">
                            <members>VL0002</members>
                        </vlan>
                    </ethernet-switching>
                </family>
            </unit>
      </interfaces>
</configuration>
```

XML has the added benefit of being more easily parsed, so you can do policy checks after your build all  your configs.

**Comment by sdndude** [comment]
Completely agree.  Heck, for that matter even the set notation would be much easier, but the XML is the preferred method if you want to make it "smart"

**Comment by gtrxcbdev** [comment]
Thanks I will give the XML a shot.  I have previously tried using the
delete: vlan; statement with both the Ansible module and with a custom
python script using the junos-eznc module and neither worked (though it is
possible I did something wrong).

**Comment by shermdog** [comment]
Load Replace support provided by #71
