### ISSUE TITLE
TransportError: Not connected to NETCONF server

### ISSUE THREAD

**Issue by cvicente** [Juniper/ansible-junos-stdlib#79]
I've recently started getting errors trying to push configs to a couple of ex4200-48t series switches running 12.3R4.6

Ansible shows:

```
TASK: [Deploy configuration] **************************************************
failed: [device1.domain.net] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/cvicente/.ansible/tmp/ansible-tmp-1439845015.33-50192573969685/junos_install_config", line 2001, in <module>
    main()
  File "/Users/cvicente/.ansible/tmp/ansible-tmp-1439845015.33-50192573969685/junos_install_config", line 399, in main
    _ldr(module)
  File "/Users/cvicente/.ansible/tmp/ansible-tmp-1439845015.33-50192573969685/junos_install_config", line 303, in _load_via_netconf
    dev.close()
  File "/Library/Python/2.7/site-packages/jnpr/junos/device.py", line 502, in close
    self._conn.close_session()
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 156, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/manager.py", line 226, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Library/Python/2.7/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/Library/Python/2.7/site-packages/ncclient/operations/rpc.py", line 291, in _request
    self._session.send(req)
  File "/Library/Python/2.7/site-packages/ncclient/transport/session.py", line 147, in send
    raise TransportError('Not connected to NETCONF server')
ncclient.transport.errors.TransportError: Not connected to NETCONF server


FATAL: all hosts have already failed -- aborting
```

The only error I see in the netconf logs on the device is:

```
Aug 17 20:45:25 [11848] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:e32a4f4c-4520-11e5-9c26-3c15c2d90eda"><get-configuration compare="rollback" rollback="0" format="text"/></nc:rpc>]]>]]>
Aug 17 20:45:25 [11848] Outgoing: <!-- netconf error: syntax error, expecting &lt;rpc&gt; -->
Aug 17 20:45:26 [11848] Outgoing: <ok/>
Aug 17 20:45:26 [11848] Outgoing: <!-- session end at 2015-08-17 20:45:26 UTC -->
```

I'm not sure if it's related or not.

I'm a bit confused because we've been pushing configs to these switches for a long time now.

I'm running junos-py-ez 1.2.2 and ansible-junos-stdlib 1.1.0

I'd be very grateful for any clues.

**Comment by cvicente** [comment]
Did more digging on this. Turns out that this _is_ related to the error above, and the error is dependent upon the configuration contents. This device has two sections of config: system and snmp. Sending both sections together fails. Sending one section at a time (system but no snmp, or snmp but no system) works fine. So it is not that the config contains anything offensive, but perhaps that there's a length (buffer?) issue. Closest thing I found reported was: 

http://forums.juniper.net/t5/SRX-Services-Gateway/strange-NETCONF-error-any-ideas-how-to-debug-the-root-cause/td-p/201349

But no solution was offered.

Again, any ideas on how to approach this would be very appreciated.

**Comment by cvicente** [comment]
Another point is that we have many more EX-4200 units, with the exact same configuration being pushed via netconf, but only these two are running 12.3R4.6.

**Comment by cvicente** [comment]
I noticed that the errors started after we added a user account. It turns out that shortening the user's full name makes the error go away. This feels like a Junos bug, but I wasn't able to find anything in the Changelog for 12.3

Anyways, I'm closing this one for now. Hopefully this monologue will be helpful to someone else :-)

**Comment by ymitsos** [comment]
This behavior and the error message is similar to a case we have identified some times in the past but not in a deterministic way, therefore we ignored it. Now we managed to reproduce it. See https://github.com/ncclient/ncclient/issues/189
