### ISSUE TITLE
install_config throws errors

### ISSUE THREAD

**Issue by blindpet** [Juniper/ansible-junos-stdlib#80]
We have tried on both an EX4200 and SRX240 and get this error using this [playbook](http://pastebin.com/a4mPJjJh). We thought it may be a PyEZ version but we have tried 1.2.2 and 1.2.3
~~~~
TASK: [Install Junos OS package] **********************************************
failed: [10.210.14.170] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/htpcguides/.ansible/tmp/ansible-tmp-1440670135.82-236773385389926/junos_install_os", line 1874, in <module>
    main()
  File "/home/htpcguides/.ansible/tmp/ansible-tmp-1440670135.82-236773385389926/junos_install_os", line 256, in main
    results = junos_install_os(module, dev)
  File "/home/htpcguides/.ansible/tmp/ansible-tmp-1440670135.82-236773385389926/junos_install_os", line 199, in junos_install_os
    ok = sw.install(package, **sw_args)
  File "/home/htpcguides/.local/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 386, in install
    checksum=checksum)
  File "/home/htpcguides/.local/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 267, in safe_copy
    self.put(package, remote_path, progress)
  File "/home/htpcguides/.local/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 131, in put
    scp.put(package, remote_path)
  File "/home/htpcguides/.local/lib/python2.7/site-packages/scp.py", line 154, in put
    self._send_files(files)
  File "/home/htpcguides/.local/lib/python2.7/site-packages/scp.py", line 245, in _send_files
    self._progress(basename, size, 0)
TypeError: update_my_progress() takes exactly 2 arguments (3 given)
~~~~

**Comment by vnitinv** [comment]
Hi @blindpet this issue was due to recent changes in PyEZ (version 1.2.2). It has been fixed and is in github but not in pypi.Will be releasing it in few days. You can install updated code (1.2.3.dev) from github using 
pip install git+https://github.com/Juniper/py-junos-eznc.git

**Comment by blindpet** [comment]
We were using PyEZ 1.2.3.dev0 originally and the same error was thrown :(. We only downgraded to 1.2.2 to see if it fixed the error which it didn't. We installed the Junos role with ansible-galaxy and installed the junos-stdlib using the pip git+ method.

**Comment by blindpet** [comment]
How long ago were updates the stdlib made? We installed using git 4 days ago or so.

**Comment by vnitinv** [comment]
3 days ago I merged the changes. 
"PyEZ 1.2.3.dev0 originally and the same error was thrown" Can you test it once again and share the exception message. also the output for
from jnpr.junos import version
print version.VERSION

**Comment by blindpet** [comment]
We checked the version with pip show junos-eznc and it showed 1.2.3 and then we downgraded to 1.2.2

We installed the std-lib with ansible galaxy which is showing version below, does the Junos role need to be upgraded as well? Should we install the Junos role with ansible-galaxy or using pip install git+https://github.com/Juniper/ansible-junos-stdlib?

~~~~
htpcguides@htpcguides-Portable-PC:~/ansible$ sudo ansible-galaxy install Juniper.junos
- downloading role 'junos', owned by Juniper
- downloading role from https://github.com/Juniper/ansible-junos-stdlib/archive/1.2.0.tar.gz
- extracting Juniper.junos to /etc/ansible/roles/Juniper.junos
- error: the specified role Juniper.junos appears to already exist. Use --force to replace it.
- Juniper.junos was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
~~~~

**Comment by vnitinv** [comment]
"does the Junos role need to be upgraded as well?" No we need not to.

**Comment by vnitinv** [comment]
@blindpet  I doubt with 1.2.3.dev would give this error. Can you install it from github and share the error message (as done in first post)

**Comment by blindpet** [comment]
Looks like we were just unlucky in the dev cycle :)

Managed to test with virtual machine at home. After running these commands I can upgrade the VM's OS using ansible. Thanks.
~~~~
pip install git+https://github.com/Juniper/ansible-junos-stdlib.git
pip install git+https://github.com/Juniper/py-junos-eznc.git
~~~~

**Comment by dharpatel** [comment]
I do have same error. I am using PyEZ version 1.2.2. is it work for version 1.2.3?

**Comment by blindpet** [comment]
I posted the fix above @dharpatel (the two pip install commands)

**Comment by dharpatel** [comment]
1.2.3 works for me.
Thanks
