### ISSUE TITLE
AttributeError' object has no attribute 'xml'  while doing commit_check  (junos_install_config module)

### ISSUE THREAD

**Issue by abhishekmarathe** [Juniper/ansible-junos-stdlib#82]
We are using 'junos_install_config' module to load a new configuration on a pre-configured juniper MX device

Device configuration:

interfaces {
 lt-0/0/10 {
        unit 0 {
            encapsulation ethernet;
            peer-unit 1;
            family inet {
                address 10.1.1.4/31;
            }
        }
		unit 1 {
					encapsulation ethernet;
					peer-unit 0;
					family inet {
						address 10.1.1.5/31;
					}
				}
	}
} 
After doing commit check of following configuration on the juniper MX device through CLI, device reported below mentioned error:
 interfaces {
    lt-0/0/10 {
                unit 1 {
                    peer-unit 1;

        }
}
}

Error:
[edit interfaces]
  'lt-0/0/10'
    unit 0: peer-unit 1 refers to other unit
error: configuration check-out failed

While doing commit check of the same configuration through ansible-playbook using module 'junos_install_config' and got following exception :

failed: [***.**.***.***] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/tmp/.ansible/tmp/ansible-tmp-1442855394.02-81768901013637/junos_install_config", line 1516, in <module>
    main()
  File "/tmp/.ansible/tmp/ansible-tmp-1442855394.02-81768901013637/junos_install_config", line 420, in main
    _ldr(module)
  File "/tmp/.ansible/tmp/ansible-tmp-1442855394.02-81768901013637/junos_install_config", line 288, in _load_via_netconf
    cu.commit_check()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 169, in commit_check
    return JXML.rpc_error(err.xml)
AttributeError: 'exceptions.AttributeError' object has no attribute 'xml'

 
 
 We feel that instead of exception we should have received proper error, can we fix this?
 
 Environment:
  Python 2.7.6
  ansible-playbook 1.5.4
  junos-eznc 1.2.2
  Ubuntu

**Comment by vnitinv** [comment]
@abhishekmarathe can you share the ncclient version. If its 0.4.5 then please downgrade to 0.4.3 using 
pip install ncclient==0.4.3 

I am expecting the reason to be https://github.com/ncclient/ncclient/issues/88

**Comment by abhishekmarathe** [comment]
We are using ncclient version 0.4.5
We will try version 0.4.3 and let you know

**Comment by abhishekmarathe** [comment]
We used the earlier version 0.4.3 of ncclient as recommended and don't see the exception anymore
ansible-playbook is showing proper error message now
Thank you for your help
