### ISSUE TITLE
unable to download Juniper.junos role

### ISSUE THREAD

**Issue by RaviCharanReddy** [Juniper/ansible-junos-stdlib#84]
Hello, 

I am trying to download the Juniper.junos role and I am getting below error.

root@ubuntu:~# ansible-galaxy install Juniper.junos
- downloading role 'junos', owned by Juniper
 [WARNING]: - Juniper.junos was NOT installed successfully: ERROR! - sorry, Juniper.junos was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by vnitinv** [comment]
@RaviCharanReddy I am not facing any issue with the installation. 

$ansible-galaxy install Juniper.junos
- downloading role 'junos', owned by Juniper
- downloading role from https://github.com/Juniper/ansible-junos-stdlib/archive/1.2.0.tar.gz
- extracting Juniper.junos to /etc/ansible/roles/Juniper.junos
- Juniper.junos was installed successfully

**Comment by RaviCharanReddy** [comment]
It worked for me. First time it worked with $sudo ansible-galaxy install Juniper.junos
