### ISSUE TITLE
key based authentication method  for  junos_install_config module 

### ISSUE THREAD

**Issue by abhishekmarathe** [Juniper/ansible-junos-stdlib#85]
We are trying to run junos_install_config module using ssh key based authentication method instead of using password

we have generated public/private rsa key on one of our instance(ubuntu) and have created a user on the MX device with authentication as ssh-rsa

But While trying to use private-key in ansible-playbook junos module (junos_install_config) , ansible-playbook throws  authentication error as "ConnectAuthError"

I have attached yaml file , hosts ,conf and output file for reference 

yaml file :-

```
name: Change description of interface
hosts: all
roles:
 - Juniper.junos
connection: local
gather_facts: no

tasks:
  - name: Change description of interface
    junos_install_config:
        host={{ inventory_hostname }}
        user={{ ansible_ssh_user }}
        port=830
        file=test.conf
        overwrite=false
        replace=false
        timeout=0
        diffs_file=commit_check_log
        logfile=commit_log  
```

test.conf file:-

interfaces{
ge-0/0/0 {
   description "Ansible test";
}
}

host file:-
xxx.xx.xx.xxx ansible_connection=local ansible_ssh_user=testuser ansible_ssh_host=xxx.xx.xx.xxx

Command used for running playbook:-
ansible-playbook -i hosts load_config.yml --private-key="/xxxx/xxxx/xxxx/xx_key" -u testuser -vvvv

Output:-

PLAY [Get Device Facts] *******************************************************

TASK: [Change description of interface] ********************

msg: unable to connect to xxx.xx.xxx.xxx: ConnectAuthError(xxx.xx.xxx.xxx)

FATAL: all hosts have already failed -- aborting

Can you please help us in resolving this issue

**Comment by sdndude** [comment]
Can you ssh to the device on port 830 using the keys?

ssh -p 830 <device IP>

that will at least tell us if we are able to use this over NETCONF or not.

**Comment by abhishekmarathe** [comment]
"ssh -p 830 device IP using keys"  is prompting for a password. If I add the -p 830, I get this following :

PTY allocation request failed on channel 0
shell request failed on channel 0

If I use -p 22, it works. 



But then I added netconf task in my yaml file 
netconf task worked  but junos_install_config failed(ConnectAuthError)



Output

PLAY [test] *******************************************************************

TASK: [Checking NETCONF connectivity] *****************************************
ok: [xxx.xx.xxx.xxx]

TASK: [Change description of interface] ******************************************************************
failed: [xxx.xx.xxx.xxx] => {"failed": true}
msg: unable to connect to xxx.xx.xxx.xxx: ConnectAuthError(xxx.xx.xxx.xxx)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/ubuntu/test.retry

xxx.xxx.xx.xxx            : ok=1    changed=0    unreachable=0    failed=1

**Comment by sdndude** [comment]
The problem is most likely that when you pushed the public key over to the device, you did so with ssh port 22. You need to do it by scp -P 830 <key file> and I think it will work. I am doing this from memory and don;t have a system in front of me, so bear with me.

Since in the playbook you are specifying port 830 and you loaded the public key via port 22 it will never work, it's always wanting the password.

**Comment by abhishekmarathe** [comment]
We are configuring user (for key based authentication) on the MX device using CLI
We are not pushing public key to the MX device for that user

I tried with scp -P 830  but since ssh is not working with port 830 , scp is also failing 
It gives following :

exec request failed on channel 0
lost connection

**Comment by vnitinv** [comment]
@abhishekmarathe I can see you using
Command used for running playbook:-
ansible-playbook -i hosts load_config.yml --private-key="/xxxx/xxxx/xxxx/xx_key" -u testuser -vvvv

even though you are passing --private-key this module is not using this option. I am doing changes where you can specify private key too. Hope that will resolve this issue. Will share you the code ASAP.

**Comment by vnitinv** [comment]
@abhishekmarathe Did you used passphrase too while generating /xxxx/xxxx/xxxx/xx_key?

**Comment by abhishekmarathe** [comment]
No , I did not use passphrase while generating /xxxx/xxxx/xxxx/xx_key

**Comment by vnitinv** [comment]
I have done some changes in my branch
https://github.com/vnitinv/ansible-junos-stdlib/tree/priv_ssh_key
to junos_install_config & junos_get_facts modules. Can you replace these 2 and test in your env. I have tested these and working fine. Corresponding playbook would look like

```yaml
---
- name: Junos ansible examples
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: install config
      junos_install_config:
        host={{ inventory_hostname }}
        user=xxxx
        ssh_private_key_file="/Users/xxxx/xxxkey"
        file=junos-config-op-script.xml
      register: result
```
Note: key was generated without passphrase here.

**Comment by abhishekmarathe** [comment]
I tested in my environment ,  It is working fine
Thank you for your help

**Comment by abhishekmarathe** [comment]
@vnitinv 
Since junos_install_config & junos_get_facts modules worked  successfully for key based authentication, Can you please do these changes in main branch so that we can download these changes using ansible-galaxy install Juniper.junos

**Comment by vnitinv** [comment]
@abhishekmarathe We are discussing this with team. We are also looking for the other better option.
Would you like to do the similar changes to all modules and send us a pull request?

**Comment by DaCookie4u** [comment]
We too get the ConnectAuthError as long as we are using a key with a passphrase. I am not sure this is related but it looks like it.

I used ssh-add to add the key to the authentication agent and do not have to pass any arguments inside the config. But as soon as I protect the key with a passphrase I get an ConnectAuthError. If I remove the passphrase everything works fine again.

All other playbooks work just fine with the protected key. The system asks for the passphrase once and then runs through the playbooks. Any iideas?

**Comment by vnitinv** [comment]
@DaCookie4u Ya this looks to be correlated. Will try to support this asked feature while doing changes for above issue from @abhishekmarathe

**Comment by stacywsmith** [comment]
@DaCookie4u @vnitinv FWIW. I have tested this with latest PyEZ, Netconify, and Juniper Ansible modules from GitHub. As long as the SSH key password is passed into the module as the passwd argument, this seems to be working correctly. Of course, this may depend upon the SSH configuration of the Ansible control host.

**Comment by DaCookie4u** [comment]
OK, it works if I prompt for the password as a variable and pass this variable as a argument to passwd. But if the password includes certain characters they need to be manually escaped.

My colleague uses Linux (I use Mac OS) and he saved his key password in the gnome keyring and it works without the need to pass it. I have the feeling this is more a problem of the module this library actually uses to connect to the juniper.

**Comment by stacywsmith** [comment]
@DaCookie4u You may also want to consider using Ansible vaults to store the key password as described here:
http://www.juniper.net/techpubs/en_US/junos-ansible1.0/topics/task/configuration/junos-ansible-authenticating-users.html

> But if the password includes certain characters they need to be manually escaped.

Can you reproduce this? If so, can you share your play where prompt for the password and then pass into the Juniper module as the passwd argument?

**Comment by DaCookie4u** [comment]
We are using, one central server, but everyone shall use the same playbook with his personal user, so we are unable to either use unprotected private keys or a vault file (since them everybody would be able to see the users ssh-key password).

Here is an example with a password prompt. In case your password contains `"` or `'` you need to escape those.

```
---
- name: get facts
  hosts: all
  connection: local
  gather_facts: no
  vars_prompt:
    - name: passwd
      prompt: "Password"
  roles:
    - Juniper.junos
  tasks:
    - name: gather facts
      junos_get_facts: host={{ inventory_hostname }} passwd={{ passwd }}
      register: junos
    - name: return version
      debug: msg="{{ junos.facts.version }}"
```

It would be best, if whoever opens the ssh connection (I am not sure which module actually does that) is able to prompt for the ssh-key password.

**Comment by DaCookie4u** [comment]
@abhishekmarathe was your key registered with the ssh-agent? Did `ssh-add -l` list it? Because this way I did not have to define the ssh-key inside ansible.

**Comment by stacywsmith** [comment]
@ DaCookie4u

> We are using, one central server, but everyone shall use the same playbook with his personal user, so
> we are unable to either use unprotected private keys or a vault file (since them everybody would be
>  able to see the users ssh-key password).

In your messages to @abhishekmarathe you mention ssh-agent works for you. That sounds like it might be the best solution for your requirements. Is there any problem using ssh-agent?

> Here is an example with a password prompt. In case your password contains " or ' you need to
> escape those.

Yes. This is a result of the fact that Ansible playbooks are YAML files, and Jinja2 {{ passwd }} variable expression simply gets substituted with the value of the passwd variable. If that value isn't a valid YAML string, the syntax of the playbook isn't valid YAML. You can mitigate some of this by placing single-quotes around the the Jinja2 variable expression. So, passwd={{ passwd }} becomes passwd='{{ passwd }}'. However, this still fails if the password contains a single quote.

This is a generic Ansible/YAML/Jinja2 issue with any argument to a module. The problem is that, unlike most modules, the Junos modules use arguments to pass their authentication parameters.

Using ssh-agent bypasses this issue as well.

**Comment by DaCookie4u** [comment]
@stacewsmit
Yes it works, but it merely saves me from pointing ansible to the key via config or inventory. As soon as I protect it with a passphrase the junos-stdlib throws the `ConnectAuthError`. As a next step I tried to use `ssh-add -K` to store the passphrase for the key inside the keychain, but no luck there either. Maybe this is an (Mac) OS specific problem. I am unsure whether this works on another OS.

I know that the quotation is a YAML/Jinja2 issue. But IMO it makes the use of `vars_prompt` to feed the passphrase into the junos-stdlib not feasable.

**Comment by mtucker502** [comment]
@vnitinv Can you merge this into main? We need this for a customer quickly.

**Comment by stacywsmith** [comment]
With the implementation of a common connection and authentication infrastructure in #278, this is now supported for all modules.

Given the following playbook:
```
---
- name: "Print Junos Version"
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get Junos Facts"
      juniper_junos_facts:
    - name: "Print Version"
      debug:
        var: junos.version
```
and this configuration on the target Junos device:
```
user@r0> show configuration system login 
user key_user {
    uid 2005;
    class super-user;
    authentication {
        ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxmshLNFt4g9lYkZPpXRiFRhWehEsBPlynoiZmRwkEphU6FA1rDUbMqIfLmFQn+lB/aJNhn0nyxZV21JquCBMY+80t4F6E37dmiE6dyzIiD7un78z2ullW8Bqn5Gq3kV9Vpo/8NfI+Gml0L9c/Q2AlO7uX2DNSDjNx9Oj3MUlNOmAueQyY+IIGBlcf/SxY+UeTDZgv0IyBxj1a8431X1HKnuVhlQ+TieNW6bJn9tSUHEYezJRg1AMVboGFmhiGaR+LBYPER5IVwgMivxvt/8FLRMOUbYiJZm3yZ2JigIa02k8jPAwi3iI/+oLMXHM+7BWqhpywaa7lEneBnInzFiJ1 user@h0"; ## SECRET-DATA
    }
}
...
```

The corresponding private key for `key_user` was stored in `~/.ssh/my_key_w_passphrase` on the Ansible control machine and had a passphrase of `user'"123` (contains both a single-quote and double-quote).

The playbook was then invoked with:
```
user@h0:~$ ansible-playbook --limit r0 --user key_user --private-key ~/.ssh/my_key_w_passphrase -k ./pb.test.yaml 
SSH password: 

PLAY [Print Junos Version] *********************************************************************************************

TASK [Get Junos Facts] *************************************************************************************************
ok: [r0]

TASK [Print Version] ***************************************************************************************************
ok: [r0] => {
    "junos.version": "17.3R1.9"
}

PLAY RECAP *************************************************************************************************************
r0                         : ok=2    changed=0    unreachable=0    failed=0   
```

This used the `--user` command line parameter to specify the user, the `--private-key` command line parameter to specify the private key, and the `-k` command line parameter to prompt for the SSH passphrase. This worked even with the passphrase containing both single and double quotes.

The user, private key file, and passphrase could have alternatively been specified using the `user`, `ssh_private_key_file`, and `passwd` options to the module.

However, any Ansible variable whos value contains a single and/or double quote will be subject to the issues with YAML/Jinja2 escaping/quoting.
