### ISSUE TITLE
Junos_install_config throw this error "msg: failure to load configuration, aborting."

### ISSUE THREAD

**Issue by dharpatel** [Juniper/ansible-junos-stdlib#86]
I have created ansible module call noob-ex that will push minimal configuration  on the ex device and to test this module I am using EX4500 device. my device is factory reset it's just new box having no configuration. At this stage when I tried to run this ansible playbook I got error like "msg: failure to load configuration, aborting"
Can anyone help me why I am getting this error? I am using pyez version 1.2.3

Below are my playbooks

# vars main/yml file

node:
    console:
     server: x.x.x.x
     port: xxxx
 oob:
     noob_ip_addr: x.x.x.x

oob:
    gateway: x.x.x.x
    networks: x.x.x.x

netconf_user: xxxxx
netconf_passwd: lxxxxx

# Tasks/main.yml

 task file for ansible-role-noob-ex
- name: Creating NOOB config
  template: src=noob.j2 dest={{ build_dir }}/noob.conf

- name: Checking NETCONF connectivity
  wait_for: host={{ inventory_hostname }} port={{ netconf_port }} timeout=5
  register: netconf_result
  ignore_errors: True

- name: loading minimal management configuration file
  when: netconf_result|failed
  junos_install_config:
    host={{ inventory_hostname }}
    user=root
    console="--telnet={{ node.console.server }},{{ node.console.port}}"
    file={{ build_dir }}/noob.conf
    overwrite=yes
    logfile={{ log }}

# ansible Run and Error
dpatel@dharpatel-ubuntu:~/Desktop/Ansible-Modules$ ansible-playbook ex-test.yml 

PLAY [all_hosts] ************************************************************** 

TASK: [ansible-role-noob-ex | Creating NOOB config] *************************** 
ok: [10.13.106.246]

TASK: [ansible-role-noob-ex | Checking NETCONF connectivity] ****************** 
failed: [10.13.106.246] => {"elapsed": 6, "failed": true, "item": ""}
msg: Timeout when waiting for 10.13.106.246:830
...ignoring

TASK: [ansible-role-noob-ex | loading minimal management configuration file] *** 
failed: [10.13.106.246] => {"failed": true, "item": ""}
msg: failure to load configuration, aborting.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/dpatel/ex-test.retry

10.13.106.246              : ok=2    changed=0    unreachable=0    failed=1

**Comment by vnitinv** [comment]
@dharpatel Sorry for the delay.Are you still stuck at this issue? Can you share the config used

**Comment by dharpatel** [comment]
@vnitinv I got solution for this problem. Thanks!
