### ISSUE TITLE
junos_install_config fails to load config with "Unable to load config: 'list' object has no attribute 'getiterator'" error

### ISSUE THREAD

**Issue by dgjnpr** [Juniper/ansible-junos-stdlib#87]
I am getting the following error when using the junos_install_config module (v1.2.0):

TASK: [commit_config | Pushing config ... please wait] ************************ 
failed: [crtj-si38-0001] => {"failed": true}
msg: Unable to load config: 'list' object has no attribute 'getiterator'

The play is common across all devices but I only get the error with certain ones. For others it is working correctly. Here's the play:

- name: Pushing config ... please wait
  ignore_errors: True
  junos_install_config:
    host={{ inventory_hostname }}
    user={{ netconf_user }}
    port={{ netconf_port }}
    passwd={{ netconf_passwd }}
    file={{ junos_conf }}
    overwrite=yes
    logfile={{ log }}
    diffs_file=/var/tmp/build/log/{{ inventory_hostname }}-diff-{{ build }}.log
    comment="Jenkins {{ build }}"
    timeout=300

I've located the offending code. It happens within the cu.load(**load_args) call within the junos_install_config module. It is not clear to me why load_args is not iterable in certain circumstances.

**Comment by vnitinv** [comment]
@dgjnpr which version of PyEZ and ncclient are you using. 

If ncclient version is 0.4.5, We are aware of this issue. We are trying to fix this ASAP. This is caused due to a bug in ncclient https://github.com/ncclient/ncclient/issues/88
For now do install ncclient last stable version 0.4.3 using.

pip install ncclient==0.4.3

For more detail do have a look to https://github.com/Juniper/ansible-junos-stdlib/issues/82

**Comment by dgjnpr** [comment]
@vnitinv thanks.

I was using ncclient 0.4.5. I've downgraded to 0.4.3. I'm now getting the following stack trace (sometimes):

Traceback (most recent call last):
  File "./patchchecker.py", line 84, in <module>
    cu.load(cfg, format='set', merge=True)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 377, in load
    return try_load(rpc_contents, rpc_xattrs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 343, in try_load
    raise ConfigLoadError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.ConfigLoadError: ConfigLoadError(severity: error, bad_element: None, message: internal communications error (tag 'configuration-set') expecting <configuration-text>)

I'm running PYEZ 1.2.3

**Comment by dgjnpr** [comment]
ok, scratch that. using ncclient v0.4.3 has fixed the problem.

My additional problem related to trying to apply set configuration to a devices that doesn't support that via netconf.

Problem fixed. :)
