### ISSUE TITLE
ConnectAuthError when using passphrased ssh key

### ISSUE THREAD

**Issue by DaCookie4u** [Juniper/ansible-junos-stdlib#92]
I am trying to get the library to work with ssh-key authentication. If the key is not protected by a password everything is fine. As soon as I protect it with a password I get the ConnectAuthError.

Other playbooks using the OpenSSH implementation connecting to Linux servers work just fine with the password protected key. I just get prompted by the system once for the password and they run.

Best regards,
Jesse

**Comment by stacywsmith** [comment]
Ansible communicates with Junos devices different than most managed nodes.

With most managed nodes, Ansible makes an SSH connection to the node, pushes modules to the node, and executes the modules on the node. In this mode, Ansible is making the SSH connection.

With Junos  devices, Ansible makes a "local" connection and executes the module directly on the local machine. The module then makes a NETCONF-over-SSH connection to the Junos device. In this mode, it's the module that is making the SSH connection.

For Junos devices using a password protected SSH key, you MUST specify the "passwd" option to pass the password to the module.

There are a few ways the password can be passed to the module.
This link covers how to prompt for the password, or use a vault to store the password:
http://www.juniper.net/techpubs/en_US/junos-ansible1.0/topics/task/configuration/junos-ansible-authenticating-users.html
