### ISSUE TITLE
junos_commit module does not support timeout argument

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/ansible-junos-stdlib#96]
If the junos_install_config module is used with the confirm option, then another commit needs to be done with the junos_commit module in order to confirm the commit.

If the configuration is large and/or the device is slow, then commits may take longer than the default timeout of 30 seconds. In this case, the junos_commit module will fail due to the default 30 second timeout being exceeded.

The junos_install_config module already supports a timeout argument to avoid this situation. The junos_commit module simply needs to support a corresponding timeout argument.

**Comment by fooelisa** [comment]
+1 that would be great!

**Comment by stacywsmith** [comment]
This suggestion has already been implemented by #97.
